### ISSUE TITLE
affiliateId ei tunnu toimivan

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#10]
Hei,

teemme login-pyynnön seuraavasti:
```
{"type":"STANDARD_LOGIN","login":"username","password":"salasana","affiliateId":"000000"}
```
Mutta nyt näyttää kuitenkin siltä, ettei tuo kumppanuustunnus toimi oikein eikä samassa sessiossa kirjatut vedot näy kumppanilla. Missä mahtaa olla vika?

**Comment by tpokki** [comment]
Moi,

Suosittelen että otat yhteyttä Veikkauksen asiakaspalveluun (https://www.veikkaus.fi/fi/asiakaspalvelu), minne voit jättää tarkemmat tiedot ongelmasta (pelitili, kumppanuustunnus, sekä ajankohta koska pelit on pelattu).
