### ISSUE TITLE
Kaksari-rivien lähetys 

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#102]
Olen taistellut viimepäivät kaksari-rivien lähetyksen kanssa. Embarcaderon Rest Debuggerilla edes aiemmin toimineen kyselyt eivät enää jostain syystä toimi, vaikka ovat aiemmin toimineetkin. Saan seuraavan virheilmoituksen

![image](https://user-images.githubusercontent.com/22799660/52287125-3ee95380-2972-11e9-91f5-c9859c05815d.png)
 
Debuggerissa ei ole mitään asetusta, jolla ssl versioon voisi vaikuttaa.
Request:
![image](https://user-images.githubusercontent.com/22799660/52287144-4d376f80-2972-11e9-8c5b-70eed6034195.png)
 
Parameters:
 
![image](https://user-images.githubusercontent.com/22799660/52287164-57f20480-2972-11e9-8adb-5e18d7319887.png)

Authentication:
![image](https://user-images.githubusercontent.com/22799660/52287189-64765d00-2972-11e9-9504-53e21941db58.png)

Osaatteko sanoa onko noissa jotain täyssin pielessä ?

Harmittaa, kun ohjelma olisi valmis kunhan saisi lähetysmoottorin kuntoon.

**Comment by ceel** [comment]
Näyttäisi, että softa yrittää käyttää ssl3:a, joten voisiko olla kyse samasta asiasta kuin tässä tiketissä https://github.com/VeikkausOy/sport-games-robot/issues/84 ?

**Comment by Ylikerroin** [comment]
Kiitos nopeasta vastauksesta. Katson mitä voin tehdä asialle, kun pääsen koneen äärelle. Lähetetty Huawei-matkapuhelimestani-------- Alkuperäinen viesti --------Aihe: Re: [VeikkausOy/sport-games-robot] Kaksari-rivien lähetys  (#102)Lähettäjä: Juha Paananen Vastaanottaja: VeikkausOy/sport-games-robot Kopio: Ylikerroin ,Author Näyttäisi, että softa yrittää käyttää ssl3:a, joten voisiko olla kyse samasta asiasta kuin tässä tiketissä #84 ?

**Comment by Ylikerroin** [comment]
Ongelma ei ole ratkennut. Virheilmoitus on tosin muuttunut, nyt:
![image](https://user-images.githubusercontent.com/22799660/53282722-5ed79000-3744-11e9-9487-1d6ab7bbfc1b.png)

SSL asetus on 
![image](https://user-images.githubusercontent.com/22799660/53282736-bd047300-3744-11e9-8521-11eb705741e1.png)

Outoa lisäksi on, että tilille kirjautuminen ja saldon haku samalla komponentilla ja asetuksilla (lukuunottamatta IdHTTP1->Request->Accept ks. alla) onnistuu, mutta rivin lähetys kaatuu

> UnicodeString s = totoJson->ToString();
TStringStream* JsonToSend = new TStringStream( s );
UnicodeString url = "https://www.veikkaus.fi/api/toto-wager/v1/bet/{poolId}";
url = StringReplace( url, "{poolId}", poolId, TReplaceFlags() <<rfReplaceAll );
Palaute->Clear();
IdHTTP1->Request->Accept = "application/json"; // kertoimia noudettaessa
IdHTTP1->Post( url, JsonToSend, Palaute ); // kaatuu välittömästi

Olisin hyvin onnellinen jos ongelmaan löytyisi ratkaisu.

**Comment by tmansner** [comment]
Hei!

Tuo 404 virhe viittaisi siihen että ohjelmasi tekee jonkin kutsun väärin. Tarkista, että toimit tuon toto pelaamisen ohjeen mukaisesti ([TOTO -  pelaaminen](https://github.com/VeikkausOy/sport-games-robot#pelaaminen-1)). 

Jos ei sitä kautta ratkea, voit olla yhteydessä [asiakaspalveluun](https://www.veikkaus.fi/asiakaspalvelu) ja jättää sinne tarkemmat tiedot kuten pelaajatunnuksen, kellonajan ja tiketin tunnisteen ongelman selvittämistä varten.
