### ISSUE TITLE
Voitto-osuus GP

### ISSUE THREAD

**Issue by matsfr** [VeikkausOy/sport-games-robot#105]
Vakio Grand Prix voitto-osuus spekulointi ei onnistu.
Onko se estetty nykyään?

**Comment by tmansner** [comment]
Hei!

Voitto-osuus laskuria ei ole tältä osin muutettu, Vakiossa ei vaan ole koskaan tuettu voitto-osuus laskentaa kohteille, joissa on yli 14 kohdetta.
