### ISSUE TITLE
/api/v1/sports/events suodatus

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#106]
Hei,

onko mahdollista suodattaa /api/v1/sports/events -haun tuloksia palvelinpäässä eli lisäämällä GET-pyyntöön parametreja tyyliin /api/v1/sports/events?game-names=EBET&sport-ids=1,3 (haetaan vain jalkapallo- ja jääkiekko-Eventit)?

En ole kokeilemalla ainakaan löytänyt tuollaisia. Ainoastaan game-names ja event-ids on tiedossa. Mutta onko muita olemassa? 

Ja sama kysymys koskien tuon osoitteen lisäksi myös Pitkäveto-kohtaista osoitetta /appapi/ebet?lang=fi&v=2 - onko siihen mahdollista lisätä suodattavia parametreja perään?

**Comment by umeetiusbaar** [comment]
Oikeastaan kysymys pitäisi muuttaa koskemaan Pitkävedon Draw -hakua eikä Eventtejä. Eli onko mahdollista ladata kaikki Pitkäveto-Draw:t yhdellä pyynnöllä? 
Nyt tuntuu ainoa tapa olevan ladata ensin Eventit ja sitten niille kullekin (batchaten sopivasti) ko. Eventin / Eventtien Draw:t. Eli tulee useita pyyntöjä Veikkauksen suuntaan.

**Comment by tpokki** [comment]
Hei, ei ole valitettavasti mahdollista. Pitkävedon tapahtumat voi tosiaan hakea vain tapahtumittain. Vaikka pyyntöjä täytyykin tehdä useampia, niin ne tulevat välimuistista kun haku tehdään yksittäiselle tapahtumalle.
Suosittelen kuitenkin malttia pitkävedon kertoimien haussa, kun ne eivät kovin tiuhaan kuitenkaan päivity. 

> Asiakkaiden ohjelmien ei kannata kysellä Veikkauksen järjestelmästä kerroinpäivityksiä alle 15 sekunnin syklillä. Esimerkiksi Pitkävetoon tulee keskimäärin n. 1000 kerroinpäivitystä päivässä, mikä tekee laskennallisesti n. 0,7 päivistystä minuutissa. Huomioitavaa kuitenkin on, ettei todellisuudessa päivityksiä tule näinkään tiuhaan, koska samalla kertaa lähetetään joko useiden otteluiden kerroinpäivitykset tai ainakin saman ottelun kaikkien markkinoiden kertoimet.
