### ISSUE TITLE
Toto-rivin pelaaminen ei onnistu

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#108]
Pitkästä aikaa koitan pelata ohjelmallani T4-rivejä. Missä mahtaa olla vika, kun tilille kirjautuminen onnistuu, mutta rivi lähetyksessä saan ilmoituksen:

![image](https://user-images.githubusercontent.com/22799660/64060520-81a49e80-cbd6-11e9-8c18-b1f19caf591f.png)

Lähetys tapahtuu pieninä järjestelminä joista ensimmäinen on

{proposals:[{gameName:TOTO,type:T4,composed:false,selections:[[1],[3],[5],[4,9,11,13]],stake:20,cost:80}],totalCost:80}

**Comment by tpokki** [comment]
404 viittää siihen että pyynnön metodi ja urli -kombinaatio on väärin.

Yksi tapa selvittää asiaa on pelata sama peli veikkauksen sivulla, ja tutkia sivun lähettämiä pyyntöjä esim firefoxin firebug laajennuksen avulla (Chromelle, Safarille ja IE:lle löytyy vastaavat "kehitystyökalut"). Tätä informaatiota voi sitten verrata siihen miten oma ohjelmisto yrittää käyttää rajapintoja.
