### ISSUE TITLE
Rejected bet with code MIDNIGHT_BREAK

### ISSUE THREAD

**Issue by fizu** [VeikkausOy/sport-games-robot#11]
Hi again,

I recently got some of my bets rejected with code MIDNIGHT_BREAK. What does this mean? (I know that this has nothing to do with this client side reference application, but maybe someone here knows)

Received response:
[{"status":"REJECTED","error":{"code":"MIDNIGHT_BREAK"},"type":"NORMAL","drawId":"85161","gameName":"SCORE","price":700,"selections":[{"systemBetType":"NORMAL","isQuickpick":false,"score":{"home":[0,1,2,2,2,3,3],"away":[6,2,1,2,3,2,3]}}],"stake":100}]

Thanks for any help in advance!

**Comment by ceel** [comment]
Hello,

Afaik, that's a scheduled break needed for batch jobs and stuff that need to be atomically executed.

Hope this helps :)

**Comment by fizu** [comment]
Hi,

Yeah, it sure sounds like it. Does someone know how regularly these maintenance breaks occur? I seem to sometimes miss placing bets, because of this maintenance break. If it occurs for example once a week in given time (and I knew the time), I could bet before the break.

Thank you @ceel for your quick response!

**Comment by tpokki** [comment]
Hi, there might be a short few second break at midnight. If you receive MIDNIGHT_BREAK error code around midnight, you can try to send the wager again after for example 30 seconds.

**Comment by fizu** [comment]
Ok, so it is usually just a bad luck to hit this error.

The only time that I've had any real problems (with this error code) was 28.4. when I received this error multiple times between 1:53 AM and 2:23 AM. But maybe that was only one bad night.

Thanks for the response :+1:
