### ISSUE TITLE
Troikka - kertoimista

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#110]
Aloin pitkästä aikaa ihmettelemään näitä ravikertoimia.

Oheisessa esimerkissä on kyse Charlottenlundin 2-lähdön troikka. 

![image](https://user-images.githubusercontent.com/22799660/68966453-c9ef5800-07e6-11ea-8e7c-9c9815a1dfda.png)

Jo se, että vaihto on epämääräinen 1 971,29€  on ihmeellinen, kun minimi panoksen pitäisi olla 50 centtiä, niin kuinka vaihto voi olla x xxx,29 €. Onko joku onnistunut pelaamaan riviä 29 centillä? Samasta syystä (min. panos 0,5€) pitäisi maks. kertoimen olla riville, jota on pelattu min. panoksella 1 kpl olla 1 379,91 €/0,5€ = 2759,82. Kuitenkin veikkaus antaa kertoimeksi 7262,68 eli riviä olisi onnistuttu pelaamaan 0,19 €:llä. 

Voisiko joku selittäää nämä mistä nämä kummallisuudet johtuvat.

**Comment by TapaniJVeikkaus** [comment]
Hei ja kiitos huomiosta, pyydän jonkun  totopeliasiantuntijamme vastaamaan. yst terv tapani j.

**Comment by Ylikerroin** [comment]
Ok, olisi varmaan pitänyt tietää.
