### ISSUE TITLE
veikkauksen oma monivetorobotti ei näytä kerrointa

### ISSUE THREAD

**Issue by mLeonnas** [VeikkausOy/sport-games-robot#113]
kun rivi on lyöty sisään robottiin ja valitsen "voitto-osuudet", niin robotti ei löydä kerrointa vaan herjaa "invalid procedure call or argument" . rivin pelaaminen kuitenkin toimii...

**Comment by ceel** [comment]
Avataan uusiksi, jos toistuu vielä uusilla versioilla.
