### ISSUE TITLE
Pitkäveto kertoimet exeliin?

### ISSUE THREAD

**Issue by aki2007** [VeikkausOy/sport-games-robot#114]
MOI!!

Auttakaa amatööriä. Miten saan muokattua exel-pohjan moniveto osuuden niin, että saan haettua pitkävetojen kertoimet monivetojen tilalle. 

Kiitoksia avusta!
Aki

**Comment by TapaniJVeikkaus** [comment]
Moi, ks. suljetuista esim. https://github.com/VeikkausOy/sport-games-robot/issues/72#issuecomment-334995139 hyvää vuodenvaihdetta
