### ISSUE TITLE
Videon embedurl runnerin prevStarts listan objektin mukana

### ISSUE THREAD

**Issue by J-E-A-P** [VeikkausOy/sport-games-robot#116]
Seuraavasta endpointista `/api/toto-info/v1/race/{raceId}/runners` on mahdollista saada veikkausmedia linkki hevosen edellisistä suorituksista. Onko mahdollista saada myös videon upotuslinkki samaan vastaukseen?
![image](https://user-images.githubusercontent.com/28506914/73598490-8d0f4380-4541-11ea-9633-3034f6fbc6cd.png)

**Comment by TapaniJVeikkaus** [comment]
Moi, kertoisitko, miten videoupotuslinkki liittyy ohjelmalliseen pelaamiseesi? Mikä on käyttötapaus ja palvelu, johon tuota tarvitset? Näiden API-palvelujemme kokonaisuus ja tarkoitus on kuvattu tuolla etusivulla. yst terv tapani j.

**Comment by J-E-A-P** [comment]
> Moi, kertoisitko, miten videoupotuslinkki liittyy ohjelmalliseen pelaamiseesi? Mikä on käyttötapaus ja palvelu, johon tuota tarvitset? Näiden API-palvelujemme kokonaisuus ja tarkoitus on kuvattu tuolla etusivulla. yst terv tapani j.

Moi, minulla (localhostissa) selaimessa pyörivä datan visualisointi appi. Tarkoitus on tehdä tulosdatan analysoinnin käyttökokemuksesta itselle mukavampaa. Tuon kyseisen videonupotuslinkin avulla saisin  edellisten ravien videot ryhmiteltyä tuolla tulevien lähtöjen hevosten avulla omaan appiini, joten minun ei tarvitsisi niitä erikseen katsoa veikkausmediasta.

**Comment by TapaniJVeikkaus** [comment]
Moi taas ja kiitti tarkennuksesta, kiinnostavaa. Toi vaan taitaa olla liian yksityinen ja spesiaali käyttötapaus meidän API-kehittäjille. Rajapintojen tarkoitus kun on välittää vaan ajankohtaisia pelikohteita ohjelmallisesti pelattavaksi. Hyvää talven jatkoa!
