### ISSUE TITLE
VBA-robotti hidastunut

### ISSUE THREAD

**Issue by Vakioija** [VeikkausOy/sport-games-robot#117]
Moro,

Tästä on jo hyvä tovi aikaa, kun tuo VBA-sovellus hidastui mielettömästi. Sanotaanko yli vuosi sitten.
Tiedä sitten mitä tapahtui, mutta sekä vakioveikkauksen kohteiden sekä voitto-osuuksien haku kestää, ja varsinkin riviensyöttö. 2 000 GP vakiorivin pelaaminen on syytä aloittaa jo sunnuntaina ennen puolta päivää. Nyt kunnon vakioiden ollessa tauolla olisi mukava saada selvyyttä onko tähän ongelmaan mitään parannusta olemassa. 
Ravien T-pelien pelitiedostojen nopeutta kun saisi vakioihin, niin kyllä kelpaisi.

Terveisin,

Tarmo

**Comment by TapaniJVeikkaus** [comment]
Moro Tarmo ja kiitos viestistä. Tutkimme asiaa ja havaitsimme nykyisen JSON-komponentin hitauden. Totesimme myös uuden JSON-komponentin toimivan paremmin, eli, tiedämme, miten korjaus tehdään, ja pistämme sen työjonoon. Aurinkoista keväänjatkoa poikkeusoloissa.
yst terv tapani j.
