### ISSUE TITLE
REST rajapintaa muille kuin urheilupeleille?

### ISSUE THREAD

**Issue by pekkalaaksonen** [VeikkausOy/sport-games-robot#119]
Hei,

Onko Veikkauksen REST rajapinnan kautta mahdollista hakea tietoa muista omista peleistä kuin urheilupeleistä, kuten esim. lotosta tai vaikka eurojackpotista?

**Comment by TapaniJVeikkaus** [comment]
Hei, tämä palvelu on omistettu joidenkin urheilupelien ohjelmalliseen pelaamiseen. Muiden pelien rajapintoja, kutsuja ja vastauksia voit tutkailla esim. veikkaus.fi 'Lotot ja arvontapelit' -osiosta.
