### ISSUE TITLE
Muutospyyntö /draws/MULTISCORE/(veikkausId)/odds endpointille

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#120]
Olisiko mahdollista: 

1. lisätä pyynnön JSON sanomaan parametri joka määrittäisi, että palautetaan vain sellaisia kombinaatioita, joille on asetettu vetoja. 

2. palauttaa yhdessä vastauksessa enemmän kuin 32767 riviä. Tuo arvo on siis tämän hetkinen pageSize arvon katto. Toivomus olisi, että lisäisitte sinne "All" mahdolliseksi parametriksi. Kelpaa kyllä kaikki muut vaihtoehdot myös millä saisi enemmän rivejä haetua yhdellä pyynnöllä. 

Olen hyvin tietoinen että on olemassa vuosisadan takainen monivedopn .zip palvelu, mutta se ei oikein palvele tarkoitustaan (enää). Olettamus on, että veikkausken REST-rajapinta tarjoaisi kaiken tarvittavan toiminallisuuden pelaamiseen ja tietoformaattina olisi ulospäin kaikkialla JSON.

**Comment by TapaniJVeikkaus** [comment]
Tervehdys, ja kiitos viestistä.

Nykyisin käytössä olevilla rajapinnoilla ehdottamasi muutokset eivät ole helppoja, emmekä niihin ryhdy, mutta meillä on vireillä myös kerroinrajapintaan vaikuttava rajapintojen rakenneuudistus, jonka jälkeen parannusehdotuksesi voisivat tulla kyseeseen.

Ensimmäisen ehdotuksesi mukainen parannus vaikuttaa melko suoraviivaiselta muutokselta, mutta toinen kohta ei. Mielestämme ei ole kestävää eikä fiksua sallia laajojen aineistojen lataamista dynaamisesti pelijärjestelmästä, eli zip-tiedostojen tarkoitus ei ole kadonnut mihinkään. Sen sijaan tuon voisi hoitaa esim. niin, että tuodaan nykyisten zip-tiedostojen rinnalle ladattava JSON-tiedosto, joka on samassa muodossa kuin varsinainen JSON API.

Selvittelemme ehdottamasi muutosten toteutuksia ja kustannuksia tarkemmin, ja pohdimme, kuinka voisimme parantaa palvelujamme näiltäkin osin. Kiitos aktiivisuudestasi ja hyvää kesänjatkoa. yst terv tapani jämsen

**Comment by qwerty667** [comment]
Itse en koe zip-tiedostoa ongelmaksi, mutta vakiossa sitä ei ole ja 32 767:n maksimi on varsin rajoittava. Jos haluaa hakea vakio ykkösen koko datan, nykyisen maksimin puitteissa tämä onnistuu 3^9 eli 19 683 rivin palasina, mikä on 1/81 rivien kokonaismäärästä 1 594 323.

Jos maksimin saisi edes tuplattua 65 534:ään, voisi yhden haun koon triplata 3^10:een = 59 049, mikä auttaisi jo paljon.

**Comment by umeetiusbaar** [comment]
Olen samaa mieltä kuin @qwerty667 ja toivoisinkin myös vakioon zip-kerrointiedostoja, jotta myös yli 14 kohteen vakioiden kertoimet saisi ladattua. JSON- ja/tai CSV-muodossa.

**Comment by VeikkausOy** [comment]
Vakion zip-kerrointiedostot on tuotu saataville, linkit on nyt lisätty README-tiedostoon.

**Comment by qwerty667** [comment]
Vakio 1:n kerroinzipissä on tällä hetkellä 616 880 riviä. Kun kombinaatioita on noin 1,6 miljoonaa niin Ilmeisesti zipistä puuttuu kombinaatiot, joita ei ole pelattu?

**Comment by qwerty667** [comment]
Näkyy tosiaan menevän niin, että zipistä puuuttuu pelaamattomat kombinaatiot.

Kun Excelillä hakee eilisen vakio 1:n rivit nyt sunnuntaina kohteen sulkeuduttua, se näyttää myös pelaamattomat rivit muodossa pelattu 0 kpl, voitto-osuus 0,00. Kun saman rivin haki Excelillä kohteen ollessa vielä auki, se näytti pelattu 1 kpl, voitto-osuus 600 000,00.

Ilmeisesti avonaisessa kohteessa on käytössä laskukaava kombinaatioon pelattujen rivien määrä +1 (eli näen kombinaation tilanteen oletuksella, että pelaan siihen itse yhden rivin). Kohteen sulkeuduttua tuo +1 poistuu käytöstä.

Zipistä 0 kpl pelatut kombinaatio puuttuvat. +1-laskukaava ei ole zipissä käytössä edes kohteen ollessa auki.

Tämän jos saisi fi8ksattua niin olisi varsin jees. Pelaamattomat rivit ovat nyt tavallista kiinnostavampia, kun miljoonan juhlapotti on yhä jakamatta.

Noin muuten zip/txt helpottaa pelaamista ainakin allekirjoittaneen systeemeillä tolkuttomasti, hieno juttu.

**Comment by qwerty667** [comment]
Zippeihinkö ei saa lisättyä 0 kpl pelattuja kombinaatioita? On taas jaossa takuupotti ainoalle täysosumalle ja haen pelaamattomia rivejä nyt sitten Excelillä niin, että minulla 16 ydintä ja teillä serveri huutaa hoosiannaa.

**Comment by tpokki** [comment]
Hei, 
Esimerkiksi nyt avoinna olevassa supermonivedossa on n. 43 miljoonaa kombinaatiota, ja tällä hetkellä kohteen zip tiedostossa on 38000 riviä. Pelaamattomia rivejä ei olla näillä näkymin lisäämässä tiedostoihin, ja rivien puuttuminen tiedostosta pitäisi olla riittävä tieto sille ettei riviä ole pelattu.

**Comment by qwerty667** [comment]
Ok. Omat kommenttini tässä ketjussa liittyivät vain vakioon, jossa zip sisältää yleensä kai suuruusluokkaa puolet 1,6 miljoonasta kombinaatiosta.

Robot.xlsm ja "spekuloi"-toiminto näyttää myös pelaamattomat rivit, toivottavasti jatkossakin.
