### ISSUE TITLE
Hakujen katkeilu kesken

### ISSUE THREAD

**Issue by qwerty667** [VeikkausOy/sport-games-robot#121]
Vakiorivien voitto-osuustietojen hakeminen tiedostolla Robot.xlsm muutaman viime viikon hankalaa/mahdotonta. Haut kaatuilevat jatkuvasti puolitiessä yhteysvirheisiin taulukon ilmoittaessa HTTP error 503. Tyypillinen hakuni koko on 19 863 riviä. Se palauttaa yleensä muutamia tuhansia rivejä ennen erroria.

Kyseinen error ei ole entuudestaan täysin tuntematon. Ennen niitä tuli arviolta yksi vartissa, mutta nykyisin luokkaa muutama minuutissa painottuen ryppäisiin.

Mistähän päästä ongelmaa pitäisi etsiä? Omassa päässäni tiedosto, rauta ja softat ovat ennallaan mahdollisia Windowsin päivityksiä lukuun ottamatta. Ongelma on on identtinen kahdella eri nettiyhteydellä testattuna.

**Comment by tmansner** [comment]
Hei!

Kiitos ilmoituksesta, tuo 500 virhe yleensä tulee palvelimen puolelta, tutkimme asiaa.

**Comment by tmansner** [comment]
Palvelun pitäisi nyt toimia normaalisti.
