### ISSUE TITLE
Pelaaminen pätkinyt pari päivää - DRAW NOT PLAYABLE

### ISSUE THREAD

**Issue by 10Andy10** [VeikkausOy/sport-games-robot#122]
Pelaaminen on nyt pätkinyt parin viimeisen päivän ajan. Virheilmoitus DRAW NOT PLAYABLE. Välillä REVISION ERROR tai REJECTED. Koskee ainakin Vakiota ja Monivetoa ja useita käyttäjiä. Yleensä n. 0-100 kuponkia menee kerralla sisään. Esim nyt 19.6. klo 12:27 - 12:39 12 kpl pelaamisyrityksiä joista 8 kertaa ei antanut pelata yhtään riviä, muut kerrat antoi pelata 100, 125, 100, 75 kun yritetty useita satoja rivejä pelata. Virheilmoitus DRAW NOT PLAYABLE.

**Comment by 10Andy10** [comment]
17.6. alkoi ensin tulemaan REVISION ERRORia ja 18.6. lähinnä DRAW NOT PLAYABLE.

**Comment by tmansner** [comment]
Hei!

Kiitos ilmoituksesta, asiaa tutkitaan

**Comment by tmansner** [comment]
Korjaavia toimenpiteitä tehty ja virheitä ei pitäisi enää tulla.
