### ISSUE TITLE
Muutospyyntö pitkävedon listaukseen ja vedon lähettämiseen

### ISSUE THREAD

**Issue by Coronatu5** [VeikkausOy/sport-games-robot#123]
Hei, 
Olisiko mahdollista lisätä rajapintaan mahdollisuus noutaa pitkävetokohteen alakohteet/alakohde, esimerkiksi suoraan kohdenumerolla?
Tällä hetkellä listauksessa palautuu vain pitkävetokohteiden 1X2 kohteet. Samalla mahdollistettaisiin kaikkien pitkävetokohteiden pelaaminen.

**Comment by Coronatu5** [comment]
Kaikkia pitkävedon kohteita ei tarvitsisi /api/v1/sport-games/draws resurssilla palauttaa, vaan alakohteet voisi palauttaa vain jos kohde on yksilöity tarkasti Id:llä. Ja vaihtoehtoisesti esim yksittäisen yli/alle 2,5 maalia kohteen voisi hakea kohdenumerolla.

**Comment by pielaveti** [comment]
>Tällä hetkellä listauksessa palautuu vain pitkävetokohteiden 1X2 kohteet. 
>Samalla mahdollistettaisiin kaikkien pitkävetokohteiden pelaaminen.

Tähän samaan törmäsin myös. Eli olisi kiva saada myös ne alikohteiden tiedot.

**Comment by tpokki** [comment]
Moi, täältä löytyy infoa:

#22
#39

**Comment by pielaveti** [comment]
Kiitos - sain toimimaan!
