### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#126]
![image](https://user-images.githubusercontent.com/22799660/98267688-5238b100-1f94-11eb-8b58-becf5ec316d7.png)

Kaikki automaattisen pelaamisen sovellukseni lakkasivat toimimasta antaen yllä näkyvän virheen.

Mitkään SSL versions arvot eivät näytä toimivan, aiemmin nämä toimivat

![image](https://user-images.githubusercontent.com/22799660/98268607-6630e280-1f95-11eb-971f-2c6aa3c9ca0e.png)

Onko palvelimella tehty jotain muutoksia ?

**Comment by Ylikerroin** [comment]
Onko tulkittava niin, ettei kenelläkään ole vastaavaa ongelmaa vai onko niin ettei näitä täällä ole kellään tietoa?

Virheen perusteella oletin, että palvelimelle olisi tehty muutoksia ja asia olisi korjaantunut näillä asetuksilla, mutta ei
![image](https://user-images.githubusercontent.com/22799660/99915505-c69d7f00-2d0c-11eb-9632-55d8bd5d76ba.png)

**Comment by ceel** [comment]
Minimi SSL/TLS-vaatimustaso on TLS v1.2 eli oletettavasti tuo alin noista. Tuon ajankohdan lähiseudulla on päivitetty tarjolla olevia ciphereitä tiukemmiksi ja mm. elliptisiin käyriin pohjautumattomat on pudotettu pois. Tämä voisi olla yksi potentiaalinen selitys, jonka pitäisi ratketa päivittämällä sovellukset/kirjastot.

**Comment by Ylikerroin** [comment]
Käytän c++builderia. virheilmoitus tulee jo siinä vaiheessa, kun koitan
luoda yhteyttä palvelimelle.  En siis käytä esimerkki sovellusta ollenkaan,
ainoastaan header tietoja jne.

t. Pauli H

ti 24. marrask. 2020 klo 9.17 Juha Paananen <notifications@github.com>
kirjoitti:

**Comment by ceel** [comment]
Joo, TLS-kättely suoritetaan ennen itse kommunikaation aloitusta. En tunne C++ builderia, mutta sen tai sen käyttämän ssl-kirjaston päivityksesta/asetuksista voisi löytyä apua. Tarjotut cipherit löytyy täältä policy versiosta TLSv1.2_2018: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html#secure-connections-supported-ciphers

**Comment by Ylikerroin** [comment]
Lisäsin Cipherlistaan (TLSv1.2_2018):

TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-SHA384:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256

![image](https://user-images.githubusercontent.com/22799660/100485502-ff709600-3108-11eb-8264-96870b30334c.png)

Jostain syystä ohjelma onnistuu muodostamaan yhteyden kerran, mutta kun suljen ja käynnistän uudelleen se ei enää toimikaan.
Ilmeisesti ongelma ei olekaan Ciphereissä, mitä ne sitten ovatkaan.
