### ISSUE TITLE
HTTP ERROR 503

### ISSUE THREAD

**Issue by qwerty667** [VeikkausOy/sport-games-robot#128]
https://github.com/VeikkausOy/sport-games-robot/issues/121

Tänään on taas sama tilanne kuin linkissä kuvatussa keississä. Ei tule vakion tekemisestä mitään.

**Comment by qwerty667** [comment]
Tilanne on edelleen sama. Tehkää sama jippo kuin viimeksi.

**Comment by tmansner** [comment]
Hei, pahoittelut että on ollut vikaa, tutkitaan ja korjataan.

**Comment by tmansner** [comment]
Nyt pitäisi toimia paremmin
