### ISSUE TITLE
Tulosvedon lopulliset kertoimet

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#13]
ONko jokin vakioaika / viive jonka jälkeen tulosvedon lopulliset kertoimet julkaistaan? Jos esim. haen ne 10 min ottelun alettua, onko varmaa että nämä ovat lopulliset? Vai onko itse vastauskessa jokin lippu joka kertoo siitä että kyseessä on lopulliset kertoimet?

**Comment by tpokki** [comment]
Moi,
Rajapinta ei tarjoa yksiselitteisesti lopullisia kertoimia. Mutta tosiaan jos haet kertoimet vaikka noin 15 minuuttia kohteen sulkeutumisen jälkeen, on ne melko todennäköisesti lopulliset.
