### ISSUE TITLE
API muutokset, 

### ISSUE THREAD

**Issue by Swamplander** [VeikkausOy/sport-games-robot#132]
Hei, 
teen vakiorivit Visual basicilla, niin nyt kun implementoin API rajapinnan muutoksia, niin Vakion ottelutietoja hakiessani näyttäisi kun json data tulisi pakattuna takaisin.  Kuitenkin suoralla linkillä selaimessa kaiuttaa stringinä datan ok (selain osaa ilmeisesti purkaa ok). Aiemmalla URLilla data tuli tekstinä ulos ongelmitta.

Pitääkö Headeriin lisätä jotain uusia parametreja? 

Nämä käytössä nyt:
        webReq.Method = method
        webReq.ContentType = "application/json"
        webReq.Accept = "application/json; charset=utf-8"
        webReq.Headers.Add("X-ESA-API-Key", "ROBOT")
        webReq.CookieContainer = cookies

Tältä mössöltä näyttää nyt:
![console_log](https://user-images.githubusercontent.com/32812180/109306074-4c1e5700-7847-11eb-9f68-6b330effe0ef.JPG)

**Comment by tpokki** [comment]
Hei,
Data näyttää tosiaan pakatulta. Kuten tuolla [ohjeessa](https://github.com/VeikkausOy/sport-games-robot#datan-pakkaus) mainitaan, niin vastaukset voivat hyvinkin tulla pakattuina. Suositeltavaa olisi että ohjelmat osaisivat purkaa pakkauksen tarvittaessa ([`Content-Encoding`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding) otsakkeen perusteella).

Tarvittaessa voit määritellä [`Accept-Encoding`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding)  otsakkeen pyynnölle, ja kertoa tukemasi enkoodaus algoritmit. 

```
Accept-Encoding: identity
```
... otsakkeella saanet vastauksen ilman pakkausta.

**Comment by Swamplander** [comment]
Jees, sain ratkaistua tämän. Visual basicilla (Visual studio 2017) asian pystyy ratkaisemaan lisäämällä headeriin seuraavan: 
webReq.AutomaticDecompression = DecompressionMethods.GZip
