### ISSUE TITLE
useampia rivejä samassa pyynnössä uudella rajapinnalla?

### ISSUE THREAD

**Issue by eikka71** [VeikkausOy/sport-games-robot#133]
Miten lähetetään useampia rivejä samassa pyynnössä uudella rajapinnalla? UKK:n mukaan edelleen voi lähettää max 25 pyyntöä samassa pyynnössä mutta missä formaatissa se tulisi nykyään lähettää. Esimerkkiä ei löydy ja seuraava pyyntö (moniveto) ei ainakaan toimi. Ainoastaan ensimmäinen tuosta menee läpi. Olen testaillut erilaisia kombinaatioita miten niitä voisi yhdessä lähettää ilman menestystä. Eli onko tuo nykyään ylipäätään mahdollista ja jos on niin miten?

{"listIndex": "1","gameName": "MULTISCORE","price": 10,"boards":[{"betType": "FULL 2","stake": 5,"selections":[{"homeScores": [2],"awayScores": [2]},{"homeScores": [4],"awayScores": [1]},{"homeScores": [2],"awayScores": [2]},{"homeScores": [1,3],"awayScores": [1]}]}]},{"listIndex": "1","gameName": "MULTISCORE","price": 5,"boards":[{"betType": "FULL 1","stake": 5,"selections":[{"homeScores": [2],"awayScores": [2]},{"homeScores": [4],"awayScores": [1]},{"homeScores": [1],"awayScores": [1]},{"homeScores": [2],"awayScores": [2]}]}]},{"listIndex": "1","gameName": "MULTISCORE","price": 5,"boards":[{"betType": "FULL 1","stake": 5,"selections":[{"homeScores": [2],"awayScores": [2]},{"homeScores": [4],"awayScores": [1]},{"homeScores": [2],"awayScores": [2]},{"homeScores": [2],"awayScores": [2]}]}]},{"listIndex": "1","gameName": "MULTISCORE","price": 5,"boards":[{"betType": "FULL 1","stake": 5,"selections":[{"homeScores": [2],"awayScores": [2]},{"homeScores": [4],"awayScores": [1]},{"homeScores": [3],"awayScores": [3]},{"homeScores": [2],"awayScores": [2]}]}]}

**Comment by tpokki** [comment]
Hei,

Useamman pyynnön lähetyksen tapauksessa pyyntö on `POST /api/sport-interactive-wager/v1/tickets/set`. Tämä API hyväksyy 2-25 pelitapahtumaa kerralla. Päivitämme tämän tiedon myös tuonne ohjeeseen.

**Comment by eikka71** [comment]
Kiitos tästä. Myös sportId-arvojen listaus olisi kiva. Esim monivedon kohdetiedot ei kerro mikä laji on kyseessä muuten kuin noilla SportId-arvoilla joten nyt pystyy päivittämään vain ne joita on jo löytynyt listoilta. Toki ne saisi varmaan kaivettua esim pitkävedon puolelta mutta silti listaus olisi hyvä olla.

**Comment by tpokki** [comment]
`/check` toiminnallisuus ei ole mahdollista useammalle riville kerralla.

**Comment by tpokki** [comment]
Lajikoodit löytyvät täältä: https://www.veikkaus.fi/api/sport-codes/v1/fi/sports
```
curl --compressed https://www.veikkaus.fi/api/sport-codes/v1/fi/sports
```

**Comment by eikka71** [comment]
Hei,
kertoisitko vielä miten nuo useammat rivit yhdessä pyynnössä tulee ryhmitellä? Ei ainakaan onnistu tuolla esimerkkini rivijonolla tuonne mainitsemaasi rajapinnan osoitteeseen. Ei jaksaisi kokeilla taas vaikka mitä vaihtoehtoja kun tieto voisi olla valmiinakin. Voisitteko julkaista kaikki muutokset esimerkin kera niin ei tarvitsisi ihmetellä ja arvailla`. Pitääkö olla hakasulut alussa/lopussa tms muita kikkailuja noiden useamman lähettämiseen. Pelkkä pilkulla eroittelu ei ainakaan näytä toimivan

**Comment by tpokki** [comment]
@eikka71, tiedoksi:

https://github.com/VeikkausOy/sport-games-robot/pull/153
