### ISSUE TITLE
API-muutosten vaikutus Pitkävetoon ja pelattujen vetojen hakemiseen

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#134]
Hei!

Vaikuttaako nykyiset API-muutokset (ns. "OmniAPI update") Pitkävedon pelaamiseen tai sen tietojen hakemiseen mitenkään? Web-sivulla siihen on ilmestynyt hiljattain GraphQL-rajapinta, mutta sille ei ole käyttöohjetta vielä? Toimiiko kuitenkin vanha REST-rajapinta Pitkävetoon vielä 15.3. jälkeenkin?

Toinen kysymys koskee pelattujen vetojen hakemista. Onko siihen nyt tulossa muutoksia? Edes tietorakennetasolla? Siellä on mm. Wager-rakenteella selections/outcomes, joka on erilainen kuin uuden OmniAPI:n tietojen haussa käytettävä selections/outcomes-rakenne. Aiemmin on voinut käyttää samaa tietorakennetta sekä pelattavien pelien tietojen haussa että pelattujen vetojen tietojen haussa, mutta nyt pitänee erottaa rakenteet toisistaan, koska API:tkin eroavat toisistaan ainakin tältä osin.

**Comment by tpokki** [comment]
Hei, 
API muutokset koskevat myös pitkävetoa. Ja vanha rajapinta lakkaa toimimasta myös tältä osin. 

Avoimet pitkävedon kohteet voi hakea seuraavasti:
```
GET /api/sport-open-games/v1/games/ebet/draws
GET /api/sport-open-games/v1/games/ebet/draws/by-event/{event-id}
```

Pelattujen pelien rajapinta on myös muuttunut, uusi rajapinta on: 
```
GET /api/sport-wager-details/v1/tickets/{serial}
```
Tämän rajapinnan pitäisi olla yhtenäinen `/api/sport-interactive-wager/v1/tickets` kanssa.

**Comment by umeetiusbaar** [comment]
Onko `/api/sport-interactive-wager/v1/tickets` rajapintaa dokumentoitu vielä jossain? Voiko pyynnölle antaa parametreja kuten aikaa tai sivua tai muita vastaavia, mitä on ollut vanhassa transaktioidenhakurajapinnassa?

**Comment by umeetiusbaar** [comment]
Onko tuossa `/api/sport-wager-details/v1/tickets/{serial}` mitään yleisempää tapaa hakea useita vetoja kerralla ilman tietyn vedon `serial`-tunnistetta? Kuten ajan perusteella tai tietyn pelin (vakio, moniveto tms.) perusteella?

**Comment by tpokki** [comment]
Tuo `/api/sport-wager-details/v1/tickets/{serial}` on uusi rajapinta pelitapahtuman merkki- ja voittotietojen hakemiseen. Tilitpahtumien hakuun tarkoitettu rajapinta pysyy toistaiseksi ennallaan.
