### ISSUE TITLE
API-muutokset: events

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#135]
Onko jossain uudessa rajapinnassa saatavilla esim. kaikki Pitkävedon tai Monivedon tai Vakion Eventit kaikkine tietoineen (esim. sport, category, tournament yms)? Vanhassa rajapinnassa tiedot löytyivät esimerkiksi osoitteen `/api/v1/sports/events?lang=fi&event-ids=1234567,2345678,3456789&game-names=SPORT` takaa.

**Comment by tpokki** [comment]
Hei,

Näillä toivottavasti pärjää:
```
GET /api/sport-codes/v1/fi/events/by-day/{yyyy-mm-dd}
GET /api/sport-codes/v1/fi/events/{event-id}
GET /api/sport-codes/v1/fi/games/{game}/draws/{draw-id}/events
```

Esimerkit:
https://www.veikkaus.fi/api/sport-codes/v1/fi/events/by-day/2021-03-02
https://www.veikkaus.fi/api/sport-codes/v1/fi/events/99508502
https://www.veikkaus.fi/api/sport-codes/v1/fi/games/SPORT/draws/100283/events

**Comment by mackepee** [comment]
Kiitos! Yksi täydentävä kysymys koskien tulosta kohteen jo ratkettua. Vanhaan tapaan 

/api/v1/sport-games/draws/{game}/{draw-id}

tuotti vahvistetut lopputulostiedot.

(Esim. https://www.veikkaus.fi/api/v1/sport-games/draws/SCORE/121073)

Onko tuo rajapinta muuttumassa uuden pelijärjestelmän myötä?

**Comment by tpokki-igt** [comment]
Hei,
Tulokset löytyvät jatkossa täältä: 
```
GET /api/sport-results/v1/games/{game-name}/draws/{draw-id}
```

Esim: https://www.veikkaus.fi/api/sport-results/v1/games/SCORE/draws/121073

**Comment by tpokki** [comment]
Hei,
Tulokset löytyvät jatkossa täältä: 
```
GET /api/sport-results/v1/games/{game-name}/draws/{draw-id}
```

Esim: https://www.veikkaus.fi/api/sport-results/v1/games/SCORE/draws/121073

**Comment by mackepee** [comment]
Lämmin kiitos!

**Comment by tpokki** [comment]
@simoheinonen, ei - vain yksi päivä kerrallaan.
