### ISSUE TITLE
Useamman kohteen hakeminen yhdellä API-pyynnöllä

### ISSUE THREAD

**Issue by pasi555** [VeikkausOy/sport-games-robot#138]
Vanhassa API:ssa pystyi hakemaan useita kohteita yhdellä pyynnöllä seuraavasti:

/api/v1/sport-games/draws?game-names=EBET&event-ids=xxx,yyy,zzz

Onnistuuko vastaava uudella API:lla, vai joutuuko jokaisen kohteen hakemaan erikseen?

/api/sport-open-games/v1/games/ebet/draws/by-event/{event-id}

Kysyn asiaa, koska vanhan API:n kautta hakeminen toimii huomattavasti nopeammin verrattuna erillisiin API-pyyntöihin.

**Comment by tmansner** [comment]
Hei!

Uudessa APIssa ei ole mahdollista hakea kohteita kuin yhdellä event id:lla kerrallaan.
