### ISSUE TITLE
API-muutokset 2021: listIndex ja eventId

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#139]
Hei,

jossain esimerkeissä on `listIndex` esitetty merkkijonona (esim. https://www.veikkaus.fi/api/sport-open-games/v1/games/SPORT/draws) ja toisaalla taas numerona (esim. sport-interactive-wager pyynnöt eli pelien pelaamiset). 
Voisiko tätä yhtenäistää vai toimiiko, jos käyttää aina vaikka numerona clientissa? 

Sama koskee `eventId`-attribuuttia joka on toisaalla merkkijono (esim. https://www.veikkaus.fi/api/sport-open-games/v1/games/SPORT/draws) ja toisaalla numero (https://www.veikkaus.fi/api/sport-codes/v1/fi/events/by-day/2021-03-09 pelkkä `id` tässä).

**Comment by umeetiusbaar** [comment]
Sama koskee muitakin tunneisteita: `sportId`, draw:n `id` (https://www.veikkaus.fi/api/sport-open-games/v1/games/EBET/draws/by-event/99391705 vs https://www.veikkaus.fi/api/sport-open-games/v1/games/SPORT/draws). 
`externallId` taitaa olla yhtenäisesti merkkijono joka paikassa.

**Comment by tpokki** [comment]
Joitakin epäyhtenäisyyksiä tosiaan löytyy noiden mainittujen kenttien kohdalla. Välitämme tiedon eteenpäin ja toivotaan että rajapintaa saadaan yhtenäistettyä jatkokehityksen yhteydessä.
