### ISSUE TITLE
Type of sport when EventId is missing

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#14]
I noticed that the eventId field seem to be missing often, example:

>[gameRuleSet:[maxSelections:10, maxStake:10000, quickPickAvailable:true, oddsType:VARIABLE, maxPrice:300000, minStake:100], id:85832, drawTime:1433365200000, closeTime:1433372100000, resultsAvailableTime:1433365200000, status:OPEN, openTime:1433314800000, gameName:SCORE, brandName:11, rows:[[id:0, score:[min:0, max:15], outcome:[away:[name:Grand Rapids], home:[name:Utica]]]]]

How can i determine the sport (hockey, soccer...), if I cannot query additional information?

Also, I thought this was a mandatory field because the docs refer to using it:

> Pelikohteen tiedoista löytyy tyypillisesti eventId-kenttä, jolla on numeerinen arvo. Tällä tunnisteella voidaan hakea urheilutapahtuman tiedot, josta näkee mm. urheilulajin nimen sportName-kentässä.

If this is a bug in your system, when will it be fixed?

**Comment by tpokki** [comment]
The field itself is not mandatory, but should be quite common. Unfortunately the sport information is not available without it. We'll need to check this specific case, if the event information should had been there.

**Comment by johan313** [comment]
That is very strange. One would think the field mandatory for Tulosveto. After all, knowing the sport is pivotal for any betting.

**Comment by tpokki** [comment]
Yes, the eventId should be there nearly always, and thus should probably had to be there in this case also. Please add comment here if you see this happen again (so far I've not been able to witness this myself).
