### ISSUE TITLE
SPORT winShares - uusi vs. wanha

### ISSUE THREAD

**Issue by mackepee** [VeikkausOy/sport-games-robot#140]
Yritin täsmäyttää keskiviikon vakion (SPORT 54348) voitto-osuuksia uuden ja wanhan rajapinnan hakujen välillä. En saa täsmäämään niitä, joten kysytään viisaammilta mikä minulla on pielessä. Seuraavassa on asian yksinkertaistamiseksi pelkkä minivakion 7 oikein tuloksen voitto-osuuden ja kappalemäärän haku.

Ensin wanhaan tapaan haettuna kaikki näyttää hyvältä:

curl -X POST https://www.veikkaus.fi/api/v1/sport-games/draws/SPORT/54348/winshares -H "Content-Type: application/json" -H "Accept: application/json" -H "Accept-Encoding: gzip, deflate" -H "X-ESA-API-Key: ROBOT" -d "{ \"page\": 0, \"additionalPrizeTier\": true, \"selections\": [{ \"systemBetType\": \"NORMAL\", \"outcomes\": [{ \"home\": { \"selected\": true } },{ \"home\": { \"selected\": true } },{ \"tie\": { \"selected\": true } },{ \"home\": { \"selected\": true } },{ \"away\": { \"selected\": true } },{ \"tie\": { \"selected\": true } },{ \"home\": { \"selected\": true } } ] } ] }"

=> "numberOfBets": 271 [OIKEIN]

OUTPUT:
{
    "winShares": [{
        "value": 2175,
        "numberOfBets": 271,
        "selections": [{
            "outcomes": [{
                "home": {
                    "selected": true
                }
            }, {
                "home": {
                    "selected": true
                }
            }, {
                "tie": {
                    "selected": true
                }
            }, {
                "home": {
                    "selected": true
                }
            }, {
                "away": {
                    "selected": true
                }
            }, {
                "tie": {
                    "selected": true
                }
            }, {
                "home": {
                    "selected": true
                }
            }]
        }]
    }],
    "suppoTimestamp": 1615395597000,
    "exchange": 935720,
    "totalResults": 1,
    "hasNext": false
}}

****************
Sitten vaihto uuteen tapaan ja jossain nyt näyttää menevän pieleen:

curl -X POST https://www.veikkaus.fi/api/sport-winshare/v1/games/SPORT/draws/54348/winshare -H "Content-Type: application/json" -H "Accept: application/json" -H "Accept-Encoding: gzip, deflate" -H "X-ESA-API-Key: ROBOT" -d "{ \"page\": 0, \"pageSize\": 100, \"additionalPrizeTier\": true, \"selections\": [ { \"outcomes\":[\"1\"] }, { \"outcomes\":[\"1\"] }, { \"outcomes\":[\"X\"] }, { \"outcomes\":[\"1\"] }, { \"outcomes\":[\"2\"] }, { \"outcomes\":[\"X\"] }, { \"outcomes\":[\"1\"] } ] }"

=> "numberOfBets": 1  [VÄÄRIN]

OUTPUT:
{
    "timestamp": 1615477229938,
    "exchange": 935720,
    "totalResults": 1,
    "winShares": [{
        "selections": [{
            "outcomes": ["1"]
        }, {
            "outcomes": ["1"]
        }, {
            "outcomes": ["X"]
        }, {
            "outcomes": ["1"]
        }, {
            "outcomes": ["2"]
        }, {
            "outcomes": ["X"]
        }, {
            "outcomes": ["1"]
        }],
        "value": 589503,
        "numberOfBets": 1
    }]
}

****************
Samat eroavaisuudet kohtaan myös varsinaisen vakiopelin osalta. Pelin vaihto pysyy samana, mutta kappaleet ja eurot eivät kohtaa wanhan ja uuden välillä. Saanko apua, KIITOS!

**Comment by tpokki-igt** [comment]
Hei, uusi rajapinta toimii toistaiseksi vain avoimille kohteille. Suljetuille kohteille palautetaan vain vaihto (ja pyydetty rivi). 
Tuohon on tulossa muutos jolla uuden rajapinnan kautta voi hakea myös suljettujen kohteiden tietoja muutaman päivän ajan. Valitettavasti minulla ei ole antaa tarkempaa aikataulua muutokselle. 

Toistaiseksi suosittelen ottamaan zip tiedoston talteen esimerkiksi 15 minuuttia kohteen sulkeutumisen jälkeen.

**Comment by tpokki** [comment]
Hei, uusi rajapinta toimii toistaiseksi vain avoimille kohteille. Suljetuille kohteille palautetaan vain vaihto (ja pyydetty rivi).
Tuohon on tulossa muutos jolla uuden rajapinnan kautta voi hakea myös suljettujen kohteiden tietoja muutaman päivän ajan. Valitettavasti minulla ei ole antaa tarkempaa aikataulua muutokselle.

Toistaiseksi suosittelen ottamaan zip tiedoston talteen esimerkiksi 15 minuuttia kohteen sulkeutumisen jälkeen.

**Comment by mackepee** [comment]
Morjens! Kiitos vastauksesta! Vaikuttaa kuitenkin siltä että vertailu uuden ja wanhan välillä on yhtenevä vaikkapa eilisten (jo suljettujen) vakioiden kohdalla. Poikkeuksen toimivuuteen muodosti juuri tuo alussa esitelty SPORT-54348. Mutta, kun muutostyöt on vielä vaiheessa niin ei tästä sen enempää.

Kiitos!
