### ISSUE TITLE
API-muutokset 2021: Pitkävedon tulokset

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#142]
Hei,

kuinka haetaan sulkeutuneiden Pitkävetokohteiden tietoja? Esim. Vakiolle toimii tämä:
```
/api/sport-results/v1/games/SPORT/draws/100283
```
esim. https://www.veikkaus.fi/api/sport-results/v1/games/SPORT/draws/100283

Mutta Pitkävedolle vastaava kysely
```
/api/sport-results/v1/games/EBET/draws/2425549
```
esim. https://www.veikkaus.fi/api/sport-results/v1/games/EBET/draws/2425549
Antaa vastaukseksi:
```
{"code":"BAD_REQUEST","fieldErrors":[{"code":"INVALID_VALUE","field":"game-name"}]}
```
Onko jokin toinen endpoint, mistä pitkävedon sulkeutuneiden kohteiden tietoja voi hakea?

**Comment by umeetiusbaar** [comment]
Tai toimiiko tämä nykyinen endpoint myös jatkossa?
```
/api/hdr/v2/sport-games/draws?game-names=EBET&date-from=<timestamp>&date-to=<timestamp>&event-ids=<eventId1, eventId2, ...>
```

**Comment by tmansner** [comment]
Hei,

löydät pitkävedon sulkeutuneet kohteet "ebet-results" rajapinnan kautta:

`https://www.veikkaus.fi/api/ebet-results/v1/games/EBET/draws/2425549`

Nykyiset rajapinnat mm. tuo "sport-games" sulkeutuvat aikanaan.

**Comment by umeetiusbaar** [comment]
Pystyykö pelkällä eventId:llä hakemaan sulkeutuneita Pitkävetokohteita? Edes niin, että hakee em. ebet-results:sta massana, jos mahdollista, ja suodattaa niistä eventId:n perusteella haluamansa?

**Comment by tpokki** [comment]
Hei, 
```
GET /api/ebet-results/v1/games/EBET/draws/by-day/{yyyy-mm-dd}/by-event/{event-id}
```
esim. https://www.veikkaus.fi/api/ebet-results/v1/games/EBET/draws/by-day/2021-03-15/by-event/99319469
