### ISSUE TITLE
API-muutokset 2021

### ISSUE THREAD

**Issue by Lennart580** [VeikkausOy/sport-games-robot#143]
Hei, saisiko yksinkertaisen mallisanoman single-pitkävedosta? En saanut toimivaa aikaiseksi omin päin. Listan sain putoamaan hienosti, mutta mielelläni pelaisin Veikkauksen rajapinnan kautta. Käsin pelaaminen saattaisi houkuttaa pelaamaan kilpailijoille...

**Comment by tpokki** [comment]
```
{
    "price": 100,
    "gameName": "EBET",
    "boards": [
        {
            "stake": 100,
            "betType": "NORMAL",
            "selections": [
                {
                    "listIndex": 11,
                    "competitors": [1]
                }
            ]
        }
    ]
}
```

**Comment by Lennart580** [comment]
Kiitos, toimii! Pääsen taas pumppaamaan rahaa urheilulle, tieteelle ja kulttuurille:)
