### ISSUE TITLE
API-muutokset tapahtuman nimi

### ISSUE THREAD

**Issue by aschumac** [VeikkausOy/sport-games-robot#144]
Miten uudessa apissa saadaan liigan/tapahtuman nimi selville? https://www.veikkaus.fi/api/sport-open-games/v1/games/EBET/draws näyttää vaan joukkueiden/pelaajien nimet. Tuleeko ne vielä lisäyksenä myöhemmin tuohon päälistaan?

**Comment by mackepee** [comment]
Tapahtumatiedoista oli (closed issue #135) listattu events -rajapinnat:

/api/sport-codes/v1/fi/events/by-day/{yyyy-mm-dd}
/api/sport-codes/v1/fi/events/{event-id}
/api/sport-codes/v1/fi/games/{game}/draws/{draw-id}/events

esimerkit:

https://www.veikkaus.fi/api/sport-codes/v1/fi/events/by-day/2021-03-18
https://www.veikkaus.fi/api/sport-codes/v1/fi/events/99446617
https://www.veikkaus.fi/api/sport-codes/v1/fi/games/SPORT/draws/100285/events
