### ISSUE TITLE
Moniveto -zipit eivät sisällä kaikkia mahdollisia tulosyhdistelmiä

### ISSUE THREAD

**Issue by odexi** [VeikkausOy/sport-games-robot#145]
Tämä ei sinänsä ole issue, mutta haluaisin tietää tarkemmin, mitkä yhdistelmät päätyvät zip-tiedostoon. Esimerkiksi tämän hetkisessä moniveto 9 -tiedostossa (id 60264) on 0-kertoimisia (lienevät ei pelattu -rivejä?) vain murto-osa kaikista tulosyhdistelmistä. Olen päätellyt, että pelaamattomat rivit eivät päädy tiedostoon joitain poikkeuksia lukuunottamatta. Voisitteko avata, mitkä ei-pelatut rivit päätyvät tiedostoon? Haluaisin myös tietää, kuinka usein tiedostoja päivitetään.

Kiitos mainiosta rajapinnasta!

**Comment by tpokki** [comment]
Hei, tiedostot päivittyvät 10 minuutin välein, ja tosiaan pääsääntöisesti ne eivät sisällä pelaamattomia yhdistelmiä. Sekä yhdistelmät joilla on tiedostossa kerroin nolla ja ne jotka puuttuvat kokonaan, ovat kummatkin samalla lailla ei-pelattuja yhdistelmiä.

**Comment by mackepee** [comment]
Veikkaus ei näytä olevan halukas kertomaan mitä nuo muutamat nolla-kertoimiset kombot niin vakion kuin monivedonkin zip-paketeissa on. Henkilökohtainen teoriani on että monivedossa kyse on säästöjärjestelmissä poistetuista komboista ja vakiossa haravakaavioissa pois pudonneista riveistä. Rivi on siis näennäisesti pelilapulla mutta se on säästösyistä ruksittu pois (ei kotivoittoja/ei tasapelejä/ei vierasvoittoja) maksettavista riveistä, jolloin se ajautuu zip-pakettiin vaikka sitä ei olisi pelattukaan. Mikäli kukaan muukaan ei pudokasta pelaa, niin se roikkuu nolla-kertoimisena muiden oikeasti pelattujen listalla vielä peliajan päättymisen jälkeenkin.

Ehkäpä tämä väite kannustaa Veikkausta kertomaan mikä on totuus sikäli kun teoriani on väärä. 😎
