### ISSUE TITLE
Vakion voitto-osuuksien haku antaa 404

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#146]
Esim. huomisen tiistain 23.3.2021 Vakio 4: 
POST https://www.veikkaus.fi/api/sport-winshares/v1/games/SPORT/draws/54367/winshares
Silmiini ei nyt osu, että tuossa polussa olisi jotain vialla. Dokkarissa kerrotaan tällainen muoto osoitteelle:
```
POST /api/sport-winshares/v1/games/SPORT/draws/{drawId}/winshares
```
Mutta kysely antaa kuitenkin tulokseksi 404 NOT FOUND.

**Comment by mackepee** [comment]
Veikkauksella on omissa ohjeissaan virhe, koska eihän se nyt niin tarkkaa ole rajapintojen kanssa 😉 

Käytä urlissa "ässätöntä" versiota, eli  

https://www.veikkaus.fi/api/sport-winshare/v1/games/SPORT/draws/54367/winshare

**Comment by umeetiusbaar** [comment]
Kiitos!

**Comment by mackepee** [comment]
Moro! En haluaisi nipottaa pienistä, mutta kun huomasin että korjasitte ohjetta niin suosittelen korjaamaan sen ihan aikuisten oikeesti toimivaksi eli sport-winshare -urlissa on ohjeessanne edelleen yksi ässä liikaa. Just se viimeinen kirjain.
