### ISSUE TITLE
Vetojen serialNumber lyhenee matkalla

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#149]
Hei,

kun pelaa vedon, niin paluusanomassa on serialNumber, joka ainakin Pitkävedoilla on muotoa:
```
1111-222222222-333333
```
Kun myöhemmin hakee pelattuja transaktioita, niin niillä `externalId` on  vielä tuo sama merkkijono. 
Mutta kun sillä hakee itse vedon, niin sen mukana tulevassa tietorakenteessa tuo serialNumber on kuitenkin muotoa
```
1111-222222222-33
```
Miksi lopusta putoaa neljä merkkiä pois?

**Comment by tpokki** [comment]
Valitettavasti tosiaan viimeiset neljä numeroa puuttuvat esim. pelattujen pelien vastauksesta.  Pelitapahtuman yksilöintiin riittää lyhyempi versio.

Välitän tiedon eteenpäin ja toivottavasti tuo saadaan yhtenäiseksi tulevissa päivityksissä.

**Comment by tpokki** [comment]
@umeetiusbaar, palvelusta löytyy rajapinta joka palauttaa pitkän version sarjanumerosta.

```
GET /api/sport-wager-details/v2/tickets/{serialNumber}
```

Rajapinta myös hyväksyy argumenttina vain pitkän version.

**Comment by umeetiusbaar** [comment]
Hei @tpokki, olikohan tuossa jokin ajatusvirhe vai onkohan se minulla? Palauttaa pitkän version ja vaatii pitkän version?

Tästä huolimatta niin se ei nyt ole muuttunur, että vetojen haku toimii sekä pitkällä että lyhyellä muodolla?

**Comment by tpokki** [comment]
Hei, 
Olettamus on että lyhyen version käyttö ja tarve poistuu ajan kanssa, eikä sitä pitäisi esiintyä missään rajapinnassa. Näin ollen sitä ei myöskään voi käyttää input-arvona näissä (uusissa) rajapinnoissa. 

Pelatessa saat siis pelitapahtumalle sarjanumeron joka on muotoa `1111-222222222-333333`, ja hakiessasi jälkikäteen pelitapahtuman tietoja tulee sinun käyttää tuota samaa pitkää sarjanumeroa käyttäessäsi `v2` rajapintaa. 

Vanha `v1` rajapinta säilyy muuttumattomana toistaiseksi. Ja tämä rajapinta hyväksyy niin pitkän kuin lyhyen muodon, ja palauttaa aina lyhyen version (pudottaa 4 merkkiä lopusta pois).

**Comment by umeetiusbaar** [comment]
Hei,
onko Pitkävedolle myös olemassa v2-rajapinta, jolle annetaan ja joka palauttaa pitkän serialNumberin? Äkkiseltään testattuna ei tämä ainakaan toimi:
```
/api/ebet-wager-details/v2/tickets/{serialNumber}
```
mutta tämä toimii vaikkakin palauttaa lyhyen serialNumberin, vaikka hakisi pitkällä:
```
/api/ebet-wager-details/v1/tickets/{serialNumber}
```

**Comment by tmansner** [comment]
Hei, 
nyt on myös pitkävedolle v2-rajapinta pitkälle sarjanumerolle tuotannossa, url juuri kuten olet koettanutkin.
