### ISSUE TITLE
api_key_header_missing

### ISSUE THREAD

**Issue by mikkome** [VeikkausOy/sport-games-robot#15]
hei, 

toimi jonkun aikaa ku värkkäsin php:lla. eli esim. selaimeen kun laittaa osoitteen: 
https://www.veikkaus.fi/api/v1/sport-games/draws?game-names=SPORT
niin vastauksena tulee seuraava. 

{"code":"API_KEY_HEADER_MISSING","fieldErrors":[]}

siis jossain kohtaa tämä ongelmitta.

onkohan joku muuttunut vai onko tämä veikkauksen json pois käytöstä vai tartteeko tähän rakentaa kirjautuminen ennekuin kyselyn voi tehdä?

**Comment by tpokki** [comment]
Moi,

API urleja ei voi kirjoittaa suoraan selaimeen johtuen siitä että pyynnöt vaativat tuon X-ESA-API-Key headerin. Eli pyyntö pitää tehdä ohjelmallisesti, php:n tapauksessa esimerkiksi http_get pyynnöllä X-ESA-API-Key header tiedolla (http://php.net/manual/en/function.http-get.php).

PHP:llekin luulisi löytyvän valmiita HTTP-Client toteutuksia, joten suosittelen käyttämään ennemmin sellaista, kuin toteuttamaan session-hallinan itse tyhjästä. 

cURL ohjelmalla tuon pyynnön saa tehtyä esimerkiksi näin:
```
$ curl --compressed -H 'X-ESA-API-Key: ROBOT' https://www.veikkaus.fi/api/v1/sport-games/draws?game-names=SPORT
```

**Comment by mikkome** [comment]
Kiitos paljon avusta, Sain tämän toimimaan vinkilläsi.
