### ISSUE TITLE
T-pelien lähtölistat ja peliprosentit

### ISSUE THREAD

**Issue by Tspel-maker** [VeikkausOy/sport-games-robot#150]
Veikkaus lähetti Toto-pelejä varten linkin, jossa oli
T-peleihin pelatut yhdistelmät on saatavilla ainoastaan XML-muodossa. "cards.xml"-tiedostossa luetellaan kuluvan päivän kohteet sekä niihin liittyvät kerroin- ja yhdistelmätiedostot.
GET /api/toto-info/v1/xml/cards.xml
GET /api/toto-info/v1/xml/{n_ddmmyyyy_Rn_txx}.xml.zip
<URL:n> URL:n
<https://www.veikkaus.fi/api/toto-info/v1/xml/cards.xml> https://www.veikkaus.fi/api/toto-info/v1/xml/cards.xml
avulla voin noutaa avoinna olevat pelit ohjelmaan.
Esimerkiksi noutamalla "T75" löytyy Teivo tiedosto. Ensimmäisellä rivillä on
<card name="TEIVO" code="T" date="27.03.2021" track-code="2" race-type="ravi">
Oletan, että tässä on ne tiedot, jotka tarvitaan lähtölistojen ja prosenttiosuuksien selvittämiseen.
Kuinka teen URL-osoitteen, jotta saan lähtölistat ja prosenttiosuudet?
Oletettavasti on olemassa kaksi eri osoitetta.

Kysyn kuinka saan Veikkauksen sivuilta T-pelien lähtölistat ja peliprosentit kun tiedän Kilpailumuodon esim. T75, radan ja päivämäärän?

**Comment by Tspel-maker** [comment]
Puuttui teksti
Ensimmäisellä rivillä on
" card name="TEIVO" code="T" date="27.03.2021" track-code="2" race-type="ravi" "

**Comment by VeikkausOy** [comment]
Kyseisessä cards.xml -tiedostossa on linkit T-pelien peliprosentit sisältäviin tiedostoihin. 

<img width="639" alt="HFS9" src="https://user-images.githubusercontent.com/9208824/131286865-93861f50-8b75-4f1c-827e-22a19201ab11.png">

Lähtölistat eivät ole saatavilla xml-muodossa, ne löytyvät jsonia palauttavan apin puolelta, esim.

```
GET /api/toto-info/v1/cards/active           # kuluvan ja tulevien päivien tapahtumat  -> cardId
GET /api/toto-info/v1/card/{cardId}/races    # tapahtuman lähdöt -> raceId
GET /api/toto-info/v1/race/{raceId}/runners  # lähdön osallistujat
```
