### ISSUE TITLE
Toto-lähdön aikataulumuutokset

### ISSUE THREAD

**Issue by jounisuom** [VeikkausOy/sport-games-robot#151]
Jos toto-lähtö viivästyy/uusitaan, Veikkauksen pelisivulle päivittyy uusi lähdön sulkeutumisaika, mihin asti vedonlyönti on vielä mahdollista. Tämä lähtöajan muutos ei kuitenkaan näyttäisi olevan saatavilla APIn kautta, onko tosiaan näin?

**Comment by iiromutikainen** [comment]
Nosto tälle, kaipailisin itsekin. Tosiaan lähdön yhteydessä lukee esim. "Lähtöön aikaa 7 min", vaikka lähtö olisi myöhästynyt alkuperäisestä ajasta.

**Comment by tpokki** [comment]
Tuo toto on valitettavasti hieman tuntemattomampi allekirjoittaneelle. @TapaniJamsen ?
