### ISSUE TITLE
Järjestelmä on ruuhkautunut

### ISSUE THREAD

**Issue by 10Andy10** [VeikkausOy/sport-games-robot#152]
Tuleeko muillekin tällaista ilmoitusta ruuhka-aikaan Monivedon ja Vakion rivien pelaamisessa? Esimerkiksi eilen 6.4.2021 Monivedossa klo 17.54 ja 18.04.

"Järjestelmä on ruuhkautunut!
 
Yritä hetken kuluttua uudelleen. Jos tämä ilmoitus tuli pelin hyväksymisen yhteydessä, voi olla mahdollista, että pelisi kuitenkin hyväksyttiin. Voit tarkistaa tämän hakemalla avoimet pelisi. Pelien tulokset voit tarkastaa TekstiTV:n sivulta 470."

[url] => https://www.veikkaus.fi/api/sport-interactive-wager/v1/tickets/set
[content_type] => text/html
[http_code] => 500

**Comment by tmansner** [comment]
Hei!

Kiitos ilmoituksesta, olemme havainneet ongelman ja pyrimme tekemään korjauksen mahdollisimman pian. Pahoittelut vian aiheuttamasta haitasta.

**Comment by tpokki** [comment]
Hei @10Andy10, 
palvelussa on nyt uusi rajapinta useamman pelitapahtuman lähettämiseen.
```
POST /api/sport-interactive-wager-set/v1/tickets/set
```

Erona vanhaan on tuo `-set` lisää API polun toisessa elementissä. Vanha rajapinta (/api/sport-interactive-wager/v1/tickets/set) poistuu käytöstä jossain vaiheessa.
