### ISSUE TITLE
Pitkävedon peliesimerkki?

### ISSUE THREAD

**Issue by anadigifin** [VeikkausOy/sport-games-robot#154]
Vaikka pitkävetoa ei tueta api-kutsuna virallisesti, olisiko mahdollista saada esimerkki, miten uuden apin mukainen (peli)kutsuu tulee tehdä?

**Comment by mackepee** [comment]
Kirjaudu ensin normaalisti tilillesi avaamalla sessio eli LOGIN os.

"https://www.veikkaus.fi/api/bff/v1/sessions"

- - - - - - - - - -

Sitten valitaan pelikohde ja määritetään panos. 
Ollaan hullunrohkeita kuten aina ja pelataan singlenä LIIGAn puolivälierien kolmannessa osaottelussa Ilvekselle kotivoittoa Lukosta 
kohde nro 6362 
panos 100 senttiä
kerroin hetki sitten 5.00. 

Tuosta peli-ideasta muodostuu "ebet-wager-request.json":

{ \"price\": 100, \"gameName\": \"EBET\", \"boards\": [ { \"stake\": 100, \"betType\": \"NORMAL\", \"selections\": [ { \"listIndex\": 6362, \"competitors\": [1] } ] } ] }

ja se POSTataan Veikkauksen UKK-ohjeissa kerrottujen pakollisten headereiden ohella os.

"https://www.veikkaus.fi/api/sport-interactive-wager/v1/tickets"

- - - - - - - - - -

Tuossa lienee yksinkertainen perusidea. Käytännön toteutus riippuu valitsemastasi kielestä.

**Comment by anadigifin** [comment]
Kiitos vastauksesta. Yritin toistaa täysin samalla vedolla:
[   INFO ] 2021-04-22 14:09:33 | Sending POST https://www.veikkaus.fi/api/sport-interactive-wager/v1/tickets:
[
    {
        "price": 100,
        "gameName": "EBET",
        "boards": [
            {
                "stake": 100,
                "BetType": "NORMAL",
                "selections": [
                    {
                        "listIndex": 6362,
                        "competitors": [
                            1
                        ]
                    }
                ]
            }
        ]
    }
]
[WARNING ] 2021-04-22 14:09:33 | hello
[  ERROR ] 2021-04-22 14:09:33 | Request failed 400, Bad Request. URL: https://www.veikkaus.fi/api/sport-interactive-wager/v1/tickets

eli bad request on vastauksena.

**Comment by tmansner** [comment]
Hei

Kysymyksessä #143 on malli yksinkertaisesta ptikävedosta. Tuossa sinun vedossa on ylimääräiset "[]" koko jsonin ympärillä.

**Comment by mackepee** [comment]
Tuanoi, syy on varmaan siinä että tuo esimerkin "ebet-wager-request.json" pitää kirjoittaa niin että jokaisen lainausmerkin ( " ) eteen tulee backslash ( \ ) merkki. Tällä alustalla kun yritin sitä tuossa malliksi kirjoittaa niin ne takakenot katosi matkalla bittiavaruuteen. Pyytäisin siis uusimaan yrityksen ja lisäämään edellä kerrotusti yhden \ merkin kunkin noin parinkymmenen " merkin eteen. Ainakin itsellä se menee sillä läpi.
