### ISSUE TITLE
Vakioveikkaus

### ISSUE THREAD

**Issue by matsfr** [VeikkausOy/sport-games-robot#155]
Onko nyt niin, että vakioveikkaukseen ei voi enää veikata kuin Veikkauksen esittämiä tapoja käyttäen?
Sain tiedon, että URL:iin perustuvaan vakiorivien lähetykseen ei ole paluuta aivan lähiaikoina, voi kestää todella kauan.
Tiedostomuotoisena ei onnistu sekään vaikka se on onnistunut Ruotsissa vuosia, tätäkin kuitenkin mietitään.

Latasin veikkausrobotin, eikä silläkään onnistunut rivien lähetys. Syy ei selvinnyt. On joskus aikoinaan onnistunut.
Mielestäni tein niinkuin on ohjeistettu.

Alkaa turhauttaa tämmöinen homma.

mats.

**Comment by TapaniJVeikkaus** [comment]
Tervehdys Mats ja kiitos viestistäsi

Veikkauksen ohjelmallisen pelaamisen palvelujen tarkoitus on auttaa asiakkaita pelaamaan esittämiämme tapoja noudattaen. Tarkemmat tiedot löytyvät täältä: https://github.com/VeikkausOy/sport-games-robot.

Valitettavasti kuvauksesi rivien lähetyksestä ei oikein riitä siihen, että tekniset asiantuntijamme voisivat sinua auttaa. Jos edelleen haluat konkreettista apua, pyydän, että kuvaat ongelmasi hieman tarkemmin. Hyvää alkukesän jatkoa.

yst terv tapani jämsen
ICT-arkkitehti, Veikkaus

**Comment by matsfr** [comment]
Liitteenä kuva tilanteesta.
Voitto-osuudet kyllä hakee mutta ei lähetä rivejä.
Aikaisemmin, kuukausia sitten, on toiminut ja tämän robot-version latasin
toissapäivänä.
Win10 ja firefox.
Onko jotain mennyt minulta ohi?
tv.mats

su 16. toukok. 2021 klo 10.27 Tapani Jamsen ***@***.***)
kirjoitti:

**Comment by TapaniJVeikkaus** [comment]
Mats, missä on mainitsemasi kuvaliite?

**Comment by matsfr** [comment]
Kyllä se on mukana tuossa meilissä, ainakin täältä lähtiessä
[image: Vakio3.jpg]
no kokeillaan näin.
mats.

ma 17. toukok. 2021 klo 9.10 Tapani Jamsen ***@***.***)
kirjoitti:

**Comment by matsfr** [comment]
Kokeilin myös toisella koneella, sama lopputulos myös sillä.
Lähetys ei onnistunut.

ma 17. toukok. 2021 klo 18.08 Mats Frogell ***@***.***)
kirjoitti:

**Comment by TapaniJVeikkaus** [comment]
Hei taas Mats, en löydä täältä enkä s-postin liitteestä kuvia, joten laittaisitko mulle työpostiin tapani.jamsen@veikkaus.fi niin toimitan sen eteenpäin asiantuntijoillemme, jotka tsekkaavat tilannetta ja palaavat sinulle tätä kautta, kiitos.

**Comment by tmansner** [comment]
Hei,

näytät käyttävän vielä vanhaa Excel robottimallia, millä ei tosiaan voi enää pelata pelejä. Lataa uusi versio täältä: [Robot.xlsm](https://github.com/VeikkausOy/sport-games-robot/blob/master/Excel%20VBA/Robot.xlsm).

**Comment by matsfr** [comment]
Latasin uuden, kerroin ensimmäisessä viestissä.
https://github.com/VeikkausOy/sport-games-robot/blob/master/Excel%20VBA/Robot.xlsm
ja sieltä download.
Onko nyt niin, että tuolla on vanha versio?
Vaihtakaa se uusi tuonne.
Tuon osoitteen saa kun googlaa ja menee polkuja eteenpäin.
Kiitos.
mats.

ti 18. toukok. 2021 klo 17.11 tmansner ***@***.***) kirjoitti:

**Comment by matsfr** [comment]
Ei onnistu vieläkään.
Vaikka kirjaudun ja näkyy tiedot niin ei hae voitto-osuuksia ja kun yritän
lähettää rivit pyytää kirjautumaan.
mats.

ti 18. toukok. 2021 klo 17.30 Mats Frogell ***@***.***)
kirjoitti:

**Comment by tmansner** [comment]
Täältä ei enää ole ladattavissa kuin uusi versio. Jos alla kuvatut kentät eivät näytä samoilta kuin sinulla, tarkista mihin se ladattu tiedosto meni ja että avaat oikean.

Spekuloidessa ei tarvitse kirjatumista, sen pitäisi näyttää tältä:
![Spekulointi](https://user-images.githubusercontent.com/19664199/118686432-aad2eb80-b80c-11eb-95f7-303ad72f28d7.png)

Huomaa että kenttä "Listan ID" pitää olla täytettynä kohteen tiedoista.

Pelaaminen edellyttää kirjautumista ja kentät "Pelitapa" ja "Lista" ovat oleellisia, "Pelitapa" valitsee pelatko järjestelmän vai hajarivit, "Lista" on pakollinen arvo kohteen tiedoista esim. Vakio 1:n "Lista" on 1. Tässä esimerkissä pelataan kaksi hajariviä listaan 4:
![Pelaaminen](https://user-images.githubusercontent.com/19664199/118688088-647e8c00-b80e-11eb-8890-35c351b457fd.png)

**Comment by matsfr** [comment]
Nyt toimii.
Mietin aikaisemmin tuota Lista solua ja laitoin Listan id numeron siihen,
ei toiminut.
Vaihdoin siihen pelinumeron, joksi sitä kutsuttiin ennen, 4 ja toimii.
Pitäisikö tuo Lista muuttaa teidän Pelinumeroksi?
Hyvä näin kun toimii.
Kiitos.
mats.

ti 18. toukok. 2021 klo 19.24 tmansner ***@***.***) kirjoitti:
