### ISSUE TITLE
Monivetorivien lähettäminen ei enää toimi

### ISSUE THREAD

**Issue by allanrt** [VeikkausOy/sport-games-robot#156]
Jostain syystä en saa monivetorivien lähetystä enää toimimaan;  aikaisemmin (ainakin vielä toukokuussa 2020 ) se on toiminut hyvin.
 
Olen aikaisemmin käyttänyt lähettämiseen UKK:ssa kuvattua JSON-pyyntöä:
 
[{
        "type": "NORMAL", 
        "drawId": "51219", 
        "gameName": "MULTISCORE", 
        "selections": [{
                "systemBetType": "REDUCED",
                "isQuickpick": false, 
                "outcomes": [{"tie": {"selected": false},"away": {"selected": true},"home": {"selected": true}}], 
                "score":{"home":[0,1,2],"away":[0,1]}
            },{
                "systemBetType": "REDUCED", 
                "isQuickpick": false, 
                "outcomes":[{"tie":{"selected":false},"away":{"selected":true},"home":{"selected":true}}], 
                "score":{"home":[0,1,2],"away":[0,1]}
            }], 
        "stake": 95
}]
Taulukkoon olen laittanut max. 15 hajariviä. Esim. lähetettäessä yksi rivi on aikaisemmin tullut seuraava reply:
 
[            
    {
    "status":"ACCEPTED",
    "type":"NORMAL",
    "drawId":"59053",
    "gameName":"MULTISCORE",
    "price":30,
    "serialNumber":"1001-044503297-40",
    "selections":    
[
{"systemBetType":"SYSTEM","isQuickpick":false,"score":{"home":[6],"away":[0]}},{"systemBetType":"SYSTEM","isQuickpick":false,"score":{"home":[1],"away":[0]}},{"systemBetType":"SYSTEM","isQuickpick":false,"score"{"home"[1],"away"[2]}}],"stake":30}
]
 
Jos minulla on lähetettävä esim. 1000 monivedon hajariviä (jokaisessa rivissä siis vain yksi maalimäärä/joukkue), niin millaisilla JSON-pyynnöillä se tehdään tehokkaimmin/nopeiten. Olisi hyvä jos saisi pyynnöstä esimerkin; muilta osin (loggaantumiset, tilin saldon haku, etc.) rajapinta on toiminut hyvin.

**Comment by tmansner** [comment]
Hei,

valitettavasti tuota UKK osiota ei ole päivitetty uuden formaatin mukaiseksi, mutta ajantasaiset mallit löytyvät tuolta doc osiosta. Siellä ei nyt ole tuolle monivedon merkinpoistolle esimerkkiä, mutta se näyttää tältä:

`{"listIndex":10,"gameName":"MULTISCORE","price":2400,"boards":[{"betType":"Reduced 24","stake":100,"selections":[{"homeScores":[0,1,2],"awayScores":[1,2],"exclude":["HOMEWINS","AWAYWINS"]},{"homeScores":[2],"awayScores":[3]},{"homeScores":[4,5,6],"awayScores":[4,5,6,7,8],"exclude":["TIES"]}]}]}`

Tuossa siis pelataan moniveto 10 kohteeseen 24 hajarivin merkinpoistojärjestelmä. BetType:ssa oleva numero on siis hajarivien määrä järjestelmässä merkinpoistojen jälkeen.

Hajarivien lähetykseen taas on kätevintä käyttää tuota `/api/sport-interactive-wager-set/v1/tickets/set` rajapintaa, jolle voi antaa 2-25 hajariviä listana, yksittäisen monvedon malli löytyy täältä [moniveto](../doc/multiscore-wager-request.json).

**Comment by tmansner** [comment]
UKK on myös päivitetty ajantasalle.

**Comment by allanrt** [comment]
Kiitos vastauksesta, 

En saa edelleenkään hajarivien lähetystä toimimaan. Onko jossain esimerkki jolla lähetetään **enemmän** kuin yksi hajarivi ?

Kun teen alla olevan 2 hajarivin pyynnön, niin tulee vastauksena **{"code":"NOT_FOUND"}**

{ 
	"listIndex": 5,
	"gameName": "MULTISCORE", 
	"price": 40, 
	"boards": [
	{
		"betType": "REGULAR", 
		"stake": 20, 
		"selections": [ 
		{ "homeScores": [ 0 ], "awayScores": [ 0 ]}, 
		{ "homeScores": [ 0 ], "awayScores": [ 0 ]}, 
		{ "homeScores": [ 1 ], "awayScores": [ 1 ]}]
	},
	{
		"betType": "REGULAR", 
		"stake": 20, 
		"selections": [ 
		{ "homeScores": [ 0 ], "awayScores": [ 0 ]}, 
		{ "homeScores": [ 1 ], "awayScores": [ 1 ]}, 
		{ "homeScores": [ 0 ], "awayScores": [ 0 ]}]
	}
]}

**Comment by tmansner** [comment]
Hei, 

monivedolla useamman hajarivin lähettämiseen pitää käyttää rajapintaa `/api/sport-interactive-wager-set/v1/tickets/set`, kuvaus kohdassa [Pelaaminen](https://github.com/VeikkausOy/sport-games-robot#pelaaminen). Silloin parametrina annettava json on lista yksittäisiä pelipyyntöjä, esimerkki [sport-multi-wager-request](https://github.com/VeikkausOy/sport-games-robot/blob/master/doc/sport-multi-wager-request.json).

Muille peleille voi yksittäisiä hajarivejä pelata myös `boards` kentän listana kuten yritit, pelikohtaiset maksimit listalle tuolla dokumentaatiossa Pelaamisen alla.
