### ISSUE TITLE
Pelitilin saldo

### ISSUE THREAD

**Issue by Jorma400** [VeikkausOy/sport-games-robot#158]
Kun yritän lukea pelitilini saldon GitHub:n kautta saan virheilmoituksen "Player ID Header missing". Minkälainen on tämän puuttuvan headerin formaatti? Saldon lukeminen on lakannut toimimasta kevään aikana.

**Comment by Jorma400** [comment]
"GitHubin kautta" tarkoittaa Veikkauksen JSON-rajapintaa.
Olen tehnyt esimerkin mukaan ja se on toiminut.
Joskus tämän kevään aikan saldon kysyminen on lakannut toimimasta.
Ja kyselyyn tulee vastaukseksi "Player ID Header missing".

**Comment by tmansner** [comment]
Kirjautumisen ja saldokyselyn rajapinnat eivät ole muuttuneet, esimerkki [python](https://github.com/VeikkausOy/sport-games-robot/tree/master/Python) toimii. 

Tarvittaessa voit ottaa yhteyttä Veikkauksen asiakaspalveluun ja antaa tarkempia tietoja (pelitilin tunniste, käyttöjärjestelmä, ohjelmointikieli), niin voidaan tutkia asiaa tarkemmin.
