### ISSUE TITLE
Tulosveto ja uusi API

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#159]
Miten toimii tulosvedon vetojen syöttäminen uudessa API:ssa vs vanha? Voisitteko laittaa esimerkkisanomat mukaan lukien selostukset mistä kyseiset tiedot saadaan. Verkkopalvelusta vakoilin, että ainakin nykyään taitaa käytössä olevan "listIndex" arvo. Tämä hieman ihmetyttää, miksi tapahtuman tunniste ei kelpaa? Lisäksi, mistä tämä tunniste pitäisi päätellä? Mikään rajapinta ei sitä tällä hetkellä palauta, vai onko minulla käytössä väärät (vanhat) rajapinnat?

Muita kysymyksiä:
- Sanomassa on myös kenttä "betType":"Full 1" - mitä tämä tarkoittaa ja mitkä ovat mahdolliset arvot?
- Mitä "exclude":[] osion tarkoitus on?

Olisi kyllä kiitollista jos veikkaus voisi julkaista API-kuvaukset esim. dokumenttimuodossa.

**Comment by johan313** [comment]
Löysin kuvaukset. Toki se että veikkauksen omat APIt ovat graphql takana tekee kyllä salapoliisityöstä vaikeata. 

Edelleen toki sitä mieltä että tuo indeksipohjainen ratkaisu on erittäin huono sillä voi johtaa siihen että pelataan väärää kohdetta. Tämä olis mahdottomuus jos käytössä olisi tunniste, kuten aikaisemmin.

**Comment by tmansner** [comment]
Hei, 

kuvaukset löytyvät tuosta readme osiosta ja esimerkit doc-hakemistosta, mm. kuvaus ja esimerkki sport-open-games rajapinnasta, josta löytyy tuo "listIndex".  BetType:n arvoa on käsitelty aiemmassa kysymyksessä [137](https://github.com/VeikkausOy/sport-games-robot/issues/137). 

Tuota "exclude" kenttää voi käyttää tulos- ja monivedoissa, sillä voi järjestelmästä sulkea pois tasapelit, koti- tai vierasvoitot, arvot ovat "TIES", "HOMEWINS" ja "AWAYWINS". Esim.
```
{

    "listIndex": 1,
    "gameName": "SCORE",
    "price": 200,
    "boards": [
        {
            "betType": "Full 2",
            "stake": 100,
            "selections": [
                {
                    "homeScores": [ 1,2 ],
                    "awayScores": [ 1,2 ]
                },
            "exclude": ["TIES"]            
            ]
        }
    ]
}
```
