### ISSUE TITLE
Oman pelihistorian hakeminen

### ISSUE THREAD

**Issue by storniai** [VeikkausOy/sport-games-robot#16]
Moikka,
Onko mahdollista hakea API:n kautta käyttäjän omat pelit? Tarkoitan siis käyttäjän omaa pelihistoriaa mikä löytyy käyttöliittymän kautta alla olevan linkin takaa: 
https://www.veikkaus.fi/fi/omat-pelit

Esimerkkeissä on ohjeistettu mm. kirjautuminen mutta tästä ei ole mitään mainintaa.

**Comment by ceel** [comment]
Moi,

Joo, tuo on mahdollista käyttäjän transaktioiden avulla. Transaktiot on saatavilla transactions(/api/v1/players/self/account/transactions)-apin kautta esimerkiksi tällaisella kutsulla: `/api/v1/players/self/account/transactions?size=10&sort-by=RESULT_DATE`. Listasta näkyy tehdyt ostot, maksetut voitot, palautukset, jne. Itse pelistä listassa on tietoa hyvin vähän, mutta ostetun pelin tarkemmat tiedot on haettaviessa wagers-kutsulla transaktioissa olevien externalId:n avulla esimerkiksi näin: `/api/v1/draw-games/wagers/1234-123456789-12`.

**Comment by miikama** [comment]
Hei,

Minulla GET requestit tuohon `/api/v1/draw-games/wagers/<external-id>` endpointtiin epäonnistuvat `404, Bad Request`

```json
{
"code":"INPUT_VALIDATION_FAILED",
"fieldErrors":[]
}
```
external-id olen saanut aiemmasta querystä tuohon `transactions` endpointtiin. Mitäköhän tuo odottaa payloadiksi? Tuolta esimerkeistä löysin  vain esimerkkejä wagerien asettamisista, mutta en tarkempien tietojen kyselyistä

**Comment by tmansner** [comment]
Hei,

käytät vielä vanhaa rajapintaa, uusi on `/api/draw-wager-details/v1/tickets/<external-id>`.

**Comment by miikama** [comment]
Tämä ei vieläkään ihan tunnut menevän läpi. Esimerkiksi 

```
GET https://www.veikkaus.fi/api/draw-wager-details/v1/tickets/1305-002558467-17
```

johtaa `404 NOT FOUND`, missä tuo `1305-002448467-17` on yksi omista kohteista joka löytyy omien `transactions` alta pelikohteistani. Onko kyselyssä rajoituksia siihen kuinka vanhoja pelikohteita on mahdollista kysellä?

**Comment by tmansner** [comment]
Vähintään vuosi taaksepäin löytyy tiedot, mutta tuossa tapauksessa on väärä rajapinta eli urheilupeleille pitää käyttää rajapintaa `/api/sport-wager-details/v1/tickets/<external-id>`.

**Comment by miikama** [comment]
Kiitoksia, tuolla ebet-wager-details onnistuin saamaan lisätietoja. Käyttäjän ilmeisesti pitää vain tietää minkätyyppisiä tuloksia kyselee? Esimerkiksi tuosta `transactions` endpointista saa tietoja pelitapahtumista jotka menevät sekä tuonne `sport-wager-details`että `ebet-wager-details` alle. Esimerkkinä yksi response tuolta `transactions` endpointista joista ensimmäisen tarkemmat tiedot löytyvät `sport-wager-details` ja toisen `ebet-wager-details` takaa:

```json
{
    "transactions": [
        {
            "id": 750931796,
            "externalId": "1696-056380672-453066",
            "accountingDate": 1636401202363,
            "amount": ...,
            "balanceAfter": ...
            "type": "BUY",
            "originator": "ESTE",
            "currency": "EUR",
            "transactionDate": 1636401202363,
            "product": "PICKTHREE",
            "flags": [
                "0"
            ],
            "resultDate": 1636495199000,
            "additionalData": null
        },
        {
            "id": 317575766,
            "externalId": "1305-002558467-17",
            "accountingDate": 1602614983248,
            "amount": ...,
            "balanceAfter": ...,
            "type": "BUY",
            "originator": "ESTE",
            "currency": "EUR",
            "transactionDate": 1602614983248,
            "product": "EBET",
            "flags": [
                "0"
            ],
            "resultDate": 1603663199000,
            "additionalData": null
        }
    ]
}
```

Tai, no tuosta `product` kentän arvosta saa selville mikä pelimuoto oli kyseessä. Onko niin että vaikka kaikki PICKTHREE kohteet löytyvät tuolta `sport-wager-details` takaa?

**Comment by tpokki** [comment]
Jep, EBET (pitkäveto) tiedot löytyvät `ebet-wager-details` ja muut urheilupelit `sport-wager-details`. Onnenpelit löytyvät `draw-wager-details`, jos niitä haluaa kysellä.
