### ISSUE TITLE
Kirjautumisen elinikä

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#160]
Aikaisemmin (ennen API muutoksia) kun kirjautui niin pystyi päättelemään kuinka kauan nykyinen sessio on elossa expires headeristä. Näemmä nyt siinä palautetaan aina nolla. Helpottaisi kyllä jos tietäisi kauan kirjautuminen on voimassa, niin ei tulisi tehtyä turhia kirjautumispyyntöjä / tarkistuksia. Voisiko tiedon palauttaa osaksi vastausta?

**Comment by ceel** [comment]
Cookie on nykyään sessiotyyppinen, joten siksi expires aika puuttuu. Istunnon timeout on puoli tuntia, joten sitä pienempää arvoa voi tarvittaessa käyttää vakiona refreshauksessa. Rajapinta tähän on mahdollisesti tulossa tulevaisuudessa.
