### ISSUE TITLE
Vakioharavan winshare

### ISSUE THREAD

**Issue by kaipondahl** [VeikkausOy/sport-games-robot#161]
Millaisella pyynnöllä saa Vakioharavan voitto-osuudet haettua? Laitoin winshare-request-jsoniin "betType":"R08000032_12", mutta sillä ei ole vaikutusta ja paluuna tulee liikaa rivejä (tavallisen järjestelmän osuudet).

	"pageSize":100,
	"page":0,
	"betType":"R08000032_12",
	"additionalPrizeTier":false
	"selections":[
		{"outcomes":["1","X"]},
		{"outcomes":["X","2"]},
		{"outcomes":["2"]},
		...
Vastauksena tulee siis 100 riviä + hasNext: true

**Comment by mackepee** [comment]
Morjens!

Haravan voitto-osuuksia kysyttäessä betType korvataan reducedSystemId:llä, esim:

"reducedSystemId": "R08000032_12"

**Comment by kaipondahl** [comment]
Kiitos, toimii!
