### ISSUE TITLE
Pitkävedon pelikohteet sarjoittain

### ISSUE THREAD

**Issue by mikalehtonen** [VeikkausOy/sport-games-robot#162]
Pelikohteet ja eventId:t löytyvät mutta miten löydän esimerkiksi Liiga-pelit koko joukosta?

**Comment by mackepee** [comment]
Morjens, Veikkauksen virallista vastausta odotellessa...  
... omalla kohdalla olen toistaiseksi ratkaissut asian kaksivaiheisesti.

1)
Haen kaikki päivän tapahtumat, esim:
curl https://www.veikkaus.fi/api/sport-codes/v1/fi/events/by-day/2021-09-27

Palautuneesta JSON-paketista filtteroin halutun sarjan tapahtumat, esim. Englannin Valioliiga:
(['sportId'] == 1 && ['categoryId'] == 2 && ['tournamentId'] == 1)

Suomen LIIGAssa vastaava filtteri olisi:
(['sportId'] == 3 && ['categoryId'] == 1 && ['tournamentId'] == 1)

2)
Mahd. löydetyistä otteluista poimin EVENT-ID:t ja pyydän tapahtuman kaikki kertoimet (yksi EVENT-ID/pyyntö), esim. 

curl https://www.veikkaus.fi/api/sport-open-games/v1/games/ebet/draws/by-event/100779759

Lopuksi palautuneesta JSON-paketista filtteroin itseä kiinnostavat kertoimet.

- - - - -

Laji-, kategoria- ja turnauskoodit pitää tietysti hakea ennalta ennen kuin tuon virityksen voi rakentaa, esim:

https://www.veikkaus.fi/api/sport-codes/v1/fi/sports 
https://www.veikkaus.fi/api/sport-codes/v1/fi/sports/1/categories/1
https://www.veikkaus.fi/api/sport-codes/v1/fi/sports/1/categories/1/tournaments/1

**Comment by mikalehtonen** [comment]
Isot kiitokset. Ehdin jo hieman katua, että tuli liian vähän panostettua ongelman ratkaisemiseksi, mutta näin hyvän vastauksen jälkeen tuo harmitus katosi!

Eiköhän se näillä eväillä onnistu! TY!
