### ISSUE TITLE
Tulosvedon tulosten haku

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#164]
Tähän asti Tulosvedon tulokset on voinut hakea /api/v1/sport-games/draws/SCORE/id-rajapinnan kautta. Sitten viime yön (13.10) vastaukset eivät ole sisältäneet ottelujen tuloksia, esim:

{"gameName":"SCORE","brandName":"9","id":"124961","status":"CLOSED","openTime":1634094000000,"closeTime":1634162280000,"drawTime":1634245199000,"resultsAvailableTime":1634245199000,"gameRuleSet":{"maxSelections":10,"maxPrice":0,"quickPickAvailable":true,"minStake":100,"maxStake":10000,"oddsType":"VARIABLE"},"rows":[{"id":"0","tvChannel":"Veikkaus","outcome":{"home":{"name":"CA Mineiro"},"away":{"name":"Santos"}},"score":{"min":0,"max":8},"eventId":"100893581"}]}

Onko rajapinta muuttunut vai onko tämä järjestelmävirhe?

**Comment by tpokki** [comment]
Moi, uusi rajapinta on muotoa:

```
/api/sport-results/v1/games/{game}/draws/{id}
```

Esim. https://www.veikkaus.fi/api/sport-results/v1/games/score/draws/123456
