### ISSUE TITLE
Robot.xlsm

### ISSUE THREAD

**Issue by Canorsson** [VeikkausOy/sport-games-robot#166]
Mistä johtuu, ettei Veikkauksen Robot.xlsm -tiedosto enää kykene alustamaan Excel-ikkunassa pelitietoja? Tiedostoa avattaessa tulee kyllä näkyviin alustusta tarjoava pikkuikkuna, mutta kun siinä valitsee "Kyllä", niin mitään ei tapahdu🤨 Kaikki peli- ja listatiedot ikkunan oikeassa laidassa jäävät tulematta. On hiukan vaikea syöttää itse laasdittuja vakion hajarivejä, kun ei ole tietoa listanumerosta ja -id:stä. Excelin asetuksessa on tietysti makrot päällä ja aikaisemmin alustus on toiminut.

**Comment by mackepee** [comment]
Morjens!
Alustus ei mielestäni ole koskaan noutanut peli- ja listatietoja, vaan ennemminkin tyhjentänyt käynnistyksen yhteydessä mahdolliset vanhat edellisten istuntojen aikana tallentuneet jämät.

Sekä vakio- että moniveto-taulukossa on erikseen napit (MV kohteet / Vakio kohteet), joilla avoimet pelit latautuu. Mielestäni mainittu robotti toimii tänään samalla tavalla kuin se on toiminut aiemminkin viime kuukausina.
