### ISSUE TITLE
Päivän Trion kertoimet

### ISSUE THREAD

**Issue by mikalehtonen** [VeikkausOy/sport-games-robot#167]
Oli tarkoitus päivittää omat softat jälleen toimiviksi, mutta nyt hakannut päätä seinään.

Tarkoitus olisi hakea kertoimet Päivän Trioon.

Esim tänään:

https://www.veikkaus.fi/api/v1/sport-games/draws/PICKTHREE/61375/odds

Epäilen että omassa JSON-rakenteessa on jotain pielessä vaikka olen sitä yrittänyt varioida joka suuntaan niin 400 bad request aina tuloksena.

Alla muutama esimerkki epäonnistumisista. 

{"page": 0,"pageSize":100,"additionalPrizeTier": false,"selections":[{"outcomes":["1"]},{ "outcomes":["2"]},{"outcomes":["3"]}]}

{"page": 0,"pageSize":100,"additionalPrizeTier": false,"selections":[{"competitors":[1]},{ "competitors":[2]},{"competitors":[3]}]}

"variables":{"gameName":"PICKTHREE","drawId":"a_61375","selections":[{"competitors":[4]},{"competitors":[5]},{"competitors":[6]}],"lang":"fi"}}

"selections":{"gameName":"PICKTHREE","drawId":"a_61375","selections":[{"competitors":[4]},{"competitors":[5]},{"competitors":[6]}],"lang":"fi"}}

"variables":{"gameName":"PICKTHREE","drawId":"61375","selections":[{"competitors":[4]},{"competitors":[5]},{"competitors":[6]}],"lang":"fi"}}

{"gameName":"PICKTHREE","drawId":"61375","selections":[{"competitors":[4]},{"competitors":[5]},{"competitors":[6]}],"lang":"fi"}}

**Comment by tmansner** [comment]
Hei, 

tietyn järjestelmän kertoimet saat haettua tällä jsonilla:

`{
   "selections":[
     {"competitors":[1,2]},
     {"competitors":[2,3]},
     {"competitors":[3,4]}
   ]
}
`

Rajapinta tälle kutsulle on:

`https://www.veikkaus.fi/api/sport-odds/v1/games/PICKTHREE/draws/61375/odds`

**Comment by mikalehtonen** [comment]
Isot kiitokset - nyt toimii!

Olin harhautunut kuvittelemaan, että nämä rajapinnat olisi nyt kaikille peleille, mutta taitavat siis olla vain Vakiolle ja Monivedolle.

GET /api/sport-odds/v1/games/SCORE/draws/{drawId}/odds
GET /api/sport-popularity/v1/games/SPORT/draws/{drawId}/popularity
POST /api/sport-winshare/v1/games/SPORT/draws/{drawId}/winshare

**Comment by tmansner** [comment]
Kyllä nuo ovat käytössä kaikille urheilupeleille, poikkeuksia ovat sport-winshares, joka on vain Vakiolle, ja sport-odds, joka on vain muille kuin Vakiolle.
