### ISSUE TITLE
Voittajavetojen kertoimien haku, kun niitä on yli 500

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#168]
Hei,

kuinka haetaan Voittajavetojen kertoimet, kun niitä on monta sivua? Esim. tänään 3.11.2021 Päivän Trio 1. Kun hakee pyynnöllä 
```
https://www.veikkaus.fi/api/sport-odds/v1/games/PICKTHREE/draws/61377/odds
```
niin saa 500 ekaa kerrointa. Tiedoissa on `"hasNext" : true`, mutta millä pyynnöllä saa seuraavat sivut? Tai saako jollain sivukoolla kaikki 1335 (tällä hetkellä) yhdellä pyynnöllä?

**Comment by umeetiusbaar** [comment]
Jos teen POST-pyynnön tuohon samaiseen osoitteeseen tälläisella bodylla, niin en siitäkään vastauksesta näe, että miten saisin kaikki kertoimet ulos:
```
{ "selections":[ {"competitors":[1,2,3,4,5,6,7,8,9,10,11,12]}, {"competitors":[1,2,3,4,5,6,7,8,9,10,11,12]}, {"competitors":[1,2,3,4,5,6,7,8,9,10,11,12]} ] }
```

**Comment by tmansner** [comment]
Hei,

kertoimia palautetaan  voittajavedoilla maksimissaan 500 kpl per sivu. Seuraavan sivun saat kun lisäät pyynnössä olevaan jsoniin sivun numeron `"page": n`, jossa n alkaa nollasta ensimmäisessä rajapinnan kutsussa. Jos palautettavassa jsonissa on tuo `"hasNext": true`, niin tiedät että voit pyytää seuraavan sivun. Kutsut siis samaa rajapintaa samalla jsonilla vain kasvattaen sivunumeroa, kunnes `"hasNext": false` on viimeisessä sivussa.

**Comment by umeetiusbaar** [comment]
Tämä `page` toimii vain POST:n kanssa, GET:llä ei voi kaikkia hakea?

**Comment by tmansner** [comment]
Juuri niin, jos kertoimia on enemmän kuin 500 kpl niin GET:lla niitä ei saa kaikkia.

**Comment by umeetiusbaar** [comment]
Kiitos. Asia selvä.
