### ISSUE TITLE
Kirjautumisongelma

### ISSUE THREAD

**Issue by Psonlus** [VeikkausOy/sport-games-robot#169]
Yrittäessäni kirjautumista seuraa ilmoitus: HTTP ERROR 401  Failed to POST  /api/bff/v1/sessions
Käytössä tänään ladattu Robot.xlms  -versio.  Mikä neuvoksi?

**Comment by tmansner** [comment]
Hei,

HTTP virhe 401 yleensä tarkoittaa että salasana ei ole oikein kirjoitettu syötekenttään.

**Comment by Psonlus** [comment]
Salasanani olen syöttänyt sekä käsin että Idprotection-ohjelmasta kopioimalla ja tulos on aina virheilmoitus. Veikkaus.fi sivulta niillä kyllä kirjautuu sujuvasti käyttäjätunnksella ja salasanalla.

**Comment by matsfr** [comment]
Jos sulla on nolla ensimmäisenä merkkinä käyttäjätunnuksessa niin joudut
vaihtaa solun "ominaisuuden" tekstiksi.

ke 10. marrask. 2021 klo 14.07 Psonlus ***@***.***) kirjoitti:

**Comment by Psonlus** [comment]
Hei,

Kävinkin jo GitHubissa kommentoimassa tuota vastausta. Kysymys ei voi olla
salasanan väärinkirjoittamisesta,
 sen testasin useamman kerran ja eri tavoin (=suoraan näppäimistöltä
kirjoittamalla ja myös IDPROTECTION-ohjelmasta kopioimalla.
Tuloksena aina sama virheilmoitus. Käytössä on Microsoft 365 Personal
Officeen kuuluva Excel.

Tapio Kellokoski

ke 10. marrask. 2021 klo 10.57 tmansner ***@***.***)
kirjoitti:

**Comment by tmansner** [comment]
Jos tuo matsfr:n keino ei auta ts. salasana ei ole pelkkiä numeroita ja ei ala nollalla, niin voit tutkia makrosta, mikä salasana lähtee palveluun. 

Englannin kielisessä excelissä: View -> Macros, etsi listasta Login, klikkaa Edit, koodissa rivi 95 "Ret = Request(LoginURl....", klikkaa rivin alkuun keskeytyspiste. Sitten koeta kirjautua lomakkeelta niin ohjelma pysähtyy asettamaasi kohtaan ja voit katsella "loginjson" muuttujan arvoja.

Suomalaisessa excelissä  valikot ovat Näytä -> Makrot ja Muokkaa.

**Comment by Psonlus** [comment]
Tervehdys

Ei auta solutyypin muuttaminen tekstiksi.
Sitten tuo toinen keino: Keskeytyksen jälkeen menin View-valikosta
Locals-ikkunaan, ja siellä "loginjson" muuttujan arvot ovat juuri samat
joilla veikkaus.fi sivuilta kirjaudun. En tiedä, mikä mättää.

ke 10. marrask. 2021 klo 14.51 tmansner ***@***.***)
kirjoitti:

**Comment by tmansner** [comment]
Kokeile vielä siinä debuggerissa ajaa se "Ret = Request..." komento eli shift-f8 (step over) niin varmistuu että nimenomaan siitä tulee se 401 virhe eli Ret muuttujan arvoksi tulee 401.

Seuraava vaihe on olla yhteydessä Veikkauksen asiakaspalveluun ja pyytää tarkistamaan taustajärjestelmästä mikä on syy kirjautumisen epäonnistumiselle.

**Comment by Psonlus** [comment]
: Ret : 401 : Integer

No niinhän siinä kävi, eli Ret muuttuja arvo on 401 ja tyyppiä Integer. Jos
Robotti toimii toisilla käyttäjillä ja minulla ei, en ymmärrä, eikö se
koodi ole kaikilla sama.

to 11. marrask. 2021 klo 13.08 tmansner ***@***.***)
kirjoitti:

**Comment by matsfr** [comment]
Mulle on joskus käynyt niin, että vaikka latasin uuden version niin
tietokone avasi vanhan.
Sama virhesanoma tuli muistaakseni.
Poistin kaikki vanhat versiot ja latasin uuden ja kas kummaa alkoi pelittää.
Kannattaa yrittää.

to 11. marrask. 2021 klo 16.13 Psonlus ***@***.***) kirjoitti:

**Comment by tmansner** [comment]
Varmista vielä että tunnus on oikein, jos se on numeerinen ja alkaa nollalla niin muuta solun tyyppi tekstiksi ennen syöttöä. Excel helposti päättelee sellaisen numeroksi ja pudottaa etunollat pois vaikka ne tässä tapauksessa ovat tarpeelliset.

**Comment by Psonlus** [comment]
Ei voi olla totta, alkoi toimia. En tiennyt tai muistanut, että
käyttäjätunnuksen ensimmäinen merkki on nolla.  Muutin käyttäjätunnuksen
solun tekstiksi ja syötin nollan 1. merkiksi ja sillä kirjautui sisään.
Veikkaus.fi sivulle kirjautuessani en koskaan syötä nollaa tunnukseeni, jos
oikein muistan, se on siinä joskus saattanut toki olla, mutta ei
vuosikausiin enää käytössä.  Kiitos ongelmaratkaisuun osallistuneille
vaivannäöstä ja hyvää viikonloppua!

pe 12. marrask. 2021 klo 10.00 tmansner ***@***.***)
kirjoitti:
