### ISSUE TITLE
Keno ja Lotto

### ISSUE THREAD

**Issue by janien** [VeikkausOy/sport-games-robot#17]
Hei.

Voiko API:n kautta pelata jotenkin myös Kenoa tai Lottoa (nojoo, nimi on kyllä sport-games-robot) ? Ohjeissa mainitaan kyllä Pitkäveto, Moniveto ym. muttei näistä sanallakaan. Jos tuo on mahdollista, niin saako näitten pelien tuloksia myös jotenkin haettua ? Tämä olisi mm. tilastointia varten omissa sovelluksissani hyödyllistä.

**Comment by TapaniJVeikkaus** [comment]
Hei, APIn kautta voi pelata Kenoa ja Lottoa ja tulokset, debuggaa selaimella esim. https://www.veikkaus.fi/fi/lotto, https://www.veikkaus.fi/fi/keno ja https://www.veikkaus.fi/fi/tulokset, käytä robot-api-avainta yst terv tapani jämsen, veikkaus

**Comment by janien** [comment]
Hei.

Kiitos, sain onnistumaan ohjeilla ainakin nyt tuon tuloshaun. Siinä taitaa olla rajoite, että ohjelmallisesti voi hakea tulokset vain max. viikon ajalta? No, eiköhän tuon kanssa pysty elämään. Tuota itse pelaamista en vielä ole kokeillut, mutta eiköhän sekin noiden ohjeiden avulla onnistu.

Kiitoksia.

**Comment by TapaniJVeikkaus** [comment]
Hieno homma, voitko heittää tänne muillekin esimerkkikoodin onnistuneesta tuloshaustasi... Hyvää syksynjatkoa :-)

**Comment by janien** [comment]
Hei. Sopiihan se toki. Laittelen tässä infoa, kun on paremmin aikaa.
