### ISSUE TITLE
Usean pelitapahtuman validointi

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#173]
Onko olemassa rajapintaa minkä kautta voisi validoida POST /api/sport-interactive-wager-set/v1/tickets/set -rajapintaan lähetettävät usean pelitapahtuman pyynnöt? Osaako esim. POST /api/sport-interactive-wager/v1/tickets/check validoida myös nämä?

**Comment by tpokki** [comment]
Ei valitettavasti ole. Check rajapinta löytyy vain yksittäisille tapahtumille.

Tiedoksi että järjestelmään on hiljattain lisätty uusi (beta) rajapinta tiedostopohjaiselle pelaamiselle, jossa pelitapahtumien muoto on hieman yksinkertaisempi json-rajapintaan verrattuna:

https://github.com/VeikkausOy/sport-games-robot#tiedostopohjainen-pelaaminen

**Comment by johan313** [comment]
> Ei valitettavasti ole. Check rajapinta löytyy vain yksittäisille tapahtumille

Ok, harmillista kun joutuu todentamaan toimivuuden syöttämällä vetoja. Vai onko olemassa jokin kehitys API-kokonaisuus?

Tuo uusi rajapinta vaikuttaa hyvältä, jopa erinomaiselta, uudistukselta. Tuotetaanko se Veikkausken tarpeita varten vai meitä API-rajapintaa käyttäviä pelajia varten? Jos meitä varten, niin toivosin hieman läpinäkyvyyttä siihen mitä on tulossa ja myös mahdollisuuden vaikuttaa määrittelyyn. Kuitekin ihan merkittäviä summia mitä liikkuu näiden rajapintojen kautta, joten olisi hyvä jos ainakin viestittäisiin tulevat muutokset ja suunnitelmat avoimesti.

Onko suunnitelmissa lisätä tuohon mahdollisuus asettaa vedon koko? Toki sen voi nytkin tehdä syöttämällä sama rivi useaan kertaan, jos ymmärsin oikein mitä nopeasti selasin. 

Voisiko saada jotain tilastoa odotetuista läpimenoajoista eri parametrein? Esim sanotaan että 5000 rivin käsittely kestäisi noin minuutin, tähän olisi mukavaa saada tarkempia lukuja (keskihajonta, keskiarvo ja onko suorituskyky linearista vai meneekä esim 500 riviä merkittävästi nopeammin läpi) koska tämä vaikuttaa omien algoritmien suunnitteluun.

**Comment by tpokki** [comment]
Voitko hieman avata mihin tarkoitukseen tarvitset tuota check-rajapintaa? Pelkästään json-tiedoston oikeellisuuden vahvistamiseen? Tietämällä paremmin mihin sitä käytetään, voimme evaluoida sen tarpeellisuuden yleisemminkin. 

Uusi pelitiedosto-rajapinta on tarkoitettu sekä Teidän että Veikkauksen käyttöön, ja se on tarkoituksella julkaistu täällä githubissa beta-vaiheen aikana jotta sen käytöstä saadaan kokemuksia ja palautetta. Toistaiseksi ei ole suunnitelmissa lisätä vedon kokoa tiedostoon, koska tosiaan siihen voi vaikuttaa laittamalla saman rivin useampaan kertaan.

Tiedoston läpimenoaikojen pitäisi olla melko lineaarisia, 500 rivin käsittely pitäisi mennä alle 10 sekunnissa. On kuitenkin huomioitava että tiedoston käsittely on asynkronista, ja mikäli tiedostoja on järjestelmässä käsiteltävänä paljon samanaikaisesti, käsitellään ne hyväksymisjärjestyksessä. Tiedostoja vois myös lähettää ja/tai hyväksyä useita rinnakkain. Tiettyyn rajaan asti tiedostoja siis käsitellään rinnakkain, mikä tarkoittaa että esimerkiksi viisi täysikokoista tiedostoa tulisi mennä läpi tuon saman minuutin aikana.

Tarkoituksena on seurata palvelun käyttöastetta, ja tarvittaessa kasvattaa resursseja tiedostopohjaiselle pelaamiselle mikäli sille nähdään tarvetta.
