### ISSUE TITLE
API-kutsusta tulee vastaus SUPPRESSED?

### ISSUE THREAD

**Issue by sattva1** [VeikkausOy/sport-games-robot#175]
Hei, 

Eiliseen asti vedot toimivat kyseisellä API-kutsulla:

POST https://www.veikkaus.fi/api/sport-interactive-wager/v1/tickets
{'boards': [{'betType': 'NORMAL', 'selections': [{'competitors': [2], 'listIndex': '24', 'odds': [202]}], 'stake': 1000}], 'gameName': 'EBET', 'price': 1000, 'type': 'NORMAL'}

Tänään ne on ruvennut vastamaan  {'code': 'SUPPRESSED'}. 

Onko joku muuttunut tai teenkö jotain väärin?

Kiitos

**Comment by struvababinkuk** [comment]
Sama ongelma täällä myös

**Comment by ceel** [comment]
Pitkävedon uudistuksen myötä Pitkä- ja Live-vedon pelaamiseen käytetään uusia rajapintoja, jotka eivät ole tämän robotin tuen piirissä. Uutinen uudistuksesta https://www.veikkaus.fi/fi/yritys#!/article/tiedotteet/pelit/2022/11_1_22_pitkaveto_uudistuu

**Comment by pasi555** [comment]
Pystyykö Pitkävedon pelihistoriaa jatkossa enää hakemaan API:n kautta? Eli tarkempia tietoja, joita pelikuponki sisältää. Aiemmin sai /api/ebet-wager-details/v1/tickets/{ticket-id} kautta.

**Comment by ceel** [comment]
Ennen uudistusta pelatut pelit saa tuon apin kautta ja uuteen järjestelmään tehdyt vedot uuden järjestelmän bets-rajapinnan kautta.
