### ISSUE TITLE
Pitkävedon tuen jatkuvuus

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#177]
Pitkävedon muutosten myötä myös vanha API on kokenut muutoksia. Esim. kaikkia Moniveto-kohteiden Pitkävetopelejä ei enää saa haettua. Pelaaminen ja pelattujen vetojen hakeminen on muuttunut myös. 
Tietojen haussa on sivustolla ollut jo jonkin aikaa käytössä GraphQL-rajapinta ja pelaamista / pelattujen vetojen hakuun on nyt tullut uusi https://api-fip.sbtech.com/betting API.  Vanha tuki Pitkävedolle onkin ollut täällä epävirallista.

Pari kysymystä tähän liittyen:

1. Korjaantuuko vanha Pitkävetotietojen haun API vielä eli tuoko se jatkossa kaikki Pitkävetopelit kuten teki ennen muutoksia? Eli siis tämän tyyppiset kutsut toimisivat ja toisivat kaikki ottelun Pitkävetokohteet: `https://www.veikkaus.fi/api/sport-open-games/v1/games/EBET/draws/by-event/101657291`
2. Onko web-sivuston käyttämästä GraphQL-rajapinnasta saatavilla scheemaa?
3. Onko uudesta Pitkäveto-API:sta (https://api-fip.sbtech.com/betting) saatavilla dokumentaatiota?
4. Eli summa summarum - onko epävirallinenkin tuki Pitkävedolle loppunut vai onko tulossa virallista tukea jossain kohtaa API-pelaamiselle?

**Comment by TapaniJVeikkaus** [comment]
Hei ja kiitos viestistä, tämänhetkisen näkemyksen mukaan Pitkävedon epävirallinenkin tuki on loppumassa. Yst terv tapani j.

**Comment by umeetiusbaar** [comment]
Kiitos tiedosta.
