### ISSUE TITLE
Monivedon ladattavat kerroinlistat ei toimi

### ISSUE THREAD

**Issue by 10Andy10** [VeikkausOy/sport-games-robot#178]
Esimerkiksi https://www.veikkaus.fi/odds_data/moniv_3.zip antaa virheilmoituksen sivua ei löydy. Vika alkoi noin 13.55.

**Comment by 10Andy10** [comment]
Klo 15.15 näyttäisi taas toimivan.

**Comment by 10Andy10** [comment]
Katkesi taas pian tuon jälkeen.

**Comment by 10Andy10** [comment]
Ja vaikka zipin voisikin ladata, niin se kerroindata ei ole päivittynyt.

**Comment by tmansner** [comment]
Vika korjaantui n. klo 18.30 lauantaina, pahoittelut!
