### ISSUE TITLE
Sample sport-draws-reply.json does not have any FUTURE draws

### ISSUE THREAD

**Issue by hvrauhal** [VeikkausOy/sport-games-robot#18]
Now GETting https://www.veikkaus.fi/api/v1/sport-games/draws?game-names=SPORT returns also  `FUTURE` draws: 
```json
{"draws":[      {
        "gameName": "SPORT",
        "brandName": "1",
        "id": "100011",
        "status": "FUTURE",
        "openTime": 1445202000305,
        "rollover": true,
        "jackpots": [
          {
            "id": "PRIMARY",
            "amount": 22000000,
            "description": "n. 220 000 e."
          }
        ]
      }
]}
```

This kind of draws are missing from the sample `doc/sport-draws-reply.json`

**Comment by tpokki** [comment]
Thank you for pointing that out. 

The ```FUTURE``` draws are information for wagers participating on multiple draws (kestopelit), which is not expected to be relevant for sport games robot. However, updated the example response and README with the information to distinguish the open and upcoming draws.
