### ISSUE TITLE
Totopelin kolmas vaihe

### ISSUE THREAD

**Issue by birger2022** [VeikkausOy/sport-games-robot#182]
Totopelien lähettämisessä on neljä vaihetta. Yhtä näistä vaiheista en saa millään onnistumaan. Ensimmäinen post-vaihe, jossa lähetetään peliehdotus onnistuu, samoin toinen get-vaihe, joka palauttaa {proposalId}-arvon, mutta kolmas post-vaihe ei jostain syystä onnistu. Pythonilla postauksen palaute on alla oleva. 

postauksessa käytetty linkki:  https://www.veikkaus.fi/api/toto-wager/v1/bet/{proposalId}

status_code:  404
{"code":129004,"description":"Not found"}

status_code:  400
{"code":129001,"description":"Unrecognized input."}

Myös neljäs get-vaihe onnistuu, kun get-linkissä  käyttää selaimella pelatun totopelin {ticketId} -arvoa. Myös monivedon pelaaminen onnistuu täysin. Ravipelejä olen testannut vain voittajapelillä. Käsittääkseni epäselväsksi on jäänyt, mitä Data-muuttuja pitää sisällään kolmannen vaiheen postauksessa? Tähän viittaa virheilmoitus  400 (Bad Request)

**Comment by birger2022** [comment]
Asia selvisi ja pelin lähettäminen onnistui. Oli ihan oma moka ja lukihäiriö. Lieventävänä asianhaarana mainittakoon, että kyseessä on elämän ensimmäinen python-koodi. :)

Ohjeen linkit olisi kuitenkin hyvä korjata oikeaan muotoon:

esim. 

GET /api/toto-wager/bet/{proposalId}
GET /api/toto-wager/v1/bet/{proposalId}

**Comment by TapaniJVeikkaus** [comment]
Hei ja kiitos viesteistäsi. Tein pyytämäsi muutosehdotuksen linkkikorjauksista, ja palaamme asiaan toto-asiantuntijoidemme myötä. Hyvää syksynjatkoa!

**Comment by umeetiusbaar** [comment]
Hei!

Minulla on myös ongelmia TOTOn kolmannessa vaiheessa (PUT https://www.veikkaus.fi/api/toto-wager/v1/bet/$proposalId). Aiemmat vaiheet menevät yleensä ok:

1. POST https://www.veikkaus.fi/api/toto-wager/v1/bet/13775754 bodyssä ``` {
        "proposals": [
            {
                "gameName": "TOTO",
                "type": "T5",
                "composed": false,
                "selections": [
                    [
                        1
                    ],
                    [
                        3
                    ],
                    [
                        5
                    ],
                    [
                        10
                    ],
                    [
                        8
                    ]
                ],
                "reserves": [],
                "stake": 10,
                "cost": 10
            },...
 "totalCost": 500}```
2. Vastauksena 202 ACCEPTED ja body: `{
        "proposalId": "UAYAeJx9lD1OAzEQhcfWBFkohaXQ0LniAHABl6GggipNboK25g5InIQ6JeIKHATmjXep_Ma7G0v75Xmf58en8_H26-WqnM6P7_vPi_g4_Dz7_P3whunm6fUj2_y7Dry7l50kUakGFry4xpPv_v8zcJcmeY6LpGw_uOc4Z1uCq9Vo4-pqV4Tdd2W4GW5JGO4hBsRDsAqsKVMbQNSItSo5WUyYuioCRhfvUhOMdYaHb5LQntw5Va84UDe7EsE6QkryvcTVglQmHjXgzq0tKIdgcUTcbmYtzJiJzFhhXQKMb5Ni8u_yahl4dTbH2VuFYfWMKcM1aGDgwLmKHwBMbdgLmXTJwIWVg_rGDM5LUcfGWH9vmDvXxPO94sad13jf1QPLrOloQKbWqBQVp6ZQtYez0zq3t-pH7rwcyuZ8qt7GHyyOwTw="}`
3. GET https://www.veikkaus.fi/api/toto-wager/v1/bet/UAYAeJx9lD1OAzEQhcfWBFkohaXQ0LniAHABl6GggipNboK25g5InIQ6JeIKHATmjXep_Ma7G0v75Xmf58en8_H26-WqnM6P7_vPi_g4_Dz7_P3whunm6fUj2_y7Dry7l50kUakGFry4xpPv_v8zcJcmeY6LpGw_uOc4Z1uCq9Vo4-pqV4Tdd2W4GW5JGO4hBsRDsAqsKVMbQNSItSo5WUyYuioCRhfvUhOMdYaHb5LQntw5Va84UDe7EsE6QkryvcTVglQmHjXgzq0tKIdgcUTcbmYtzJiJzFhhXQKMb5Ni8u_yahl4dTbH2VuFYfWMKcM1aGDgwLmKHwBMbdgLmXTJwIWVg_rGDM5LUcfGWH9vmDvXxPO94sad13jf1QPLrOloQKbWqBQVp6ZQtYez0zq3t-pH7rwcyuZ8qt7GHyyOwTw= (käyttäen edellisessä vastauksessa saatua proposalId:ä)
4. Vastauksena 201 CREATED ja body: `{"proposalId": 340623008, "valid":true, "totalCombinations":50,"proposals":[....]} (eli tässä tulee joku ihan toinen proposalId kuin mitä oli edellisissä vaiheissa)
5. Sitten se PUT https://www.veikkaus.fi/api/toto-wager/v1/bet/340623008, jossa vastauksena tulee 404 NOT FOUND: `{
    "code": 127004,
    "description": "Proposal not found"
}`


Toinen virhe tulee jo vaiheessa 3, kun käytän vaiheessa 2 saatua proposalId:ä, joka onkin liian pitkä:

3. GET https://www.veikkaus.fi/api/toto-wager/v1/bet/QCcAeJyFmjGuJTUQRd0tj2QRWfqjyUAdwcSQEBBYBGRISOyDFYDkeBZAgFgCq2AJbIFdDAF0Vdmv30z7XP5X6410nt3lcrnquv68efnn7Re__fzLm5f3f7z__evkPy9__-iff331zj5ef__np_v5-e_4Of-5fZtepXz-1hMc9qVP7Nk_f3znVSppO3-PVBnX1NMu8MkK4-McLXA_R4t3G-6IT7iL0T61xIcwzbF69x5eWeLd3BL4tT03bAtrOHpLasd2W7d4t61bY7Gw_VrYW3s-whZOIhzyte716MNnwNFnIGa0_MRz8s_sueGW-iZGy1hzLN69yf12LEafI7PwmmM2TW-oY_nuafl39nyEqz7A9drQNbZQwkCu7nFct-clMbkffozUei1sdcZOXITl7bT84FBsV6ytcLfp2efdJsfR57hNHP-cZMIOrCY_xAnN4XHx7kM49cRNHKLA6JYTdE_ZhO0Q4QH288Pnu4RTKVoMF353CZ9vjJVbiluOwVSSKhb1OeUusK2bLT-sxHK0DEyTH5G4aEMPSx4FcXNxsJPPA2NmakM7qNFsueGmRzc-_m1oB9ixwJlirQ1xIEdjiQ2Mgdxc0nT2-ZO0uFdBw4eXaBzdlGm7OxWCqQ3dAsWihW7h_d5VFQyMei1wl5NvmDza-V6RcidGtzje4PgPTNmhueIRPs9ewdHnOSo448raYWDlFhlrT3LuG3tu-BFrq1A0QZZ5xwxXtW4ZqVlHqss54bVLzi137ArkJb70GmM2zTGHomNet85MjoXPlVZsqag6FrslYq3ajrFpNUQVYp0dpJScGDNTU5KqDcNwYf4FfnfT6d4x-9yOH3ttS7JIbiEOaN0uBjkcQiviu03OnV-gSB2YTBtakbF0S6g9HG1yTgST6TVRS0pYTuHgugEv2IHxCHbveeAB7s_1e41ddTEWZ2xgcmqPzgG5pY9aAnE-MS4sX9nhnhUnlqPxkts9YaLS7FEN2C3ygt110uyp7KJTZMe3Foxzw9K0qlKuqS0h37vH-UHXlsBdjBZNDY8UFkVu8__giqEYGLViFEh0qmGxoXa9FmrPMYeiYbEl4-5OoTgwldjAhdad3eeYUx1zX3FiNblct5LvOTLirnGFOA-sLHeVy6MdgyDLSSaurENxYKqC-YNIXb_7mO9mjMH0lDQRK9O4vA88quBNn08ck39pzwrH5DS668mlUw-8zQXGzJSTvBvkKM4aoxicWJgmikVOUQ0UPlDGPvC61EzMTq1CpwbeSSsGxj5Tnj1JdKpLaF63VzK0PKuOqGM-JS4F-YrsmLXDwJQ8BiafD0xuCYw-f2AeLWKtRLEglVtC6YmFKSHqWC5s1wvb9cIcQzUooxIJ08RV8YHZLeL-PTHv96635KlTdMuKJcl2TEnP_Zaf7LlhOwbocyXAH9i35JbuJ4Ye18S8Y6oSlVmJpOWjFUST17D81oaaGOrYxGH57W-SE0N5H5gumuWDQvWDPTcsU49jNXlTkaqq4MQq1rgdMzD9GWliOXpmh_WWtNlvWZ-SR29vvSWP3AI-n0fwV3tWeBfR0rCOFX0vKdG4o35q4Lnu5cI2bv1NLEy7kubSqZesWeIrpy5Nc7yWsQ9c8YxdKZcn53VfGRktF6F4JWx6N_UdJpZeUz4vnnIPmrzoGqrarQ-MXquioRJ4o0tuCSlJt9iipeTEnHoOH90IN3Hpccwqt6SRWRB3K9C8sC6T5hZ_PSefb4bYtCFjBW7C8tDYEgufZ9XrKWHVjpGaXWpiKEY3FsOhaPk-MDnVd5xzakn8_3rmz38n9gMc
4. Vastauksena 414 Request-URI Too Long tai joskus 413 Request Entity Too Large


Lopputulemana TOTOn pelaaminen ei nyt onnistu, vaan tyssää joko väärään proposalId:hen PUT-vaiheessa tai liian pitkään proposalId:hen ensimmäisessä GET-vaiheessa.

**Comment by birger2022** [comment]
itsellä pitkä proposalId ei ole aiheuttanut ongelmia. Tein ensimmäisen version Pythonilla nähdäkseni miten homma toimii käytännössä, mutta pelaamiseen käytän ilmaisella Lazaruksella koodattua ohjelmaa. Olen pelannut robotilla kaikkia muita pelimuotoja (kaksari, troikka, duo jne) paitsi T-pelejä, jotka syötän edelleen lataa tiedosto -toiminnolla. Siltä osin en osaa sanoa, olisiko ongelmia ilmennyt. Periaatteessahan kaikkien pelimuotojen tiedostoformaatti on sama. T-peleissä vain enemmän pelejä, mikäli kyseessä hajoitettu systeemi. Itsellä ongelmia ei varsinaisesti ole ollut.  Olen saanut robotilla Veikkauksen ongelmien aikana  pelit läpi mielestäni paremmin kuin selaimella. Ohjelmassani on myös kerran minuutissa päivittyvä raviratojen jäljellä olevan pelinajan kertova ikkuna, jolla voi aika hyvin ennakoida , milloin Veikkauksen järjestelmä alkaa jumittua. Kellonajat eivät enää etene normaalisti. Jos vertaa aikaan ennen Veikkauksen järjestelmäpäivitystä, niin mielestäni ongelmia on nyt erityisesti ticket-vaiheessa. Odottamiseen menee 2000-3000 millisekuntia, kun aiempi oli alle alle 500 millisekuntia. Tähän liittynee myös se, että jos selaimessa painaa "näytä lisää pelejä" -nappia, niin ainakin itsellä kuluu jopa minuutteja ennen kuin lisää pelattuja pelejä tulee näkyville. Tämä ongelma ilmestyi jo ennen Veikkauksen järjestelmäpäivitystä. Joskus keväällä tai kesällä.

**Comment by birger2022** [comment]
Katselin kuinka  pitkiä proposalId:t ovat itsellä ja näyttäisi olevan luokkaa 84-88 merkkiä. Eli selvästi lyhyempiä kuin esimerkissäsi. En tiedä katsoinko tapahtuamiasi oikein, mutta tarkoitushan on köyttää samaa linkkiä sekä toisessa GET vaiheessa ja myös kolmannessa PUT vaiheessa. 

GET https://www.veikkaus.fi/api/toto-wager/v1/bet/{84-88 merkkiä pitkä proposalId}
PUT https://www.veikkaus.fi/api/toto-wager/v1/bet/{84-88 merkkiä pitkä proposalId}

**Comment by umeetiusbaar** [comment]
Minulla edelleen tulee liian pitkiä proposalId-vastauksia. Tässä yksi esimerkki:

```
{
    "headers": {
        "Content-Type": [
            "application/json"
        ],
        "Content-Length": [
            "2461"
        ],
        "Connection": [
            "keep-alive"
        ],
        "Date": [
            "Tue, 17 Jan 2023 15:46:36 GMT"
        ],
        "x-amzn-RequestId": [
            "2ef69442-b091-4557-8e0d-b6a35c4cd4b4"
        ],
        "x-xss-protection": [
            "1; mode=block"
        ],
        "x-frame-options": [
            "DENY"
        ],
        "x-amzn-Remapped-content-length": [
            "2461"
        ],
        "via": [
            "1.1 google, 1.1 bc0a0f9f99d36a68240a31a25e39addc.cloudfront.net (CloudFront)"
        ],
        "set-cookie": [
            "JSESSIONID=C9595BC3C9044FCA3CCED1F666238070; Path=/; HttpOnly"
        ],
        "x-amz-apigw-id": [
            "e5NiWGmpgi0F3vA="
        ],
        "cache-control": [
            "no-cache,no-store"
        ],
        "x-amzn-Remapped-server": [
            "Google Frontend"
        ],
        "x-content-type-options": [
            "nosniff"
        ],
        "x-cloud-trace-context": [
            "05e9032ca674422273f13ec742491e36"
        ],
        "x-amzn-Remapped-date": [
            "Tue, 17 Jan 2023 15:46:36 GMT"
        ],
        "X-Cache": [
            "Miss from cloudfront"
        ],
        "X-Amz-Cf-Pop": [
            "FRA60-P1"
        ],
        "X-Amz-Cf-Id": [
            "EkgYp6t7f8-hD9C9zYo7vHRDCe-EGugaPNVs1nlcGqeQ5rG7M1DZUg=="
        ]
    },
    "body": {
        "proposalId": "FkYAeJyVmj_OHEUQxXtbgzQmmoSIpCQkDkBGgvoCJASIU_gMHXMXRIJEQmzuwDG4AHy76qqpbrvfe_7EarH9c1VXVde_Gb9_9_df__7-26_v3334_rsPvbx-vvnzn-fX48efvn5-f_XDLz_Xt-__xs_zj_4oX7x9PX_3MT7H67-3ny-fn_pt0Bm0t885vhXwIUm08WsFrJLEpqruZZitgJcAvtQ-BPCQwDa-qeo2oE7A6gYz8AUdLNbjEzACw2Ko2kETwNMlQvc4aAw8EgiNOcudN9A9CcT30cGDWX0maRTMF5iCVPV1nxFn4VXmagHBqko8i1BSHOwshH42YxL91hjzoyVpVLXdF4iCPLnabRCW2IpYUlqqZEz1WYRq9vozxepHubMBOjyDksRDlXioEl-XuwOwulus4FRw8FFIKjh4SGBVVQ_wVCRqZxzJBWcKLz9PkVT16VLRxV1rKQUPBsbNPsilOJJ79jnjd8s_27nnSMCFVDuYqy4FTTmjQ1SiMfckUHOPg9tYJxDXxxWkElsK4xb0xILjzBM8x8WtDPTORf3o4esCGLcbhvC6s3CfChmEK0AGL-bw6y6i1JiouDDWHhWaCgnEqq0Ik9QCYomtRCZy8FQl2ueA9JoNkObMq4A1NpEmEG8fR1pRjMQ6tw8N9JWFgp5knwTz1BGzAgOtgDbsoOvfOjyDssQmSsRNMy8UcH5MIB7iHKyqxPoZEnHZ89Zv6bMFpTXFwa4Y44kPu-sC7tM1gbgXriA7Y4yvTGJIY8Y4iI1pRUwuB62QVGhFTK52V4r9ROp7llcqZHUehqExE7gtUg5eqkR3DQphBmFkApTOaIVHJsCmnrGTEE59hkamF9LYF5C7pxfSuc7Uh0xQ7SBV7RsIrOHaKnWmxcfLMwRNcE-AhlT7HvNgxlw3hHeFa5FGQT9fJ6A7fB_CAfIHlT4p-82BYHY2PKPdMAabeMbpgcb2Ulz3pcUN6VouxfaMri77EoL08UMGOwqhg5cq0dI5KXioEqUzDnCfhQnE056DrZAWl0H3JQWtgEuRwS5KjGmKgfg-ruA2FQb4UgvbRwYVPzpIQ-ibMA5hvWONVScQqx7goYDxHBc6vKYBBYJDJ1d9pBc50Op1k0Ng1B0mMZ5RdAWkZ7T7jDjWDpoKdubH7CKYClbufkNBUyV6zCHYiljsW4nrtt_iEkjrY05-Cnqbgw7P67UE0iKVQSoxZshOQDcGWh2Dpj8vpSDcPjJo_j8EfBTShvNbAHgpjqJUs7bE76GAYRUDoXsyaKpq6McF3Psxg011Tyug7C2gZnUvIBVWUFLdRdVRCBh4SGCuAhQ0dHEXkIewqg6vw4801g5Sh1fVj1X1o6UjKOC-mmUQPhjKYGd-rMpM8QTz06NOwJAIwet2OL49V7qKMNa-8lUBjEkPpqv0aqgl18DxegE1iXCfSSB3zwDxjOugFwBmDH_3sYLQ4Q7SEGZQkgifpbTycT-kIHyimUFTJRpLBQc7s3qAvJq1249YdS_3YybkR1eJp72Wnj0yhwfI_DjNjuiMeYiDVvvIFb6koIHIRDTY8LGCW9UBVlUi664BDodvG1KA7YYh-CifCdIzRgveZeEE0sj4-kElevf3uQKBdL9eQWy1L7jowXkGwxYEOoRVtxKJQ0Et1k2NdbvdA40JtahzrSBU7XVekkgrRVQ61mdWcFukJhA1pAl0FymgpJpes5jLJGPYUuGgO5yqjpdNKIQZpCGMvEYhjAKFSsoUPhSZKXzojBNoflgB3Dp8AnvZ154MRodgIFylAmwFz48B9nRWBE7jwhb0mYeqPoQCMIHGLkV624Mjk__1A5PoFuMz-uLTBIkBQocnUFPdmcOV5SyDUV4YGM1dAbHEp0tGXuMzWmrBHYGtRDnZlr0AWcUN0IpQABxkkXkZcd5SJRC6x_s1nFJ8fvP5DBoTBqFF_KOJEKVClBMruJrlzkXP6OD2ec8EsksRYCeRySB1jycXVB1FHj3QcJBu7BmMYe5T4NSCkR_XXr01ZgKRezII3ZPBQwKresaqqq6qakvbEgT7_RcgSNuwg3Tk-gjczT0ruM3CCex-UALCuSeDcO75CIRWpyqF7-MAXxA0JoMwhAmUVMNCuoJcYlWNqeoZq3LGNO1h9yhj4QQaU62MhQF25YwJxGfM_2Z4NwE46P7EFVcZXSewC2ekr3wnEO2FU0M3JtHKXQGYxLhu0GoTXvlmkF_cVsQWN0DeFVoRG1JLOc3OGGoZqFXcXqZ-uAWjtR1EtTTjBjggrtrSX1BASSItpDUZA0MYOw0aXVcQFoAAqyqRlZQAu2K1CTc87wowMrGqsAIQYC947okEMwBOjQhNzVMjUiRGkdoZM60nVLWb_WCglXvO3fWZCTR2RkswUx1nZRId3F6z6dHIgxnThLekE8gc7jccVlwHo2kiqzP4aav9538TWaUA"
    },
    "statusCode": "ACCEPTED",
    "statusCodeValue": 202
}
```

Tätä ei tapahdu aina, vaan joskus proposalId on lyhyempi ja toimii GET:n kanssa:
```
{
    "headers": {
        "Content-Type": [
            "application/json"
        ],
        "Content-Length": [
            "357"
        ],
        "Connection": [
            "keep-alive"
        ],
        "Date": [
            "Tue, 17 Jan 2023 15:46:25 GMT"
        ],
        "x-amzn-RequestId": [
            "7ceb2101-0353-486a-a855-a3e044a7d3a7"
        ],
        "x-xss-protection": [
            "1; mode=block"
        ],
        "x-frame-options": [
            "DENY"
        ],
        "x-amzn-Remapped-content-length": [
            "357"
        ],
        "via": [
            "1.1 google, 1.1 adc51edbb4dc468fb382e40b115a2f62.cloudfront.net (CloudFront)"
        ],
        "set-cookie": [
            "JSESSIONID=43E7D40026A7ED2CAA5DD13371418872; Path=/; HttpOnly"
        ],
        "x-amz-apigw-id": [
            "e5NgsETYAi0FmYA="
        ],
        "cache-control": [
            "no-cache,no-store"
        ],
        "x-amzn-Remapped-server": [
            "Google Frontend"
        ],
        "x-content-type-options": [
            "nosniff"
        ],
        "x-cloud-trace-context": [
            "0a29f54256c0c1bdc9ed62141db6ad62"
        ],
        "x-amzn-Remapped-date": [
            "Tue, 17 Jan 2023 15:46:25 GMT"
        ],
        "X-Cache": [
            "Miss from cloudfront"
        ],
        "X-Amz-Cf-Pop": [
            "FRA60-P1"
        ],
        "X-Amz-Cf-Id": [
            "LKJDourSiibnb6ZNF334uoJ2SWvKH_vp0z7HWUrTxrrnJiz_MecDUA=="
        ]
    },
    "body": {
        "proposalId": "OQUAeJyNkjEOwjAMRZsoSBVTFiYGghBcAgmVHRYGbsJe7sAFeoGubByEM8AZIEntYqraSSTXavT6_e26bV7b_WF5aZv347p2RTyr-zMkdTzNQ57tzjft8wdOuFsUE_8Mt8qHgwjvxTSE3vQ0gpbApQBGEd2BkRsFjY8K1FQnzIIaKyr4cBQsoXSyGUcaqSHngLxHBLEh1iPtVqVKO6JsBbAfTyl5rECJRhJ0OaDOUbTgUZwjzo_upQRGRS0NfAhyc8Q-kl1HCJtBvzkg2_UfWAseh6Co2C9FnfBIQVbR4GhUJhgV8VeyoP0tLuvR4M9wXYilcXH47cHzBUXzHqc="
    },
    "statusCode": "ACCEPTED",
    "statusCodeValue": 202
}
```

**Comment by tpokki** [comment]
Hei, ohjeistusta [päivitetty](https://github.com/VeikkausOy/sport-games-robot/pull/188):
https://github.com/VeikkausOy/sport-games-robot#pelaaminen-1

**Comment by birger2022** [comment]
Laitoin robotin näyttämään proposalIdn pituuden ja olleet 80 - 104 merkkiä. Pituus on aina neljällä jaollinen. Veikkauksen järjestelmä näyttää jumittuvan aika tavalla  kun Toto86 ja Toto75-pelissä  peliaikaa on jäljellä  3 minuuttia tai vähemmän. Tämän huomaa, kun katsoo GET-vaihdein odotusaikoja. Menevät usein yli 20 sekunnin. Erityisesti kuitin odottaminen. Mutta yleisesti ottaen itsellä robottipelaaminen on onnistunut erittäin hyvin.
