### ISSUE TITLE
Tulosvedon kertoimet

### ISSUE THREAD

**Issue by RPekka** [VeikkausOy/sport-games-robot#186]
Onko olemassa VBA-makro, joka lataa Tulosvetokohteen kertoimet Exceliin? Asia kiinnostaa, mutta koodaustaidot eivät riitä.

**Comment by tmansner** [comment]
Hei,

valitettavasti sellaista VBA makroa ei ole näissä malleissa tehtynä.

**Comment by mackepee** [comment]
Suoran Excel-imurin puuttuessa yksi vaihtoehto on asentaa omalle koneelle palvelinympäristö PHP-tuella. Maailmalla paljon käytetty ja toimivaksi todettu ohjelmisto on 

https://www.apachefriends.org

-yhteisön luoma XAMPP (eri variaatioineen). 

Palvelinympäristön toimiessa selaimessa voidaan ajaa esimerkiksi 

https://pastebin.com/ASbQMJhk 

halutun tulosvedon kerroinhaku ja muokata saatu data Excelin tukemaan .csv -formaattiin.

Esimerkkikuvassa tiistaina 03.01.2023 pelattavan Tappara-Jukurit -ottelun kertoimien alkua noin klo 12.
 
![odds](https://user-images.githubusercontent.com/42345083/210340810-70e1bc6c-363a-47d2-b0b4-e4a2f882d143.jpg)

**Comment by RPekka** [comment]
Kiitos, ehkä kokeilen...

**Comment by mackepee** [comment]
Sellainen varoituksen sananen unohtui päiväpostauksesta, että ... jos annat pikkusormen luomalla oman koti-internetin localhost -palvelimineen ja teet pari onnistunutta cURLausta, niin huomaat pian koko kätesi olevan syvällä taikinassa. Rutiinin kasvaessa ajatus karkaileekin jo siihen, miksi et ole tehnyt tätä jo aiemmin :)

XAMPP kannattaa harjoitellessa asentaa asennuspaketin oletusasetuksilla C-asemaan. Kokemuksen karttuessa voi sitten muokata asennusta jos tarvetta ilmenee. Oletusasennuksen seurauksena koneellesi muodostuu hakemistorakenne, mistä on löydettävissä polku

C:\xampp\htdocs (htdocs = localhostin päähakemisto)

Mikäli kopioit aiemmin mainitun pastebin -tiedoston, niin tallenna se edellä mainittuun polkuun vaikka nimellä C:\xampp\htdocs\scoreodds.php

Tiedoston testiajo toimii siten, että nettiselaimeen kirjoitetaan osoite 

localhost/scoreodds.php 

Tässä vaiheessa skripti ei vielä tiedä mitä tulosvedon kohdetta on tarkoitus zuumata. Jotta kerroinkyselyn saa kunnolla käyntiin, niin selaimen osoitteen loppuun lisätään vielä lisätietona halutun joko tulosvetokohteen pelinumero tai id. 

Esim. tulevan yön NHL-ottelun LAK/DAL pelinumero näyttää olevan 11 

localhost/scoreodds.php?pelinro=11 

Samaan lopputulokseen pääsee jos tietää että kyseisen kohteen yksilöivä id on 133648

localhost/scoreodds.php?id=133648 

Jos tuulet on suotuisat, niin tässä vaiheessa selaimessa näkyy jo puolipilkulla eroteltuina koti- ja vierasjoukkueiden maalit ja voittokertoimet. Rivit on helppo siitä hiirellä kopioida ja tallentaa millä tahansa tekstieditorilla muodossa "All types" ja nimellä "scoreodds.csv". Sitten Excelissä valinnalla "Tiedot/Hae ulkoiset tiedot/Tekstistä" löytyy haluttu kerrointiedosto. 

Mikäli kerrointen kanssa on tarvetta laajemminkin puuhata, niin jatkossa kannattaa harkita sitä, että ruudulta kopioinnin sijaan kerroindata tallennetaan tiedostoon jo suoraan hakuvaiheessa.

**Comment by RPekka** [comment]
Kiitos lisäohjeista. Loppuminuuteilla ennen vedon sulkeutumista ei oikein ehdi kopioida tietoja. Pitäisi saada tekstitiedostoon, jonka voi linkittää Exceliin.
Taidan vielä jatkaa nykysysteemiä eli kopioida kertoimet teksti-tv:stä vähän etukäteen ja päivittää manuaalisesti muutamia potentiaalisia vetovaihtoehtoja.

**Comment by mackepee** [comment]
OK - Laitoin toisen päivitetyn version osoitteeseen 

https://pastebin.com/pTuYpH2g 

mikä oletuksena **sekä printtaa kertoimet ruudulle että samalla myös automaattisesti luo csv-tiedoston** samaan hakemistoon (htdocs) kuin missä se selaimessa ajettava php-tiedostokin on. Manuaalista kopiointia ei siis tarvita. 

Myöhemmin homman laajentuessa kannattaa ehdottomasti luoda itselle mieluinen hakemistorakenne ja ohjata luotavat datapaketit sinne, jotta päähakemisto ei puuroudu ja asiat pysyvät paremmin järjestyksessä. 

Jos esimerkiksi haet kertoimet id:llä 133648 niin datatiedostoksi muodostuu scoreodds-133648.csv. 

Ja vielä kertauksena se että pelinro:lla voi hakea vain siihen asti kunnes kohde sulkeutuu. Sen jälkeen voi muutaman päivän ajan hakea sulkeutuneiden kohteiden kertoimia id:llä.

**Comment by RPekka** [comment]
Kyselin Annabetiltä tietoja Tulosvetoavusta ja sain keskustelussa vinkkiä Veikkauksen rajapinnasta. Kokeilujen ja opettelun jälkeen saan ladattua Tulosvedon kohteet ja kertoimet Exceliin suoraan ilman makroja, vaiheet liitteessä. Vastaavasti voi varmaan noutaa muutkin tiedot mitä Veikkaus rajapinnassa tarjoaa. Kiitos, mackepee, paneutumisesta asiaan, en kuitenkaan rohjennut kokeilla...

[Tulosvedon kohteet ja kertoimet Exceliin Veikkauksen verkkosivuilta.pdf](https://github.com/VeikkausOy/sport-games-robot/files/10391639/Tulosvedon.kohteet.ja.kertoimet.Exceliin.Veikkauksen.verkkosivuilta.pdf)
