### ISSUE TITLE
Pitkävedon uusi rajapinta

### ISSUE THREAD

**Issue by holmb3rg** [VeikkausOy/sport-games-robot#187]
Ilmeisesti viime vuoden uudistus on jakanut pitkävedon kohteet kahtia niin, että vain osa peleistä (events) löytyy vanhan EBET rajapinnan kautta niin onko tietoa vieläkään tuleeko uutta rajapintaa uudelle pelitarjonnalle tai korjataanko vanhaa?

Kirjoittamis hetkellä kutsu 
`https://www.veikkaus.fi/api/sport-open-games/v1/games/ebet/draws/`
löytää 198 peliä (event) vaikka tarjolla pitäisi olla yli 800. 

Onko loppuihin kohteisiin mahdollista päästä käsiksi jonkin uuden rajanpinnan kautta? SBTech?

Samaan asiaan liittyen toinen kysymys, että miksi kohteet (event) aukeavat hetkeksi ja sitten sulkeutuvat ja aukeavat taas joskus myöhemmin uudestaan haettaessa tällä kutsulla? 
`https://www.veikkaus.fi/api/sport-open-games/v1/games/ebet/draws/by-event/102143163`

**Comment by tmansner** [comment]
Hei,

valitettavasti pitkävedon ohjelmallista pelaamista ei tueta, eikä sille näin ollen ole tarjolla dokumentoitua rajapintaa.
