### ISSUE TITLE
Palvelinevästeellä kirjautuminen ei toimi

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#19]
Hei,

meidän järjestelmän kirjautuminen lakkasi toimimasta viime yön aikana silloin kun kirjautumiseen käytetään voimassa olevaa sessiota palvelimen puolella (eväste). Tavallinen kirjautuminen toimii hyvin:
>Creating new session for user XXX
>[CUSTOMER_JSESSIONID=xxxx.appd01p; Path=/; Secure, isessionid=xxxx; Expires=Mon, 19-Oct-2015 17:43:51 GMT; Path=/, Veikkaus=XXX; path=/

Mutta kun ohjelma käyttää kyseistä evästettä, niin API palauttaa:
>HTTP status: 401 Code: NOT_AUTHENTICATED

Onko jokin rikki Veikkauksen puolella vai onko tehty muutoksia siihen, miten palveluihin pitää kirjautua?

**Comment by tpokki** [comment]
Hei, 

Muutoksia on tosiaan eilen (19.10.2015 06:00) tehty, ja viittaan tuohon READMEn [keksi ohjeistukseen](https://github.com/VeikkausOy/sport-games-robot/#keksit-cookies). Eli palvelun keksit saattavat muuttua ilman erillistä ilmoitusta, ja robotin tulee hyväksyä kaikki palvelun asettamat keksit (jokaisen pyynnön yhteydessä) ilman että niitä erikseen määritellään ohjelmalle. REST-rajapinnoissa ei pitäisi olla muutoksia.

Ohjelmassa ei tulisi siis olla ennalta määritelty tiettyjä keksien nimiä tai valmiita arvoja. Ja tosiaan tuon ohjeessa olevan esimerkkiohjelman tulisi edelleen toimia moitteettomasti.

Haluaisin tarkoituksella välttää keksien nimeämistä tässä yhteydessä, jotten vahingossa tule luoneeksi mahdollisesti vanhentuvaa dokumentaatiota :smile:. Mutta mikäli ongelma ei ratkea näillä ohjeilla, niin voidaan katsoa tarkemmin mitä keksejä tällä hetkellä pyyntöjen yhteydessä liikkuu.

**Comment by johan313** [comment]
Jaahas, tälläinen muutos =)

Täytyy todeta, että vanha tapa missä pysyi kirjautuneena evästeen voimassaolon aikana, oli kyllä paljon mukavampi ratkaisu. Ymmärrän toki syyt muutokselle,

Vaikkakin palvelussa saattaa tiettyjä asioita muuttua ilman erillistä ilmoitusta, niin olisi suotavaa jos olisi jokin kanava (esim. täällä) missä veikkaus ilmoittaisi kun he tekevät merkittäviä päivityksiä / muutoksia ja/tai palvelut ovat alhalla (mikä tapahtuu aika ajoin). Säästyisi merkittävästi aikaa kun tietää mistä etsiä virhettä / kyse ei ole ohimenevästä virhetilanteesta.

**Comment by johan313** [comment]
Hm, tämä vaatii sittenkin vähän tarkennusta.

Kun kirjaudutaan (/api/v1/sessions), niin vastauksen otsikkotietueissa on seuraavat tiedot

Date=[Tue, 20 Oct 2015 18:45:01 GMT]
Set-Cookie=[isessionid=xxx; path=/; expires=Tue, 20-Oct-2015 19:15:01 GMT; secure, esa-tc=xxx; Expires=Thu, 19-Oct-2017 18:45:01 GMT; Path=/; Secure, Veikkaus=391188825.20480.0000; path=/]
Cache-Control=[no-cache]
ETag=["0cf40d1cebd536e0966d0f1c97fef8edf"]
Content-Length=[623]
X-Frame-Options=[sameorigin]
X-Content-Type-Options=[nosniff]
X-XSS-Protection=[1; mode=block]
Strict-Transport-Security=[max-age=86400; includeSubDomains]
Vary=[Accept-Encoding]
Keep-Alive=[timeout=5]
Connection=[Keep-Alive]
Content-Type=[application/json]

Elikkä asetetaan ainoastaan yksi keksi. Mikäli nyt yritetään hakea esim. tilin saldo ("/api/v1/players/self/account):

def response2 = new RestBuilder().get(HOST + "/api/v1/players/self/account"){
	contentType "application/json"
	accept "application/json"
	header 'X-ESA-API-Key', 'ROBOT'
	header 'Cookie', cookie
}

Niin HTTP status: 401 Code: NOT_AUTHENTICATED. Mikä on siis muuttunut rajapinnassa ja miksi tämä ei toimi? Valitettavsti käytössä groovy ja hyvin pitkälle custom toteutus Springin RestTemplaten varaan, joten python esimerkkitoteutuksesta ei nyt ole hyötyä. Olen kuitenkin vahvasti sitä mieltä, että tämän pitäisi toimia =)

**Comment by johan313** [comment]
Lsiäkommentti:

Mikäli täysin samalla logiikalla kutsutaan  "/api/v1/sport-games/wagers/check"

def response = new RestBuilder().post(HOST + "/api/v1/sport-games/wagers/check"){
	contentType "application/json"
	accept "application/json"
	header 'X-ESA-API-Key', 'ROBOT'
	header 'Cookie', cookie
	json bets
}

Niin kaikki toimii. Tämä palauttaa keksin [Veikkaus=407966041.20480.0000; path=/], mikä on uutta, mutta ei selitä miksi tässä pyyntö toimii mutta ei silloin kun haetaan tilin saldoa. Vai onko niin, että tätä kutsua ei autentikoida?

**Comment by tpokki** [comment]
Moi,
Tuo /check ei vaadi kirjautumista, ja toimii todennäköisesti siitä syystä. Tässä esimerkki saldon hakemisesta cURL ohjelmalla. 

```
# -D optiolla saadaan tulostettua headerit, ja vastauksesta kiinnostaa näin ollen vain 'Set-Cookie' rivit. 
$ curl -D - -H 'X-ESA-API-Key: ROBOT' -H 'Content-type: application/json' -d '{"type":"STANDARD_LOGIN","login":"mylogin","password":"mypassword"}' https://www.veikkaus.fi/api/v1/sessions 2>/dev/null | grep Set-Cookie
Set-Cookie: isessionid=xxx; path=/; expires=Tue, 20-Oct-2015 20:20:50 GMT; secure
Set-Cookie: esa-tc=yyy; Expires=Thu, 19-Oct-2017 19:50:50 GMT; Path=/; Secure
Set-Cookie: Veikkaus=zzz; path=/

# Vastauksessa oli kolme keksiä. Kopioidaan keksit saldokyselyyn...
$ curl -H 'X-ESA-API-Key: ROBOT' -H 'Cookie: isessionid=xxx; esa-tc=yyy; Veikkaus=zzz' https://www.veikkaus.fi/api/v1/players/self/account
{"status":"ACTIVE","balances":{"CASH":{"type":"CASH","balance":1234,"frozenBalance":0,"currency":"EUR"}}}
```

Epäilen että tuossa sinun tapauksessa joku kekseistä jää asettamatta, tai ehkä lähetät jälkimmäisessä pyynnössä vain "viimeisimmän keksin"?

**Comment by johan313** [comment]
Hei, kiitos vastauksesta. 

Nyt alkaa kyllä vaikuttamaan bugilta siinä miten grails/groovy käsittelee noita keksejä. Loogisesti sovelluksen pitäisi toimia juuri niin kuin yllä näytät. No nyt kun tiedän mitne asian pitää olla, niin eiköhän tämä ongelma tästä katoa huomisen aikana. Kiitos.

**Comment by johan313** [comment]
Noniin, elikkä ongelma oli se, että evästeen mukana kulki (turhia) attribuutteja mitä api ei enää hyväksynyt. Toki näistä ei mitään haittakaan ollut. Poistin ne ja kaikki toimii. Sinänsä sovellus toimi siis oikein...
