### ISSUE TITLE
APIn dokumentaatiota kaivataan

### ISSUE THREAD

**Issue by HarryTorrent** [VeikkausOy/sport-games-robot#190]
En löydä omasta mielestäni veikkauksen APIsta täydellistä dokumentaatiota.
Vastaavissa ulkomaisten vedonlyöntifirmoissa löytyy! 

Tämä github lienee ainut paikka? 

UKK wikissä väitetään:
> *Veikkauksen JSON-rajapintojen kautta voi pelata kaikkia pelejä Monivedon ja Vakion esimerkkiä noudattaen, rajapintakutsut ovat loogisesti yhdenmukaisia ja muokattavissa muiden pelien vastaaviin GitHubin ohjeiden mukaan.*

Toisaalta taas että 
> * Pitkävetoa ei virallisesti tueta ohjelmallisen pelaamisen kautta, mutta joitain ohjeita on annettu kysymyksissä GitHubin "issues" osiossa.*

Mikä on totta ja mikä ei? Voiko pelata vai eikö voi?
Miten esim. lyön vetoa Nyrkkeilyssä? Veikkaus.fi sivustossa tämä löytyy pitkävetona. Voiko siis pelata vai ei? Miten?
Normaalisiti etenisin siten että haen kyseisen urheilun id:n (jos ei tiedoss, tai voihan se mahd. myös vaihtua).
Sen jälkeen avoimet vedot (tai muu vastaava kuten turnaukset jne).

yritin esim.
kutsua ```https://www.veikkaus.fi/api/sport-codes/v1/fi/sports``` joka mainitaan UKK:sa., saadakseni id:t kaiksita mahdollisista 
urheiluista. Pukkaa 404?  Joko githubin tiedot ovat vanhentuneet tai sitten teen jotain kummaa, kun ei ole kunnon selkeää dokumentaatiota omasta mielestäni. Kirjautuminen, saldo ja ```/api/sport-open-games/v1/games/GAME/draws```
eri GAME parametreille onnistuu. En mielestäni esim löytänyt sieltä tätä

![image](https://user-images.githubusercontent.com/8774878/213665653-509b4383-c867-44ef-be43-acb6d19e322b.png)

Miten siis saan kaivettua esiin urheilun U:n kohteet k<sub>1</sub>,k<sub>2</sub>,... k<sub>n</sub>?
Voiko vai eikö voi pelata kaikkia kohteita kuten UKK:ssa vätetään?

Kaipaisin siis kunnon API dokumentaatiota jossa kerrotaan selkeästi kaikista mahdollisista API kutsuista ja niiden vaatimista parametreistä.

Tyyliin:
![image](https://user-images.githubusercontent.com/8774878/213664194-41aa9217-dd08-435d-bf8f-fdb096daca7d.png)

Robotti on sinäänsä ihan ok esimerkkinä, mutta ......

**Comment by TapaniJVeikkaus** [comment]
Hei @HarryTorrent mikä on UKK wiki, johon viittaat. Meillä ei ole ohjelmallisen pelaamisen palveluissa tukea Pitkävedolle, eikä ole tulossakaan. yst. terv. tapani jämsen, ict architect

**Comment by HarryTorrent** [comment]
Hei @TapaniJVeikkaus,
eli githubin niin sanottu dokumentaatio ei enää vastaa todellisuutta eikä "kaikkia pelejä" voikkaan pelata.
https://github.com/VeikkausOy/sport-games-robot/wiki/UKK

**Comment by TapaniJVeikkaus** [comment]
Hei @HarryTorrent pahoittelut usein kysyttyjen kysymysten vastauksissa olevasta 'kaikkia pelejä' maininnasta, jolla tosin viitataan vain noihin muuttuvakertoimisiin peleihin, mutta kieltämättä monitulkintaisesti. Pyydän tuohon korjausta, koska en itse voinut UKK-vastauksia oikaista. Meillä on ohjelmallisen pelaamisen tuki vain mainittuihin pari mutuel -peleihin, ei esim. Pitkävetoon. Tämän palvelun tarkoitus ei ole tarkoitus julkaista Veikkauksen kaikkien rajapintojen dokumentaatiota.

**Comment by HarryTorrent** [comment]
@TapaniJVeikkaus 
Okay! Asia selvä. Tämän suuntaisia viittauksia löytyi....
Harmi....
Entäs ovatko tämän osion alla olevat kyselyt valideja.
***Mikä on lajin NNN koodi / Mitä kaikkia lajikoodeja on?***
$ curl --compressed -H 'X-ESA-API-Key: ROBOT' https://www.veikkaus.fi/api/sport-codes/v1/fi/sports
jne,

joka oman tulkinnan mukaan viittaa hakuun jolla saisi kaikkien urheilujen id:t. Tuota kun kokeilin niin 404 tuli silmille.
Jos tuo kysely ei enää pidä paikkansa tai on "monitulkinnaisesti" kirjoitettu niin sitäkin voisi selventää/korjata

Tämäkin viittaa mielestäni "kaikkiin peleihin/lajeihin/urheiluun"
Loogisesti ajatellen "Kaikki" aina tarkoittaa kaikki (tai ei mitään, hehe)....

Kiitos vastauksista!

**Comment by mackepee** [comment]
Morjens! 

Lajikoodit löytyy kyllä tuolla mainitsemallasi osoitteella ihan vain osoitteen selaimeen kirjoittamalla tai luettavammassa muodossa esim. ajamalla komento  

curl https://www.veikkaus.fi/api/sport-codes/v1/fi/sports

palvelussa sivulla  

https://reqbin.com/curl 

Mitä lajikoodien määrään tulee niin lajien lukumäärä on isosti pudonnut muutaman vuoden aikana johtuen ilmeisesti viime aikojen pitkävetouudistuksesta. Minulla on pari vuotta vanha listaus missä on vielä mm. 

{"id":"25","name":"Kamppailulajit"} 

ja tuotakaan ei nykyään enää mainita. Oma tulkinta on se että ainoastaan niiden urheilulajien tunnarit on vielä julkisia joista tulee ajoittain kohteita vanhaan tapaan pelattavaksi kivijalkamyymälöissä.
