### ISSUE TITLE
Frequent http 504 errors from the api.

### ISSUE THREAD

**Issue by seb876** [VeikkausOy/sport-games-robot#191]
The api at [Post] https://www.veikkaus.fi/api/toto-wager/v1/upload responds with 504 timeout errors after processing the file for 30 seconds.

What is the actual maximum csv file upload size? Documentation quotes 50'000 but I'm getting errors with files smaller than 1000 lines.

I've tried asking for support via www.veikkaus.fi contact but I get the "we will pass that info dev team" answer an no follow up.

**Comment by TapaniJVeikkaus** [comment]
Hi seb876 here's an answer from our expert mr. Roope P.
***
Hello,

The maximum file size is 10MB (10485760 bytes). The maximum number of bets in one file is limited to 50000. With 1000 bets it should not take that long to process.
Unfortunately I cannot see from our logs what is wrong with the file.

Do these errors occur for example if you try to POST a file that has a rows from 1-10? 

I’m not saying that you should split the files this way, but I’m interested to know does this happen with every single file you try to POST?

Best regards,
Roope Paasiala
***

**Comment by seb876** [comment]
Hi Roope,

As for the limits (10MB and 50'000 lines) I'm well within that.

I'm guestimating that about a third of file uploads fail for me.
From my observations it's usually bigger files that fail on races with bigger pools.

I have not tried splitting the file after a failure.

Please find bellow an example of a file that failed on the first POST request and a timestamp and the server response.
The response was returned 30 seconds after my request.
I've removed lines 11 to 650 - I'm happy to share the full file in a private message. you can email me at 'sebix876 at gmail'.
timestamp: 2023-02-04 15:12:49 [UTC]
[failed file.csv](https://github.com/VeikkausOy/sport-games-robot/files/10669871/failed.file.csv)

![response](https://user-images.githubusercontent.com/124546383/217106125-0868c166-e432-459d-b0a3-e4bdf9838b1d.jpg)

response headers
```
"Accept-Ranges": "bytes",
"Connection": "close",
"Content-Length": "3793",
"Content-Type": "text/html",
"Date": "Sat, 04 Feb 2023 15:12:50 GMT",
"ETag": "\"26b6c580ce6a8867c7416e3cab39dc67\"",
"Last-Modified": "Sat, 10 Dec 2022 08:24:48 GMT",
"Server": "AmazonS3",
"Via": "1.1 a842e6ed7853f1a77f754cf5bae38910.cloudfront.net (CloudFront)",
"X-Amz-Cf-Id": "aihuFuCy1e_xp_ougeCNUA4av7L5UKrGmXpBWIHfTQM6dUoNkCPu_g==",
"X-Amz-Cf-Pop": "ARN54-C1",
"X-Cache": "Error from cloudfront",
"x-amz-server-side-encryption": "AES256"
```

Is the error message coming from you backend or is this something that cloudfront responds with when you backend is busy processing file?

**Comment by seb876** [comment]
@TapaniJVeikkaus is this something that you are able to help with?

**Comment by TapaniJVeikkaus** [comment]
@seb876 unfortunately I'm not able to help you with this, bus I've informed mr. Roope Paasiala, and he'll most likely knows more.
Kind regards -t.j.

**Comment by rosseli** [comment]
Hello,
I checked and tested with the short example file you provided.  There is nothing wrong with that.
From the logs I cannot see any specific reason for this behaviour so please provide me the whole file. I'll send you an email.

The error is from cloudfront because of the timeout.

Regards,
R
