### ISSUE TITLE
Vakion numerot eivät täsmää

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#192]
14.2.2022: 
Pitkävakio 5 ottelut  (https://www.veikkaus.fi/fi/vedonlyonti/vakio?kohde=a_100385) eivät ole samat kuin Vakio 5 ladattavassa tiedostossa.  Mistä ero johtuu? Pitäisikö olla ? Mistä  löytyy Pitkävakio 5:n ladattava tiedosto?

Esim.
1. Nottingham - Manchester C (zip-paketissa Manchester U - Leeds U ) 
jne.

**Comment by tmansner** [comment]
Hei,

valitettavasti noista yli 14 kohteen vakioista ei tuoteta kerroinaineistoa lainkaan, vaan tuo ladattavissa oleva on viime viikon kohteesta.
