### ISSUE TITLE
Uskomatonta mutta totta

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#193]
Jostain kumman syystä järjestelmänne ei suostunut ottamaan vastaan pelitiedostoani vaan ilmoittaa

![image](https://user-images.githubusercontent.com/22799660/219758134-6d288875-5c90-4e24-bab4-d2d4033152cd.png)

Vaikka tiedosto pitäisi kaiken järjen mukaan olla oikeaa muotoa (Futisvakio 9: 12 kohdetta) Vakio9.txt:
2111112112XX
211111212X1X
211111212X21
21111121X121
21111121XXX2
21111X2121X1
2111X1212221
2111X1212X22
2111X1212XXX
2111X2211122
212111211122
2121112111XX
21211121211X
212111212X1X
21211121X122
21211221111X
2121122111XX
212121112X1X
212121222XX1
212121X1X122
21212XX111X2
2121X1212X21
2121XX211212
2121XX21211X
212X21112111
21X111211122
21X1112111XX
21X111211X1X
21X1X1212122
21X1X1212212
2X112121X122
2X21X12111X2
X121212121XX

Kokeilin myös tyhjiä välirivejä, kuten ohje näyttäisi vaativan ,mutta sekään ei auttanut.
Onko olemassa jokin järkevä syy ettei tiedoston vienti onnistunut?

**Comment by mackepee** [comment]
Morjens! 

Olethan varmistanut, että pelitiedostosi ei sisällä BOM-piilomerkkejä? Toisin sanoen tuon virhetilanteen sattuessa kannattaisi ajaa se ainakin kokeeksi vaikkapa Notepad++ ohjelmassa ja tallentaa se siellä asetuksella Tiedostomuoto: UTF-8 (Ei BOM).

**Comment by Ylikerroin** [comment]
Kiitos vastauksesta, vika oli tosiaan tuossa BOMissa. Korjasin koodia ja nyt se toimii 😁

**Comment by mackepee** [comment]
Tätä todennäköisesti monille päänsärkyä aiheuttavaa asiaa ei Veikkauksen ohjeistuksessa käsitellä tietääkseni ollenkaan.

**Comment by tpokki** [comment]
Hei, rajapinnan pitäisi nyt hyväksyä tiedostot joissa on UTF-8 BOM (ef bb bf) mukana.
