### ISSUE TITLE
Partial responsses from the api

### ISSUE THREAD

**Issue by seb876** [VeikkausOy/sport-games-robot#194]
Sometimes the response from the api is missing data.

When placing bets and calling a GET on https://www.veikkaus.fi/api/toto-wager/v1/ticket/[ticket-id], the last step of bet placement process: get status of the placed bets, the response looks like this:

```
{
    "wager": {
        "masterId": 3730xxxxx,
        "gameName": "KAK",
        "status": "CONFIRMED",
        "totalCost": 34300,
        "channel": "WWW",
        "transactionTime": 16776xxxxx,
        "isBetfile": true,
        "poolId": 30351047,
        "poolStatus": "CONNECTED",
        "selectedRunners": [...],
        "confirmed": [
            {...}
        ],
        "totalConfirmed": 17,
        "totalCombinations": 17,
        "totalDiscarded": 0,
        "paged": false,
        "valid": true
    },
    "valid": true
}
```

Notice that the `confirmed` array has only one item while the `totalConfirmed` says 17 bets were placed.

Is there a way to get all of the confirmed bets to show up here so I can get the ticket IDs?

**Comment by rosseli** [comment]
Hello,

You can use the https://www.veikkaus.fi/api/toto-wager/v1/wager/[wagerId] to get all the tickets.
