### ISSUE TITLE
Pelitiedoston pudottaminen ei toimi vieläkään

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#195]
Sama? ongelma nyt 12 - kohteen NHL vakion kanssa kuin  aeimmin

https://github.com/VeikkausOy/sport-games-robot/issues/193

Tosin tiedoston pudottamisen jälkeen tulee näyttö

![image](https://user-images.githubusercontent.com/22799660/226721204-4a3b2cb3-7cc6-44f7-a0c2-e9b9ade5bc9f.png)

Missä mahtaa olla vika? Pudotetun tiedoston alku näyttää seuraavalta;

111121121X21
11112112X111
111121221122
111121X11121
111121X22X12
11112X122122
1112212XX112

Toiminut aiemmin 13-kohteen jalkapallovakiossa.

**Comment by VeikkausOy** [comment]
Hei, kiitos tiedosta. Pelitiedoston lähetys nettisivun välityksellä on mennyt äskettäin rikki. Tähän on tulossa korjaus.
