### ISSUE TITLE
Pitkävedon kertoimet

### ISSUE THREAD

**Issue by hayraxe** [VeikkausOy/sport-games-robot#197]
Pitkävedon ylätason kertoimet (1x2 ja 12) löytyvät kutsulla https://www.veikkaus.fi/api/sport-open-games/v1/games/EBET/draws. Millä lisäyksellä löydän tietyn eventin alatason kohteiden kertoimet? Kokeilin https://www.veikkaus.fi/api/v1/sport-games/draws?game-names=EBET&lang=fi&event-ids="xyz", mutta se ei palauta alatason kertoimia.

**Comment by mackepee** [comment]
Hiljaisuudesta päätellen Veikkaus ei taida enää pitkävetoon api-apuja tarjoilla, koska sekin vähä mitä heidän kahden EBET-alustan taktiikassa vielä tarjolla on, niin lienee jollakin aikavälillä tappouhan alla. Mutta, esimerkiksi varhain sunnuntaina 14.05.2023 pelattavan NHL-matsin Seattle/Dallas kaikki apilla löydettävät EBET-oddsit löytää osoitteesta

https://www.veikkaus.fi/api/sport-open-games/v1/games/ebet/draws/by-event/102444419  

Ja mielenkiintoisen kohteen id:n voi sitä ennen kairata paketista osoitteesta 

https://www.veikkaus.fi/api/sport-codes/v1/fi/events/
