### ISSUE TITLE
JSON ja ZIP

### ISSUE THREAD

**Issue by RPekka** [VeikkausOy/sport-games-robot#198]
Moi

Olen tutustunut Monivetoon. Olen hakenut pelikohteen kertoimet ZIP-tiedostona esim.
https://www.veikkaus.fi/odds_data/moniv_9.zip
ja JSON-muodossa
https://www.veikkaus.fi/api/sport-odds/v1/games/MULTISCORE/draws/62633/odds.
JSON-datan olen lisännyt Exceliin Power Querylla suoraan verkkosivulta ja myös tallentamalla ensin tiedostoon.

Mistä mahtaa johtua, että ZIP-tiedostossa on erilaisia rivejä kertoimineen esim. 7573, mutta JSON:ista saan Exceliin vain 400 rivin kertoimet? Avasin tiedoston myös Wordiin ja etsin avaimet “value”, 400 löytyi, eli Excel ei pilko tietoja.

Veikkauksen asiakaspalvelu ei kyennyt auttamaan, ohjasivat tänne.

**Comment by tmansner** [comment]
Hei,

ero tulee siitä että zip tiedostossa on kaikkien kombinaatioiden tiedot maaliluvuittain järjestettynä ja sport-odds palauttaa Monivedolle vain 400 ensimmäistä kerrointa kertoimen mukaan järjestettynä pienimmästä alkaen.

**Comment by tmansner** [comment]
Sille on oma käyttötarkoituksensa. Paras ja helpoin tapa saada kaikkien Monivedon kombinaatioiden kertoimet on juuri tuo zip tiedosto.

**Comment by RPekka** [comment]
OK. Uteliaana vielä kyselen, mikä se oma käyttötarkoitus on?

**Comment by mackepee** [comment]
Veikkauksen Exceliin tarjoama vakio/moniveto-robotti (**Robot.xlsm**) lienee käsittääkseni ainakin yksi ns. käyttötarkoituksista.

**Comment by RPekka** [comment]
Kyllä, robotissa JSON-dataa käytetään voitto-osuuksien spekuloinnissa. Kokeilin tämän päivän kohteelle 62639 etsiä kertoimet järjestelmälle 0,1,2-0,1,2 kaikille otteluille. Excel kyllä tulosti kaikki 729 riviä, mutta niistä 560 oli “Ei pelattu”, vain 169 yhdistelmälle tuli kerroin. ZIP-tiedostossa oli kertoimet 7133 riville, myös niille, jotka JSONissa olivat “Ei pelattu”.

Eli JSON-data on nykyisellään hyödytön tässä käyttötarkoituksessa. Ainoa käyttö lienee tutkiskella neljääsataa pienintä kerrointa.

**Comment by mackepee** [comment]
Sait ylipuhuttua kokeilemaan saman esimerkin ja minulle se kyllä antaa kaikki 729 kerrointa ja ei ainuttakaan "Ei pelattua".

**Comment by RPekka** [comment]
Juu, joku tilapäinen häiriö, yritin useaan kertaan ja aina sama tulos. Nyt tulostuu tosiaan 729 riviä, ja vaikka 4096 jos niin haluaa ja on aikaa odotella. Pitää tutkia lisää.

**Comment by RPekka** [comment]
Kiitos avusta, asia tuli selvitettyä.

**Comment by RPekka** [comment]
Aika kätevä olisi semmoinen makro, joka ilman noita spekulointeja hakisi kaikki pelatut yhdistelmät ja niiden kertoimet.

**Comment by VeikkausOy** [comment]
Lisätty sivulla olevaan dokumentaatioon maininta sport-odds -rajapinnan Monivedon 400 kertoimen rajoituksesta.
