### ISSUE TITLE
Virhe SYSTEM_GAMING_LIMIT

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#20]
Hei!

Mitähän tuo otsikossa mainittu virhe SYSTEM_GAMING_LIMIT tarkoittaa? Onko kyseessä saldon ylitys vai jokin muu tilanne? Aiemmin saldon ylitykseksi olemme tulkinneet vain virheet BALANCE_TOO_LOW ja EXCEEDED_PLAYER_AMOUNT_LIMIT.

Onko teillä jotain kattavaa listaa kaikista virheistä ja niiden merkityksestä? 

Joskus on myös tilanne, että tulee error, mutta sillä ei ole lainkaan codea. Mitä mahtaa se tarkoittaa?

--teemu

**Comment by tpokki** [comment]
Moi,
SYSTEM_GAMING_LIMIT tarkoittaa kaikille peleille yhteistä päivärajaa (3000€).

Virheet ilman erillistä virhekoodia voivat viitata luokittelemattomaan virheeseen, ja tapaukset pitäisi selvittää tapauskohtaisesti. Mikäli virheitä tulee häiritsevän usein, niin suosittelen olemaan yhteydessä suoraan [Veikkauksen asiakaspalveluun](https://www.veikkaus.fi/fi/asiakaspalvelu) (asian selvittämiseksi tarvitaan pelitilin tiedot ja ongelman ajankohta).

Valitettavasti virhekoodeista ei ole olemassa listaa robotti toteutuksille, vaan virhekoodien oletetaan olevan riittävän kuvaavia (esim. DRAW_NOT_PLAYABLE). Epäselvissä tapauksissa selvennystä voi tosiaan kysellä täältä.

**Comment by johan313** [comment]
Hei,

onko siis olemassa sellainen peliraja, että jos yhden päivän aikana pelaat 3K€ edestä pelejä, niin et pysty enää saman päivän aikana asettamaan vetoja? Hyvitetäänkö voittoja tätä rajaa vasten (elikkä jos asetat 3K€ vetoja ja voitatat 3k€, niin voisit edelleen asettaa 3k€:n edestä vetoja)?

**Comment by TapaniJVeikkaus** [comment]
Hei, 

3K€ päivittäisen pelaamisen raja on ehdoton maksimi, johon ei voittaminen vaikuta.

Yst terv tapani jämsen Veikkaus
