### ISSUE TITLE
Pitkävedon kohteiden puuttuminen JSON-vastauksesta.

### ISSUE THREAD

**Issue by goatboyyy** [VeikkausOy/sport-games-robot#22]
Pitkävedon uudistuksen jälkeen en saa enään kaikkia kohteita kun teen pyynnön api/v1/sport-games/draws?game-names=EBET. Saan ainoastaan 12 ja 1X2 kohteet, sekä muutamia Pelien määrä kohteita tennisotteluihin. Onko tämä tarkoituksenmukaista vai onko asiaan tulossa korjaus myöhemmin? Haluaisin saada myös tasoitus- ja yli/alle kohteiden tiedot.

**Comment by tpokki** [comment]
Pelikohteiden suuren lukumäärän vuoksi /api/v1/sport-games/draws?game-names=EBET palauttaa tarkoituksella vain ns. ylätason kohteet, jotka tyypillisesti ovat 12 tai 1X2 kohteita. Tapahtuman muut kohteet tulee pyytää tapahtuman tunnisteella (`event-ids` parameteri). Tunniste löytyy JSON rakenteesta seuraavasti: draws->rows->eventId

Esimerkki: 

1. Ylätason kohteet:
```
$ curl --compressed -H 'X-ESA-API-Key: ROBOT' 'https://www.veikkaus.fi/api/v1/sport-games/draws?game-names=EBET&lang=fi'|json_pp 

{
   "draws" : [
      {
         "openTime" : 1463972400000,
         "gameRuleSet" : {
            "basePrice" : 100,
            "maxStake" : 100000,
            "oddsType" : "FIXED",
            "maxPrice" : 1000000,
            "maxSystemLevel" : 10,
            "minStake" : 10
         },
         "id" : "217982",
         "status" : "OPEN",
         "closeTime" : 1464109680000,
         "rows" : [
            {
               "name" : "",
               "shortName" : "1X2",
               "description" : "",
               "eventId" : "88528374",
// ... 
```

2. Tapahtuman 88528374 kohteet. 

```
$  curl --compressed -H 'X-ESA-API-Key: ROBOT' 'https://www.veikkaus.fi/api/v1/sport-games/draws?game-names=EBET&lang=fi&event-ids=88528374'|json_pp

// ...
```

**Comment by goatboyyy** [comment]
Kiitoksia nopeasta ja hyvästä vastauksesta :+1:
