### ISSUE TITLE
Uudistunut pitkäveto

### ISSUE THREAD

**Issue by tips2016** [VeikkausOy/sport-games-robot#23]
Millainen on uuden pitkävedon rivien input-komento ts. kuinka kohde ja merkki syötetään? Vakiossa ja monivedossa merkit erotetaan puolipisteellä, mutta miten on uudessa pitkävedossa kun pelikohteen tietokin täytyy välittää...

**Comment by tpokki** [comment]
Valitettavasti referenssitoteutus ei tue kuin Vakion ja Monivedon pelaamista. Esimerkki JSON pyynnöt on lisätty doc/ hakemiston alle.

**Comment by tips2016** [comment]
Hei,

Kiitos vastauksesta. Olisi hienoa, jos uudistunutta pitkävetoa voisi pelata vakion tapaan.

Esko
-----------------------
Ystävällisin terveisin
Esko Jämsä
P. +358405011508
