### ISSUE TITLE
Omien pelien hausta

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#27]
Osoitteesta /api/v1/players/self/account/transactions?size=50&types=WIN,BUY&sort-by=RESULT_DATE voi hakea omia pelattuja pelejä, mutta voiko tuohon sort-by -parametriin antaa muuta kuin RESULT_DATE? Haluaisin hakea tiedot lajiteltuna pelaamishetken perusteella eli TRANSACTION_DATE(?) ja lopettaa seuraavien sivujen haun, kun tulee haluttu aikaväli haetuksi, mutta se ei tunnu onnistuvan ja tuo TRANSACTION_DATE antaa 400-virheen. 
Onnistuisiko jollain toisella parametrin arvolla? En haluaisi hakea kaikkia rivejä ja tehdä lajittelua ja suodatusta käsin, koska se kestää tolkuttoman kauan.

**Comment by tpokki** [comment]
Moi, pelaamishetken perusteella voi hakea kun sort-by arvona on TXDATE.

**Comment by umeetiusbaar** [comment]
Kiitos! Auttoi!
