### ISSUE TITLE
Future of dependent odds Tulosveto

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#29]
What is the current and future **official** state of Tulosveto? A few months ago when you launched the remodeling of Tulosveto as a fixed odds game you pretty much killed dependent odds Tulsoveto in the process. However, now there seem to be more games available again for the traditional Tulosveto. So what is the future and current state of dependent wager Tulosveto? 

**And then some rambling:**
Considering that the REST-Api supported Tulosveto one would have assumed that the game will not change for some time. However, it changed only a few months after the REST-Api was launched. This must have been known by all personnel at that time. Some transparency from Veikkaus would be nice, after all it is a monopoly meant to serve the people best interests and a monopoly without transparency is something we find in third world countries.

**Comment by TapaniJVeikkaus** [comment]
Thanks for the message. The official state for both Score / Correct Score type of sports games is stable. Both games are included in the sports gaming portfolio, also in the new Veikkaus company. 

However, officially, via this GitHub service, we're currently supporting robot gaming only/mainly for Vakio (Sports) and Moniveto (Multi Score) games. That is why we do not publicly offer constant info of our API changes.

Kind regards 
Tapani Jämsen, ICT Design Manager, Sports Games
