### ISSUE TITLE
robot.xlsm ei toimi kuin osittain

### ISSUE THREAD

**Issue by teros64** [VeikkausOy/sport-games-robot#31]
Miksköhän excelillä robot.xlm toimii osittain, Alustus toimii, eli nollaa kaiken, aika  toimi eli hakee ajan oikein, kirjautuminen toimii, saldoa ei hae, antaa virheen, vakio kohteet hakee, voitto osuudet ja pelaa rivit ei toimi.
antaa virheen saldon haussa 
http error 404 failed to get  /api/latest/players/self/account

voitto-osuudet
http error 400 failed to POST /api/v1/sport-games/draws/SPORT/100062/winshares

**Comment by tmansner** [comment]
Korjattu saldon käsittely. Voitto-osuuksien hausta en löytänyt vikaa, varmista että spekulatiivisessa rivissä on merkki kaikille kohteille.

**Comment by teros64** [comment]
Nyt hakee saldon ok.
voitto osuus haku antaa vielä virheen
http error 400 failed to POST /api/v1/sport-games/draws/SPORT/100062/winshares
mallirivi
1-1-2-x-1-1-1-2-1-x-1-2-x
lista 100062

pelaa rivit sama http error 400 , failed to POST /api/v1/sport-games/eagers

saan ajettua rivit pythonilla robot.py :llä siinä erotin siis puolipiste

**Comment by tmansner** [comment]
Aivan, skripti on nirso "x":t pitää olla isona "X"´:na.

**Comment by teros64** [comment]
Kiitos, nyt toimii, näemmä pythonilla kun ajaa suoraan kelpaa pienet x.

**Comment by teros64** [comment]
Moi, vielä kun saisi pelatuimmuus prosentin näkyviin , niin hyvä olisi!


________________________________
Lähettäjä: tmansner <notifications@github.com>
Lähetetty: 14. lokakuuta 2016 13:53
Vastaanottaja: VeikkausOy/sport-games-robot
Kopio: teros64; Author
Aihe: Re: [VeikkausOy/sport-games-robot] robot.xlsm ei toimi kuin osittain (#31)


Aivan, skripti on nirso "x":t pitää olla isona "X"´:na.

-

**Comment by teros64** [comment]
Moi. Miten saa haettua keno tulokset pythonilla?

Terv. Tero Sved

**Comment by tmansner** [comment]
Tuolla pitäisi onnistua, vaatii python v.3.4 tai uudemman.

[result.txt](https://github.com/VeikkausOy/sport-games-robot/files/852355/result.txt)

**Comment by kpson** [comment]
Monivedon puolella jokin häikkä, hakee listat muttei osaa spekuloida - solun kommentissa joku kenties myös pielessä? Testihaku kopoitu suoraan kommentin kahdesta ekasta kohteesta, kolmannen esimerkistä ei oikein saa toimivaa (vaikka kohteita olisi ne vaaditut kolme ko. pelikohteessa). "Run-time error '5': Invalid procedure call or argument". Vakion puoli toimii, mutta ehkä puutteena se, ettei spekuloida voi kerrallaan kuin yhtä (järjestelmä)riviä.

**Comment by matsfr** [comment]
Vakioveikkauksen spekuloinnista ehdotus:
Spekuloitava järjestelmä/harava kirjoitettaisiin soluun D25 Ja tulos/hajarivit niistä riviä alemmaksi, lähtien D26 ja alaspäin.
Jos haluttaisiin spekuloida yksittäisiä hajarivejä niin ne voitaisiin kirjoittaa/liittää esim. solusta D26 ja alaspäin. Voitto-osuus haettaisiin viereisiin soluihin.
Ihan miten helpoimmin sen saa toteutetuksi.
Haravan spekulointi myös mahdolliseksi.

**Comment by teros64** [comment]
lisäsin kenon tulostenhakuun aikaväliä, 604800, sillä saa viikon ei taida saada enempää yhteen kyselyyn.
tarvitsisin vielä päivämäärän tuloksen kanssa näkyviin, mikä olisi muuttujan nimi, date ei kelpaa, id tulee siis näkyviin, mutta ei se numero kerro tarpeeksi

**Comment by teros64** [comment]
tuo vakion omien hajarivien spukulonti olisi hyvä ominaisuus

**Comment by tmansner** [comment]
Lisäsin pvm:n tulokselle, laitoin nyt tuon skriptin gist:in: [https://gist.github.com/tmansner/aad8c32c7cebed0dadc40165eb0d4677](url)

**Comment by tmansner** [comment]
Monivedon spekuloinnista en saa tuota yllä mainittua virhettä esiin. Excel on kyllä tarkka sen muodon kanssa, ylimääräisiä välilyöntejä ei saa otteluiden välillä eikä otteluiden maalilukujen joukossa.

**Comment by teros64** [comment]
Kiitos, nyt tulee kenohakuun päivä, haen siis viikon kerralla.

**Comment by tmansner** [comment]
Lisätty Exceliin vakiolle haravien ja hajarivien spekulointi.

**Comment by teros64** [comment]
Kiitos!

24.3.2017 10.08 ap. tmansner <notifications@github.com> kirjoitti:

Lisätty Exceliin vakiolle haravien ja hajarivien spekulointi.

**Comment by matsfr** [comment]
Kiitos spekuloinnin lisäyksestä.
Kokeilin äkkiseltään ja näyttää toimivan halutulla tavalla.

**Comment by matsfr** [comment]
Vakiosta hieman lisää.
Saisikos siihen exceliin vielä Minivakio mahdollisuuden?

Onko suunnitelmissa saada mahdollisuutta jättää sisään vakion hajarivit tiedostona?
Ruotsissahan tämä on ollut mahdollista jo 20 vuotta.

**Comment by tmansner** [comment]
Lisätty Minivakio spekulointiin ja pelaamiseen mukaan, nyt voi myös pelata järjestelmän tai haravan sellaisenaan.

Tiedostolla pelaamisesta ei ole olemassa mitään suunnitelmia toistaiseksi.

Suljen nyt tämän kommenttisäikeen,  viat / kommentit / kehityspyynnöt uusiin säikeisiin.
