### ISSUE TITLE
Tulosvedon kerroinlistojen haku palauttaa toisinaan ContentLength = -1

### ISSUE THREAD

**Issue by Domppari** [VeikkausOy/sport-games-robot#32]
Moi,

Otsikon mukainen ongelma. Onko tämä tyypillistä vai jokin minun implementaatiossa oleva vika? Muut apin rajapinnat, mitä olen ehtinyt kokeila toimivat moitteetta. Kehitän C#:lla.

Tässä hieman koodia:

`  private static Stream GetTulosvetoOdds(int drawId)
        {
            HttpWebRequest request = HttpWebRequest.CreateHttp("https://www.veikkaus.fi/api/v1/sport-games/draws/SCORE/" + drawId + "/odds");
            request.Method = "GET";
            SetupHeaders(request);

            HttpWebResponse response = null;
            try
            {
                response = (HttpWebResponse)request.GetResponse();
            }
            catch (Exception e)
            {
                Console.WriteLine("Tulosveto odds request failed to following expection: " + e);
                return null;
            }

            if (response.StatusCode != HttpStatusCode.OK)
            {
                Console.WriteLine("Tulosveto odds. Server returned error: " + response.StatusCode);
                return null;
            }

            if (response.ContentLength == -1)
            {
                return null;
            }

            return GetJSONResponseStream(response);
        }
`

**Comment by tpokki** [comment]
Moi,
Microsoftin dokumentaation mukaan -1 arvoa käytetään kun vastauksessa ei ole Content-Lenght headeri tietuetta. Lisäksi näyttää tosiaan siltä että joka kerralla tätä ei ole vastauksessa.

```
$ curl -o /dev/null -D -  -H 'X-ESA-API-Key: ROBOT' https://www.veikkaus.fi/api/v1/sport-games/draws/SCORE/94476/odds 2>/dev/null
HTTP/1.1 200 OK
Date: Tue, 18 Oct 2016 19:48:05 GMT
Cache-Control: public, s-maxage=60, max-age=60
X-Frame-Options: sameorigin
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=86400; includeSubDomains
X-UA-Compatible: IE=Edge, chrome=1
Age: 45
Content-Length: 6119
Content-Type: application/json
Set-Cookie: Veikkaus=424743257.20480.0000; path=/
Set-Cookie: TS0150b1a4=0175254fa0fb9b1b1c9a38e735b5066d819dd8c7c3241bd690840227cb02be3021b95a202ca75b2e5886fd834c9c6f99f782126c8d; Path=/

$ curl -o /dev/null -D -  -H 'X-ESA-API-Key: ROBOT' https://www.veikkaus.fi/api/v1/sport-games/draws/SCORE/94476/odds 2>/dev/null
HTTP/1.1 200 OK
Date: Tue, 18 Oct 2016 19:48:08 GMT
Cache-Control: public, s-maxage=60, max-age=60
Content-Type: application/json
X-Frame-Options: sameorigin
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=86400; includeSubDomains
X-UA-Compatible: IE=Edge, chrome=1
Set-Cookie: Veikkaus=357634393.20480.0000; path=/
Set-Cookie: TS0150b1a4=0175254fa054362cf17822181ad437d4c3870be0fc52aaf2969376c3d5acf5ac5b2d14ba6fce3b62a3d422b99652f353fc7f062395; Path=/
Transfer-Encoding: chunked
```

Eli toisinaan vastauksessa käytetään Transfer-Encoding mekanismia, ja toisinaan Content-Length kenttää. Lisää tietoa löytyy mm. wikipediasta: https://en.wikipedia.org/wiki/Chunked_transfer_encoding

Kummatkin muodot ovat ns. oikeita, eli asiakasohjelman tulee ymmärtää kummatkin muodot.

**Comment by Domppari** [comment]
Kappas, enpäs tuollaisesta tiennytkään.

Täytyypä katsoa huomenna kuntoon. Kiitos selvityksestä!
