### ISSUE TITLE
Edes saldokysely ei onnistu enään

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#33]
En tiedä mitä on tapahtunut, aiemmin toimineet saldokyselyt, rivien pelaamine jne, toimivat mutta nyt ne kaatuvat virheilmoitukseen: 'HTTP/1.1 400 Bad Request'.

Käytän (valitettavasti) C++Builder XE6 joka on varmaan useimmille vieras ympäristö, mutta ohessa koodi jolla saldon nouto onnistui aiemmin. Kirjautumiseen asti kaikki menee kuten pitääkin riville if(RESTResponse1->StatusCode == 200) asti. Sen jälkeen Request-objektin arvoja muokataan vastaamaan saldokyselyä, joka suoritetaan  RESTRequest1->Execute();  // KAATUU TÄHÄN, johon ohjelma kaatuu.

Ongelma ilmaantui yllättäin, enkä mielestäni ole muuttanut ohjelmaa mikä selittäisi ongelman.
Embarcaderon RestDebuggerin avulla kirjautuminen ja saldokysely onnistuu ilman ongelmia,  

Osaisiko kukaan kertoa missä vika voisi olla ?

void __fastcall TForm1::btnSaldokyselyClick(TObject *Sender)
{
    RESTClient1->Authenticator = SimpleAuthenticator1;
    RESTClient1->BaseURL = "https://www.veikkaus.fi";
    RESTClient1->AllowCookies = true;

```
TJSONObject *json = new TJSONObject();
json->AddPair("type", new TJSONString("STANDARD_LOGIN") );
json->AddPair("login", new TJSONString( edtUserName->Text ) );
json->AddPair("password", new TJSONString( edtPassWord->Text ) );

// Kirjautuminen
RESTRequest1->Params->Clear();
RESTRequest1->Params->AddItem("X-ESA-API-Key", "ROBOT", pkHTTPHEADER);
RESTRequest1->Params->AddItem("Accept", "application/json", pkHTTPHEADER);
RESTRequest1->AddParameter("body", json,  pkREQUESTBODY);
RESTRequest1->Client = RESTClient1;
RESTRequest1->Method = rmPOST;
RESTRequest1->Resource = "api/v1/sessions";
RESTRequest1->Execute();

if(  RESTResponse1->StatusCode == 200) // Kirjautuminen onnistui
{   // Saldokysely
    RESTRequest1->Params->Delete("body");
    RESTRequest1->Resource = "api/v1/players/self/account";
    RESTRequest1->Method = rmGET;
    RESTRequest1->Execute();  // KAATUU TÄHÄN
    // virheilmoitus: 'HTTP/1.1 400 Bad Request'.
    //...
    edtSaldo->Text = saldo;
}
else
{
    ShowMessage("Kirjautuminen epäonnistui: " + RESTResponse1->ErrorMessage );
}
```

}

**Comment by tpokki** [comment]
Moi,

Näyttäisi siltä että tuo koodi tekee pyynnön joka on muotoa `/api/v1/players/self/account?=`. Eli lopussa on ylimääräinen = merkki.

**Comment by Ylikerroin** [comment]
Koodi on ^^mukainen. 

RESTRequest1->Resource = "api/v1/players/self/account";

En ymmärrä mistä kumikaan merkeistä ?= generoituu pyyntöön.

**Comment by tpokki** [comment]
Jep, ei mitään tietoa mistä moinen tuonne generoituu. Mutta voisit kokeilla lisätä jonkun dummy parametrin tuohon pyyntöön. Jos se vaikka auttaisi (ei jäisi tyhjää parametria). Eli jos pitäisi arvata, niin: 

```
RESTRequest1->AddParameter("dummy", "1",  pkGETorPOST);
``` 

... voi olla että tuo `Params->Delete("body")` jättää jotain heikkoon happeen. Yksi vaihtoehto voisi olla rakentaa pyyntö tyhjästä, eli tehdä tuo `Params->Clear()` joka välissä? 

ps. Ei ole C++ Builder XE6 kokemusta, joten edellä oleva on ihan puhdas arvaus :smiley:

**Comment by Ylikerroin** [comment]
Kiitos vastauksesta, mutta valitettavasti en saanut pyyntöä toimimaan niillä.

Alla oleva ratkaisu tuntui mielestäni todennäköisimmin toimivalta, mutta sekään ei toimi (kaikki antavat tuon saman vastauksen 'HTTP/1.1 400 Bad Request' ) 
	
        if(  RESTResponse1->StatusCode == 200) // Login onnistui
	{   // Saldokysely
		RESTRequest1->Params->Clear();
		RESTRequest1->Params->AddItem("X-ESA-API-Key", "ROBOT", pkHTTPHEADER);
		RESTRequest1->Params->AddItem("Accept", "application/json", pkHTTPHEADER);
		RESTRequest1->Resource = "api/v1/players/self/account";
		RESTRequest1->Method = rmGET;
		RESTRequest1->Execute();  // KAATUU TÄHÄN
		// virheilmoitus: 'HTTP/1.1 400 Bad Request'.
		//...
		//edtSaldo->Text = saldo;
	}

Asian tekee vielä ihmeellisemmäksi se, että RestDeguggerilla lähetetyt pyynnöt toimivat, mutta RestDeguggerista kopioiduilla komponenteilla, jossa pitäisi olla toimivat pyynnöt ei toimi. Turhauttavaa.

**Comment by Ylikerroin** [comment]
Kiitos nopeasta vastauksesta. Korjaan virheen ja tarkistan johtuiko ongelma
tuosta .
24.10.2016 9.56 "Toni Pokki" <notifications@github.com> kirjoitti:

**Comment by tmansner** [comment]
Voitsit kokeilla vaihtaa tuon `RESTRequest1->Params->Clear();` tilalle `RESTRequest1->ResetToDefaults();`

**Comment by Ylikerroin** [comment]
Kokeilin seuraavia ehdotettuja vaihtoehtoja alla näkyvässä if-rakenteessa:
a) RESTRequest1->Params->Clear(); 
b) RESTRequest1->AutoCreateParams = false;
c) RESTRequest1->ResetToDefaults();  

	if(  RESTResponse1->StatusCode == 200) // Login onnistui
	{   // Saldokysely
		//RESTRequest1->Params->Clear();
		//RESTRequest1->AutoCreateParams = false;
		RESTRequest1->ResetToDefaults();
		RESTRequest1->Params->AddItem("X-ESA-API-Key", "ROBOT", pkHTTPHEADER);
		RESTRequest1->Params->AddItem("Accept", "application/json", pkHTTPHEADER);
		RESTRequest1->Resource = "api/players/self/account";
		RESTRequest1->Method = rmGET;

		UnicodeString s = RESTRequest1->GetFullRequestURL();

		RESTRequest1->Execute();  // virheilmoitus: 'HTTP/1.1 400 Bad Request'.
		RESTResponse1->Content;
	}
	
ja debuggerilla katsoin millaisia arvoja funktio RESTRequest1->GetFullRequestURL() antaa muuttujalle s.


1)
RESTRequest1->Params->Clear();
...
s = { u"https://www.veikkaus.fi/api/players/self/account?=" }


2)
//RESTRequest1->Params->Clear(); // kommentoitu pois
...
{ u"https://www.veikkaus.fi/api/v1/players/self/account?body=%7B%22type%22%3A%22STANDARD_LOGIN%22%2C%22login%22%3A%22TUNNUS%22%2C%22password%22%3A%22SALASANA%22%7D&=" }

3)
RESTRequest1->Params->Clear();
RESTRequest1->AutoCreateParams = false;
...
{ u"https://www.veikkaus.fi/api/players/self/account?=" }

4)
//RESTRequest1->Params->Clear();    // kommentoitu pois
RESTRequest1->AutoCreateParams = false;
...
{ u"https://www.veikkaus.fi/api/v1/players/self/account?body=%7B%22type%22%3A%22STANDARD_LOGIN%22%2C%22login%22%3A%22TUNNUS%22%2C%22password%22%3A%22SALASANA%22%7D&=" }

5)
//RESTRequest1->Params->Clear();   // kommentoitu pois
//RESTRequest1->AutoCreateParams = false;  // kommentoitu pois
RESTRequest1->ResetToDefaults();
{ u"https://www.veikkaus.fi/api/players/self/account" }

Muuttujan arvo 2) ja 4) tapauksessa
s = { u"https://www.veikkaus.fi/api/v1/players/self/account?body=%7B%22type%22%3A%22STANDARD_LOGIN%22%2C%22login%22%3A%22TUNNUS%22%2C%22password%22%3A%22SALASANA%22%7D&=" }
on selkokielisenä { u"https://www.veikkaus.fi/api/v1/players/self/account?body={"type":"STANDARD_LOGIN","login":"TUNNUS","password":"SALASANA"}&=" } 

Mikään näistä ei kuitenkaan toiminut. Ilmeisesti 3) arvo olisi oikein ilman tuota = merkkiä. Jotenkin nuo login vaiheen evästeet pitäisi olla mukana saldokyselyssä. Mahtaako se hoitua automaattisesti kun Reguest-komponentti on kytketty aiemmassa pyynnössä käytettyyn RESTClient:tiin (ja RESTClient1->AllowCookies = true).  Embarcaderon dokumentointi on aika olematonta eikä esimerkkejäkään oikein ele saatavilla.

**Comment by tmansner** [comment]
Eilen klo 19.23-19.24 on ollut onnistunut login ja saldokysely (palautettu HTTP 200) ja url oli oikein logissa. Arvelen että olisi ollut tuo tapaus 5) jossa myös näkyy olevan oikeanlainen url.

**Comment by Ylikerroin** [comment]
Onnistunut saldokysely oli tehty Embarcaderon RESTDeguggerilla ei siis ohjelmallisesti. Valitettavasti C++Builder XE6:n RESTDebuggeri ei kuitenkaan ilmeisesti anna oikeita arvoja kopioitaville komponentteille.  Testasin uudemmalla ilmaisella RESTDeguggerilla (https://www.embarcadero.com/free-tools/rest-debugger), joka palauttaa headers-lehdelle erilaisen tuloksen, kuin käytössäni oleva vanhempi versio (palvelimen palauttama body-lehden JSON on sama). Valitettavasti ilmainen RESTDebuggeri ei kuitenkaan salli kyselyn komponenttien kopiointia.

**Comment by Vrobotti** [comment]
Veikkauksen oma robotti ei myöskään palauta enää saldoa rivien lähettämisen jälkeen. Tulee virheilmoitus. Rivien lähettäminen katkeilee koko ajan. Aiemmin ei ollut ongelmia.

**Comment by tpokki** [comment]
@Ylikerroin, ongelma näyttää olevan tuossa käyttämässäsi kirjastossa/ympäristössä, ja emme valitettavasti voi auttaa täältä käsin tuon enempää. Lisäämällä tuon dummy=1 parametrin pyynnölle, päätyi url parametreiksi `dummy=1&=`, eli se ei poistanut tuota haamuparametria pyynnöstä. 

Ehkä jostain C++Builder/Embarcadero forumilta voisi löytyä täsmällisempää apua asiaan? 

@Vrobotti, onko kyseessä tuo python vai excel versio? Millaisen virheen ohjelma antaa? 
Sinänsä kummatkin toteutukset ovat tarkoitettu lähinnä esimerkeiksi kuinka ohjelmallinen pelaaminen on mahdollista. Mutta jos noissa esimerkeissä on virheitä tai rajapinnat eivät toimi odotetusti, niin voidaan yrittää selvittää tilannetta.

**Comment by Ylikerroin** [comment]
Kiitos kuitenkin vaivannäöstä. Kokeilen toisilla (Indy) komponenteilla.

**Comment by tpokki** [comment]
Ok, suljen tämän issuen tältä erää. Avatkaa uusia tarpeen tullen :)
