### ISSUE TITLE
Onko tällä mahdollista saada eurojaskan viimeisimmän kierroksen tuloksia ja tulosjakoa

### ISSUE THREAD

**Issue by evantaur** [VeikkausOy/sport-games-robot#36]
ainut jolla olen jotain saanut pihalle on

`curl --compressed     -H 'Accept: application/json'     -H 'Content-Type: application/json'     -H 'X-ESA-API-Key: ROBOT'     'https://www.veikkaus.fi/api/v1/draw-games/draws'`

mutta tuokin näyttää vain tulevat arvonnat?

**Comment by tmansner** [comment]
Kysymys on vähän tämän aiheen ulkopuolella mutta kutsu tarvitsee muutaman parametrin:
`curl --compressed -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'X-ESA-API-Key: ROBOT' 'https://www.veikkaus.fi/api/v1/draw-games/draws?game-names=EJACKPOT&status=RESULTS_AVAILABLE&date-from=1479074400000&date-to=1479679200000'`

Vastauksesta löytyy "results" ja "prizeTiers", jossa on nuo tulokset ja voitonjako.

**Comment by tmansner** [comment]
Suljen tämän.
