### ISSUE TITLE
Vakion voitto-osuuksien haku

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#37]
Hei!

Vakion voitto-osuudet voi hakea POST-pyynnöllä osoitteeseen
```
https://www.veikkaus.fi/api/v1/sport-games/draws/SPORT/<draw id>/winshares
```
Pyynnössä annetaan sivunumero ja sivun koko.

Kysyisin, että mikä on sivun koon maksimi? 100? Suurempi? Tai voiko yhdellä pyynnöllä ladata kaikki voitto-osuudet samaan tapaan kuin nyt saa Monivedon kerrointiedostot zip-paketteina ladattua?

**Comment by tmansner** [comment]
Sivun koko (palautettavien voitto-osuusrivien määrä) on kiinteä 100. Jos spekuloitavan järjestelmän koko on yli 100, niin sivutus tapahtuu automaattisesti ja sivunumeron avulla saa ne hallitusti kaikki. Vakiolle ei ole tiedostoliittymää kuten monivedolle eikä siis isojen järjestelmien voitto-osuuksia saa yhdelllä kutsulla.
