### ISSUE TITLE
Vakio Grand Prix - voitto-osuuksien haku 

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#38]
Moro. Vaihdon hakuun voi olla fiksumpikin tapa mutta teen sen niin, että haen tietyllä yhdistelmällä voitto-osuuksien määrän, josta lasken vaihdon, kun tunnen palautusprosentin.

Homma toimii kaikki kaikkien muiden paitsi Grand Prix vakion kohdalla. Veikkauksen sivulla Grand Prix vakio ei myöskään anna mahdollisuutta kysyä voitto-osuuksia. Onko tämä mahdollisuus rajattu pois 18-kohteen vakiosta vai teenkö jotain väärin? Ymmärrän hyvin, että voitto-osuuksien haku 18-kohteen vakiossa kasvattaa järjestelmän rivimäärä helposti, eikä minulla olekaan tarkoitus käyttää sitä voitto-osuuksien hakuun vaan ainoastaan vaihdon selvittämiseen.

**Comment by tmansner** [comment]
Terve!

Voitto-osuuksia ei tosiaan tueta noille Vakio GP kohteille (15-20 kohdetta). Vaihdon toki saa helpomminkin käyttämällä kutsua:

` /api/v1/sport-games/draws/SPORT/[Arvonta#]/popularity
`

Palautettavassa JSON:ssa löytyy päätasolta "exchange", joka kertoo vaihdon sentin tarkkuudella.

**Comment by Ylikerroin** [comment]
Ok. Kiitos tiedosta.
