### ISSUE TITLE
Yli 2.5 / Alle 2.5 maalia sekä koti-, että vierastasoitusten haku

### ISSUE THREAD

**Issue by zuikkelo** [VeikkausOy/sport-games-robot#39]
Tiedustelisin miten saa haettua pitkävetokohteelle Yli ja alle 1.5 tai 2.5 maalia sekä tasoitusvetojen kertoimet? Syntaksilla curl --compressed -H 'X-ESA-API-Key: ROBOT' https://www.veikkaus.fi/api/v1/sport-games/draws?game-names=EBET  saan 1x2 kertoimet, mutta en tuosta listasta löydä kohteen muita vetoja.

**Comment by tmansner** [comment]
Pitkävetoa ei virallisesti tueta tämän ohjelmallisen pelaamisen puolella, mutta jos lisäät parametrin "event-ids=tunniste#" tuohon pyyntöön niin saat kaikkien alakohteiden tiedot. Tuo "tunniste#" on "id" edellisessä palautetussa JSON:ssa.
