### ISSUE TITLE
Vakion voitto-osuuksista

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#40]
![sieppaa](https://cloud.githubusercontent.com/assets/22799660/21577976/960eff90-cf77-11e6-89dd-afc8fabd6bb7.JPG)

Oheisessa kuvassa on erään rivin voitto-osuuden ajallinen kehitys (viimeisen sarakkeen arvon hain tavoitteen haulla muuttamalla vaihtoa).

Onko siis niin, että veikkaus ei laske voitto-osuutta todellisen senhetkisen vaihdon perusteella vaan olettamalla vaihtoa kertyvän tietty summa ? 

En ymmärrä kuinka Veikkaus muuten olisi saanut taulukon mukaisia voitto-osuuksia riville. Toki tuo luvattu 200 000 ylimääräistä rahaa ei ole tarkka, mutta se ei selitä mitenkään voitto-osuuksien eroa. Esim. 1 sarakkeen tapauksessa, ylimääräistä rahaa olisi oltava 270 000 euroa, jos voitto-osuus olisi laskettu hetkellisen vaihdon avulla.

**Comment by TapaniJVeikkaus** [comment]
Hei ja kiitos viestistäsi, asia on, kuten kysymyksessäsi oletit. 
Veikkaus arvioi kertyvän vaihdon tason. Tässä tapauksessa päävoittoluokkaan oli luvattu 500t ja tämä ei muutu vaihdon mukaan. Arviomme lisärahan käyttötarpeesta oli n. 200t. ja tämä perustui aikaisempiin toteumiin. Tällä kierroksella lisärahaa jaettiin 200884,- € :-)

Yst terv Sami A ja Tapani J Veikkaus Oy
