### ISSUE TITLE
Veikkaus, RAY ja Fintoto yhdistymisen vaikutus ohjelmalliseen pelaamiseen

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#41]
Olen juuri saamassa softat valmiiksi vakion, monivedon, päiväntrion, päivänpariin, superkaksariin, supertriplaan. 

Ilmeisesti yhdistyminen ei vaikuta ohjelmalliseen pelaamiseen näiden pelien osalta ts. järjestelmät eivät ole taas menossa uusiksi ?

**Comment by ceel** [comment]
Moi,

Yhdistymisellä ei ole vaikutusta ko pelien ohjelmalliseen pelaamiseen.
