### ISSUE TITLE
Lajitiedon perusteella haku / haun rajoitus

### ISSUE THREAD

**Issue by zuikkelo** [VeikkausOy/sport-games-robot#42]
Tiedustelisin onko mitenkään mahdollista hakea suoraan lajitiedon sportId:n avulla esim. jalkapalloon liittyviä tapahtumia? Nyt näyttää siltä, että lajitiedon saa vasta päätason eventId:llä erikseen hakemalla. Eikö olisi järkevämpää, että sportId näkyisi jo ylemmän tason tiedoissa? Haen lähinnä Ebet kertoimia ja nyt joudun tekemään turhia kyselyjä, jolla selvitän lajitiedon. Haluaisin vain jalkapalloon ja jääkiekkoon liittyvät tiedot ja molemmat ominaan. Nythän joudun käymään läpi koko päätason listan ja näistä vielä erikseen kyselemään eventId:llä onko kyseinen laji jääkiekko ja jos on niin hakea vielä toisella kyselyllä tälle alikohteet yli/alle jne. kertoimet. Sama juttu sitten jalkapallolle. Jos lajitieto olisi heti päälistauksessa voisin rajata muut ulos heti ensimmäisellä kyselyllä ja keskittyä olennaiseen.

**Comment by TapaniJVeikkaus** [comment]
Tervehdys Z. ja kiitos viestistä ja kehitysehdotuksesta. Meillä on lähtökohtaisesti Betradar/Sportradar -urheiludata luokiteltu laji, sarja/kategoria, turnaus -luokkiin ja tämän mukaan laji-/sportId:n avulla tapahtumahaku pitäisi olla mahdollista. 

Toisaalta Pitkäveto taitaa pelijärjestelmän rajapinnoissa toimia juuri noin, kuten olet kuvannut ja siihen on pelijärjestelmäarkkitehtuurissamme tietyt syyt. Pitkävedon rajapintatoiminnallisuuteen ei näillä näkymin ole suunnitteilla muutoksia lyhyellä aikavälillä. Sen sijaan kiinteäkertoimisen vedonlyönnin kokonaisuudistus lähivuosina voi aikanaan vaikuttaa rajapintoihinkin. Lisäksi meillä ei ole asiakaslupausta eikä sovittua tukea Pitkävedon ohjelmallisen pelaamiseen, joten tässä asiassa olet valitettavasti aika omillasi. Kiitos yhteydenotosta ja hyvää vuodenjatkoa. Yst terv tapani jämsen

**Comment by TapaniJVeikkaus** [comment]
Moi vielä, ja sportId:t ovat nämä:
          1 Jalkapallo
          2 Pesäpallo
          3 Jääkiekko
          4 Lentopallo
          5 Koripallo
          6 Jääpallo
          7 Salibandy
          8 Moottoriurheilu
         10 Tennis
         11 Kaukalopallo
         12 Käsipallo
         13 Rullakiekko
         14 Yleisurheilu
         15 Futsal
         16 Talviurheilu
         18 Curling
         19 Golf
         20 Viihde
         21 Urheilu
         22 Am. jalkapallo
         23 Suunnistus
         24 Greyhound
         25 Kamppailulajit
         26 Pyöräily
         27 Snooker
         28 Rugby
         29 Agility
         30 Maahockey
         31 Vesipallo
         32 Baseball
         33 E-urheilu Counter-Strike
         34 Shakki
         35 Kriketti
         36 Squash
         37 Sulkapallo
         38 Pöytätennis
         39 E-urheilu League of Legends
         40 MMA
         41 E-urheilu DOTA
         43 E-urheilu StarCraft
         44 E-urheilu Call of Duty
         45 Olympialaiset
         46 Beach volley
         47 E-urheilu Overwatch
         48 Arvontapelit
         49 Darts
         50 Hevosurheilu

**Comment by zuikkelo** [comment]
Kiitos vastauksestasi. Mikäli haen pelitapahtumia aiemmin kuvaamallani tavalla, tulee Veikkauksen serverille hieman enemmän kuormaa, johtuen useista kyselyistä. Onko ko. menettely kuitenkin sallittua, vaikka kuormittaakin palvelinta?

**Comment by TapaniJVeikkaus** [comment]
Tervehdys taas, oletko tutustunut tapaan, jolla verkkokaupassamme Pitkävedon etusivulla suodatetaan tapahtumia lajin perusteella, ja lajin alla esim. sarjan perusteella? Esim. https://www.veikkaus.fi/fi/pitkaveto?sportId=1,3&selectedLeagues=1-all/3-all Ehdotan, että tsekkaat vielä verkkokauppamme toteutusta ja sen jälkeen pyrit optimoimaan ohjelmasi hakuja... yst. terv. t. j.

**Comment by zuikkelo** [comment]
Terve, kiitos loistavasta ja ilmeisesti allekirjoittaneelle liian ilmiselvästä vastauksesta. En tosiaan tullut ajatelleeksi vilkaista suoraan Veikkauksen sivuilta vaan tutkiskelin täältä githubista toteutusmallia.
Hyvää vuodenjatkoa teillekkin.

**Comment by TapaniJVeikkaus** [comment]
Hyvä, kun onnistuin opastamaan. Jatkossakin Veikkauksen verkkokauppa on paras, monipuolisin ja koeponnistetuin referenssi kaikkeen toiminnallisuuteen REST-rajapintoja vasten. Suosittelen lämpimästi sen koodiin tutustumista.
