### ISSUE TITLE
Login url changes on Tue the 4th of April

### ISSUE THREAD

**Issue by TapaniJVeikkaus** [VeikkausOy/sport-games-robot#43]
Login url will change during this spring. Please, follow this ticket for updates, the next update is on Thursday the 23rd of March.

Kind regards

Tapani Jämsen
Veikkaus Oy

**Comment by TapaniJVeikkaus** [comment]
Veikkaus.fi services and APIs are going to be updated on Tuesday the 4th of April, and, for example, 
the password data storage shall be changed. Therefore the following URL should be updated:
POST /api/v1/sessions --> /api/bff/v1/sessions


Kind regards

Tapani Jämsen
Veikkaus Oy

**Comment by TapaniJVeikkaus** [comment]
Veikkaus.fi-palvelut ja -rajapinta päivitetään tiistaina 4. huhtikuuta, jolloin myös pelaajien salasanojen tietokanta vaihdetaan. Seuraava URL on päivitettävä:
POST /api/v1/sessions --> /api/bff/v1/sessions

yst. terv.

Tapani Jämsen
Veikkaus Oy

**Comment by tmansner** [comment]
Exceliin on nyt muutettu tuo login URL uudeksi.

**Comment by tpokki** [comment]
README.md, ja python referenssitoteutus päivitetty kirjautumis URL:n osalta.

**Comment by kpson** [comment]
Onko tarkoitus että toimisi myös Excel 2003:a? Ei nimittäin toimi, syitä useampia. Tein jo yhden tätä aiemmasta (olisiko ollut 24.3.) versiosta muuntamalla sen tälle vanhemmalle excelille "sopivaan xls-muotoon" uudemmalla excel-versiolla, muuten toimi, muttei lähettänyt pelejä sisään + kasa virheilmoituksia.

Virheitä/ilmoituksia:

"Tämä tiedosto on luotu uudemmalla Microsoft Excel versiolla..."
"- Alustamattomia ActiveX-komponentteja ei avata tässä Excelin versiossa"

Jonka jälkeen Microsoft Visual Basic: "Compile error: Method or data member not found"

"Workbook/Privatre Sub Workbook_Open ()" ja kun sulkee debuggerin ja jotain kokeilee tulee (MSVB): "CAn't exit design mode because Control 'ComboBox2' canot be created

Tiedoksi vain.

PS. yksi näistä aiemmista versioista toimii täysin mutta ilman uusia ominaisuuksia siis, onneksi tallessa.

**Comment by tmansner** [comment]
Ei tosiaan varmaan toimi kovin vanhoilla Excel versioilla ja ongelmia voi olla myös Mac Excelissä.

**Comment by matsfr** [comment]
Millä versioilla toimii?
Minulla 2010 pro, eikä hyväksy kirjautumista.

**Comment by tpokki** [comment]
Hei matsfr, oletko kokeillut viimeisimmällä versiolla? Vanha login url on poistunut tänään käytöstä.

**Comment by matsfr** [comment]
Latasin taas uudemman kerran ja tuloksena sama virheilmoitus kirjautuessa.
HTTP ERROR 401
Failed to POST/api/bff/v1/sessions
Samoilla tunnuksilla pääsen kirjautumaan kylläkin Veikkauksen sivulle.
Kohteet kyllä hakee.

**Comment by kpson** [comment]
Mikä on tuo uusi login url ja mikä oli vanha (jotta voin sen hakea ja muuttaa itse vanhempaan vanhemmassakin excelissä vielä toimivassa versiossa)? Tarvitaanko muita muutoksia jotta voin välttää ilmoituksen "Failed to POST /api/v1/sessions"?

**Comment by kpson** [comment]
Käytän vahnempaa kaiketi helmikuista versiota excel 2003:lla yhdessä koneistani (ikävä kyllä sillä joka on aina lähimpänä). Loggautuminen muuttui joo ja muutos 
POST /api/v1/sessions --> /api/bff/v1/sessions on tehty. Toimii muuten, muttei tuo nimikenttään mitään salasanakentän alle. Aiemmin poimi myös sen tiedon. Lisäksi huomasin että s-postilistalta "pottimuistuttaja" Veikkaukselta tuli tervehdys, jonka mukaan etunimeni on "ETUNIMI".

**Comment by tmansner** [comment]
Nimitiedon haku muuttui myös, sitä ei sen laajemmin kerrottu kun näille roboteille lähinnä "nice to know".

Saat sen toimimaan esim. näin:
- lisää Main yksikön alkuun vakio
`
Const LoginInfoURl As String = "/api/bff/v1/sessions/self"
`
- lisää Login rutiiniin LoginUrlin POST:n jälkeen LoginInfoUrl GET kutsu
```
    Ret = Request(LoginURl, "POST", loginjson, resp)
    
    If Ret <> 200 Then
        MsgBox "Failed to POST " + LoginURl, vbOKOnly, "HTTP ERROR " + Str(Ret)
        Exit Sub
    End If

' Nimen haku
    Ret = Request(LoginInfoURl, "GET", "", resp)
    
    If Ret <> 200 Then
        MsgBox "Failed to GET " + LoginInfoURl, vbOKOnly, "HTTP ERROR " + Str(Ret)
        Exit Sub
    End If
```

Tuo spostimuistuttajan nimitiedot korjaantuvat lähiaikoina.

**Comment by tmansner** [comment]
Hei matsfr, 401 virhe tulee mm. jos on väärä salasana tai tunnus, Tarkista että ne ovat oikein lomakkeella.

**Comment by kpson** [comment]
Vaikuttaisi toimivan. Tätä rataa kun jatkaa niin kohtahan se minivakionkin lisäys vanhaan koodiin onnistuu... ja toimii myöa vanhemmalla excelillä kenties sen jälkeen. Backuppia vaan joka toimivan vaiheen jälkeen :) 
Muuten: onko kukaan kokeillut josko toimii LibreOfficella tai OpenOfficella tää makrokieli?

**Comment by matsfr** [comment]
tmansner, samoilla tunnuksilla pääsen Veikkauksen nettisivuille.
Hieman outo juttu kun etunimeni on vaihtunut eli käytössä on ollut kolmas nimeni mats niin muutoksen jälkeen käytössä on minun ensimmäinen nimeni eli Ari joka tulee näkyviin numerosarjan tilalle käyttäjätunnukselle.
Oisiko tällä joku merkitys?

**Comment by matsfr** [comment]
Kokeilin vaimoni tunnuksilla ja niillä pääsin läpi.
Johtopäätös: jotain vikaa minun tunnuksissa Veikkauksen päässä.
Olisiko joku nimisekaannus johon excel tarrautuu.
Nettisivulle pääsen.

**Comment by tmansner** [comment]
Täsmälleen sama tunnus ja salasana pitäisi toimia, joilla myös kirjaudut www sivujen kautta. Se nimi sitten kirjautumisen jälkeen on vain ensimmäinen etunimi väestörekisterin tiedoista. Vaihtui myös muillakin (kuten minulla) eri nimeksi kuin kutsumanimi.

Tarkista ettei ole ylimääräisiä "näkymättömiä" merkkejä (välilyönti, kontrollimerkki tms) tunnus tai salasana kentissä.

**Comment by matsfr** [comment]
Olisiko virhe siinä, että kun minun käyttäjätunnus alkaa nollalla ja kun kirjoitan tunnuksen ja siirryn riviä alemmas niin tunnus näkyy ilman nollaa eli excel ei hyväksy tunnuksen alkavan nollalla.
Veikkauksen sivulla nolla pysyy ensimmäisenä näkyvissä.

**Comment by tmansner** [comment]
Sehän se, muuta solun formatointi tekstiksi, niin pitäisi auttaa. Korjaan tuon johonkin tulevaan versioon.

**Comment by matsfr** [comment]
Sehän se oli. Hyvä kun selvisi. Nyt toimii.

**Comment by kpson** [comment]
#43 ja vielä exceleistä:

Latasin tämän minivakiotkin hyväksyvän version hieman uudempaan exceliin ja muunsin sen vanhempaan  .xls -muotoon 2003:kin toimivaksi. Tuntuu toimivan "kokonaan" eli en ole havainnut ongelmia, vielä ainakaan. :+1:
