### ISSUE TITLE
Vakion voitto-osuus haussa tulee err 500

### ISSUE THREAD

**Issue by piko61** [VeikkausOy/sport-games-robot#44]
Moikka,
nyt muutaman päivän ajan on Vakion voitto-osuus haku tuottanut melkein jatkuvaa virhettä:
Additional information: Etäpalvelin palautti virheen: (500) Palvelimen sisäinen virhe.

Mistä moinen voisi johtua?
Käytössä olevaan ohjelmaan en ole tehnyt muutoksia ja lauantaina Vakio 1 (100084) 18.3. toimi ihan hyvin, maanantaina ei enään toiminut, ei tiistaina eikä tänään keskiviikkona.  Hakee muutaman rivin ja sitten alkaa tulla virhettä ja homma ei etene.

**Comment by tmansner** [comment]
Palvelimilla esiintyi ajoittain vikatilanne ja se on nyt korjattu eli haut toimivat normaalisti.

**Comment by nipsux** [comment]
Moi piko61,
laitatko meiliä niin tutkitaan lisää 
asiakaspalvelu@veikkaus.fi
