### ISSUE TITLE
robot.xsml bug report

### ISSUE THREAD

**Issue by salmra** [VeikkausOy/sport-games-robot#46]
robot.xsml ei toimi minun Excelissäni.

Ongelma näyttäisi olevan siinä, että CreateSelection() funktion kutsusta PlayWagers() -funktiossa puuttuu jälkimmäinen argumentti ("NORMAL" ?).

- salmra -

**Comment by tmansner** [comment]
Kiitos huomiosta, vika korjattu nyt uusimpaan versioon.
