### ISSUE TITLE
Toto pelien perustiedot?

### ISSUE THREAD

**Issue by piko61** [VeikkausOy/sport-games-robot#47]
Moikka,
mistä löytyy (url) Toto-pelien perustiedot ja voitto-osuudet, vastaavanlaiset kuin Vakiossa?

**Comment by tpokki** [comment]
Moi,
Pääsetkö näillä ohjeilla alkuun? 
https://www.veikkaus.fi/fi/toto#!/ohjeet/pelaamisen-tyokalut

**Comment by piko61** [comment]
Kyllä, näillä mennään. Kiitokset!
