### ISSUE TITLE
Toto-pelien perustiedot

### ISSUE THREAD

**Issue by hasplund** [VeikkausOy/sport-games-robot#48]
Jostain syystä ladattavassa XML-tiedostossa ei kuitenkaan ole kyseisen päivän tietoja. Tarkalleen ottaen kerrointiedostojen nimet puuttuvat pool-tageistä. Mihin aikaan noiden pitäisi päivittyä? (kello on 11.25).

Edellisen päivän tiedot ovat tallella, vaikka niiden ei pitäisi kaiketi enää olla saatavilla.

Tulevatko XML-tiedostot jossain vaiheessa JSON-muotoon?

**Comment by tpokki** [comment]
Moi,
Nyt XML tiedostojen pitäisi päivittyä. Toistaiseksi tarjolla on vain XML tiedostot.
