### ISSUE TITLE
Onko palvelimella tehty muutoksia ?

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#49]
Kaikkien ohjelmieni tilille kirjautuminen lakkasi toimimasta yhtäkkiä. Trion torstain rivit jäi pelaamatta ja 190 e voitto lunastamatta. 

Virheilmoitus on vanha tuttu: HTTP/1.1 404

Onko loggautummisen json muuttunut jotenkin ?

**Comment by tmansner** [comment]
Url on vaihtunut 4.4. , asiasta on [Issue 43](https://github.com/VeikkausOy/sport-games-robot/issues/43).

Lisäksi etusivulla olevat ohjeet on päivitetty.  Json ei ole muuttunut.

**Comment by Ylikerroin** [comment]
Kiitos. Ongelma ratkesi tuolla, harmi etten huomannut aiemmin.
