### ISSUE TITLE
Monivedon json-sanoma

### ISSUE THREAD

**Issue by taunohyvarinen** [VeikkausOy/sport-games-robot#5]
Hei,
dokumentaatiossa sanotaan monivedon syöttämisestä seuraavaa.
"Yksittäisessä pyynnössä voi lähettää maksimissaan 25 pelitapahtumaa kerralla."
Tarkoittaako tämä, että alla olevia rakenteita voi olla yhteensä 25 vai yhdessä requestissa saa olla vain 25 moniveto riviä? Tällä tarkoitan, sitä että voiko olla yhdessä requestissa 25 erilaista järjestelmää ja näiden järjestelmien eri rivi variaatioiden määrä olla yli 25?

{"type":"NORMAL",
"drawId":"9",
"gameName":"MULTISCORE",
"selections":[
{"systemBetType":"SYSTEM","score":{"home":[2],"away":[1]}},
{"systemBetType":"SYSTEM","score":{"home":[2],"away":[1]}},
{"systemBetType":"SYSTEM","score":{"home":[2],"away":[1]}}],
"stake":20}

**Comment by umeetiusbaar** [comment]
Hei,

olisiko kyse samasta asiasta kuin tässä: https://github.com/VeikkausOy/sport-games-robot/issues/1 ? Eli puuttuu taulukkoon laitto:
```
[{"type":"NORMAL",
"drawId":"9",
"gameName":"MULTISCORE",
"selections":[
{"systemBetType":"SYSTEM","score":{"home":[2],"away":[1]}},
{"systemBetType":"SYSTEM","score":{"home":[2],"away":[1]}},
{"systemBetType":"SYSTEM","score":{"home":[2],"away":[1]}}],
"stake":20}]
```
Ks. myös https://github.com/VeikkausOy/sport-games-robot/blob/master/doc/multiscore-wager-request.json

**Comment by taunohyvarinen** [comment]
Joo oli tajusin tuon itsekin ja sitten muokkasin kysymystä.

Eli monivedossa 25 rajoitus tarkoittaako noiden alla olevien lukumäärää listassa vai listan variaatioiden lukumäärää? eli jos pelaa järjestelmiä niin voiko niitäkin olla 25 kpl, jolloin variaatioiden lkm voi olla paljon suurempi?

-Tane-

**Comment by tpokki** [comment]
Moi,
tuo rajoitus tarkoittaa että kyseisiä rakenteita (pelitapahtumia) saa yhdessä pyynnössä olla maksimissaan 25 kappaletta. Yksittäisen pelitapahtuman järjestelmän kokoa monivedon tapauksessa taitaa rajoittaa käytännössä pelitilin maksimi saldo.

**Comment by taunohyvarinen** [comment]
Hyvä kiitos tiedosta, noin arvelinkin sen olevan ja koodasin sen toimimaan noin.

-Tane-
