### ISSUE TITLE
Toto-transaktioiden haussa virhe

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#50]
Hei!

Yritin hakea omia pelattuja vetoja matkimalla web-sivunne toimintaa, mutta törmäsin virheeseen hakiessani toto-pelin transaktion kohdetta (wager):
```
400::{"code":129002,"description":"Required parameter is missing"}
```
Osoite, josta yritin tietoja hakea, oli tämän tyyppinen:
```
https://www.veikkaus.fi/api/toto-wager/v1/wager/<id>
```
missä id on transaktiossa ollut externalId.
Tämä sama menetelmä toimii muilla peleilla (url tosin eri), mutta en saa sitä nyt toimimaan toto-wagerien kanssa.

**Comment by stefanodep** [comment]
Hei,

Vaatii ensin kirjautumista järjestelmään. Kirjautumisesta palautettu isessionid on oltava mukana kutsussa. Esimerkiksi näin:

`curl --cookie "isessionid=<sessio-id>" https://www.veikkaus.fi/api/toto-wager/v1/wager/<id>`

**Comment by umeetiusbaar** [comment]
Hei,

no niinpä tietenkin. Testasin nyt suoraan toton kohdalla pelkän wagerin hakua ilman sitä edeltävää transaktioiden hakua ja siksi lipsahti kirjautuminen pois kokonaan. Kiitos!
