### ISSUE TITLE
HTTP 302 when placing SCORE wagers

### ISSUE THREAD

**Issue by kompa3** [VeikkausOy/sport-games-robot#51]
I tried to make a POST request with the following body:
```
[{
	"gameName": "SCORE",
	"drawId": "97513",
	"type": "NORMAL",
	"stake": 100,
	"selections": [{
		"score": {
			"home": [3],
			"away": [2]
		},
		"systemBetType": "NORMAL"
	}]
}]
```
The service returns HTTP 400 with the following error:
`{u'fieldErrors': [], u'code': u'INPUT_VALIDATION_FAILED'}`

Some more details:
* URL is https://veikkaus.fi/api/v1/sport-games/wagers/check
* I have made a successful login with the same session before POST request
* I tried with and without isQuickpick attribute (not shown above)
* When sending the request to https://veikkaus.fi/api/v1/sport-games/wagers, the service returns HTTP 405 with `{u'fieldErrors': [], u'code': u'METHOD_NOT_ALLOWED'}`

Any ideas what's wrong with the request?

**Comment by tpokki** [comment]
Hi,

It seems that the POST request done to /api/v1/sport-games/wagers/check did not contain request body. And the request to /api/v1/sport-games/wagers used method GET instead.

**Comment by kompa3** [comment]
Thanks for the quick feedback!

I debugged the connection in more detail, and the results are quite confusing.
```
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): veikkaus.fi
send: 'POST /api/v1/sport-games/wagers HTTP/1.1\r\nHost: veikkaus.fi\r\nContent-Length: 156\r\nAccept-Encoding: gzip, deflate\r\nConnection: keep-alive\r\nAccept: application/json\r\nUser-Agent: python-requests/2.4.3 CPython/2.7.9 Linux/4.1.13-v7+\r\nX-ESA-API-Key: ROBOT\r\nContent-type: application/json\r\n\r\n[{"gameName": "SCORE", "drawId": "97513", "type": "NORMAL", "stake": 100, "selections": [{"score": {"home": [3], "away": [2]}, "systemBetType": "NORMAL"}]}]'
reply: 'HTTP/1.0 302 Found\r\n'
header: Location: https://www.veikkaus.fi/api/v1/sport-games/wagers
header: Server: BigIP
header: Connection: Keep-Alive
header: Content-Length: 0
DEBUG:urllib3.connectionpool:"POST /api/v1/sport-games/wagers HTTP/1.1" 302 0
send: 'GET /api/v1/sport-games/wagers HTTP/1.1\r\nHost: www.veikkaus.fi\r\nAccept-Encoding: gzip, deflate\r\nX-ESA-API-Key: ROBOT\r\nAccept: application/json\r\nUser-Agent: python-requests/2.4.3 CPython/2.7.9 Linux/4.1.13-v7+\r\nConnection: keep-alive\r\nCookie: isessionid=80183A84BAB652F267C3683AC5990C1D857E1E8CC7DDD98CCDC3D6F791FB473994F33057D1E0B135FE78130E581004F27397CB7F5BB941EB860DFDF0DC6F6A738D7080267A2AE7FD29652D5B066AAAE9B0ECF69AD95FE75E28877CF86E471FBDC408993208323062926A8AA4B4819C1776234131122024A95CC631; Veikkaus=491852121.20480.0000; TS0150b1a4=0175254fa0b9b60f54a08358a545fbfd00c4ea7dd5324bc9fb6ad468d769f5f520e133d7e9c8ef0487685fcedd0af1886a1f4846e06bc01bf85457a34b0da216278a73ef22\r\nContent-type: application/json\r\n\r\n'
reply: 'HTTP/1.1 405 Method Not Allowed\r\n'
header: Date: Wed, 12 Apr 2017 17:24:16 GMT
header: Allow: POST, OPTIONS
header: Content-Type: application/json
header: Content-Length: 46
header: X-Frame-Options: sameorigin
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 1; mode=block
header: Strict-Transport-Security: max-age=86400; includeSubDomains
header: X-UA-Compatible: IE=Edge, chrome=1
header: Keep-Alive: timeout=5
header: Connection: Keep-Alive
DEBUG:urllib3.connectionpool:"GET /api/v1/sport-games/wagers HTTP/1.1" 405 46
```

It seems that the first POST requests get HTTP 302 (moved temporarily) in response, redirecting the client to the _identical_ url than the original one. Python requests library then makes a GET to that url (probably because it's identical to the original one?).

Any explanation on why /api/v1/sport-games/wagers returns HTTP 302?

**Comment by kompa3** [comment]
When I add allow_redirects = False argument to request, it just fails with HTTP 302.

**Comment by kompa3** [comment]
Now I got it! I should have had www.veikkaus.fi and not veikkaus.fi. Problem solved, thanks for the help and hope this will help someone else in the future!
