### ISSUE TITLE
Täydellinen lista GameName-arvioista

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#52]
Hei!

Mikä olisi toto-pelien myötä täydellinen lista GameName (ja Product) -arvioista? Etusivulla olevaa listaa täydentänee ainakin arvot T86 ja T75, mutta mitä muita on tullut mukaan? Ja ovatko nuo GameName ja Product 1:1. Jälkimmäisellä tarkoitan siis omien pelattujen vetojen hakemista osoitteesta
```
https://www.veikkaus.fi/api/v1/players/self/account/transactions?size=<size>&types=<types>&products=<products>&sort-by=TXDATE&showMoreState=
```
missä ```<products>``` on lista Product / GameName -arvoja.

**Comment by tpokki** [comment]
Moi,
Toto pelit päivitetty etusivulle (löytyy myös tästä alta).

```
VOI	Toto: Voittaja
SIJ	Toto: Sija
VS	Toto: Voittaja+Sija
KAK	Toto: Kaksari
KPR	Toto: Kaksari ristiin
EKS	Toto: Eksakta
EKR	Toto: Eksakta ristiin
SPA	Toto: Sijapari
SPR	Toto: Sijapari ristiin
TRO	Toto: Troikka
TRR	Toto: Troikka ristiin
DUO	Toto: Päivän Duo
T4	Toto: Toto4
T5	Toto: Toto5
T54	Toto: Toto54
T6	Toto: Toto6
T64	Toto: Toto64
T65	Toto: Toto65
T7	Toto: Toto7
T75	Toto: Toto75
T76	Toto: Toto76
T8	Toto: Toto8
T86	Toto: Toto86
T87	Toto: Toto87
```
