### ISSUE TITLE
Toton pelaaminen

### ISSUE THREAD

**Issue by RobottiAlpo** [VeikkausOy/sport-games-robot#53]
Moi, millä opilla pelataan esim.  20.4.2017 Bollnäs T64?
En ole onnistunut löytämään avoimia toto kohteita saati pelamaan niitä.

-api

**Comment by tpokki** [comment]
Moi,
Toto pelien ohjelmalliselle pelaamiselle ei valitettavasti ole vielä tarjolla ohjeistusta REST/JSON rajapinnan osalta. Toto pelien sivulta löytyy ohjeet pelaamisen työkaluille, kuten esimerkiksi pelitiedoston käyttöön: https://www.veikkaus.fi/fi/toto#!/ohjeet/pelaamisen_tyokalut
