### ISSUE TITLE
Vakio 1 voitto-osuus haku ei toimi kunnolla...

### ISSUE THREAD

**Issue by piko61** [VeikkausOy/sport-games-robot#54]
Moikka,
viimen yön (24-25.4.) palvelimen päivityksen jälkeen ei voitto-osuus haku ole antanut oikeita tietoja, vaan jotain aivan muuta.

25.4. Illalla Veikkauksen sivuilla oli viesti että Vakio 4 voitto-osuus haku ei toimi kunnolla ja että asiaa tutkitaan. Nyt kyseinen ilmoitus on poistunut, joten päättelin että asia olisi kunnossa.

Virheelliset tiedot ovat myös Veikkauksen sivuilla voitto-osuus tarkistelussa.
Esim:
Vakio 1 - Viikko 17
Voitto-osuusarviot 25.4.2017 klo 21.20.
Vaihto 50 035,50 €.
Rivit	Voitonjako 13 oikein (arvio)	kpl
111 111 111 111X	2,63 €	5121
111 111 111 1112	5,86 €	2305
111 111 111 1111	0,22 €	-4607
1–3 (Yhteensä 3 riviä)

Onko mahdollista että tarkistatte asian?

**Comment by tmansner** [comment]
Hei!

Voitto-osuuksien haussa oli tosiaan vikaa pidempään ja nyt pitäisi kaikki olla korjattu.

**Comment by matsfr** [comment]
Onko tosiaan nyt niin, että vakion gp-hajarivejä ei voi spekuloida?
Ei onnistunut viime viikolla eikä onnistunut tänään.
Vai onko vika täälläpäin?
HTTP ERROR 400
Failed to POST/api/v1/sport-games/draws/SPORT/52535/winshares

**Comment by tmansner** [comment]
Hei matsfr!

Vakion GP kohteille ei ole voitto-osuuslaskurin toiminnallisuutta saatavilla.
