### ISSUE TITLE
Miten saan pitkävetokohteiden lisärivit näkyville?

### ISSUE THREAD

**Issue by samiljin** [VeikkausOy/sport-games-robot#55]
Haettaessa pitkävetokohteita tulee näkyville vain perus voitto/tasapeli/tappio -kohteet. Kohteella on kuitenkin tietue includedRowCount, joka käsittääkseni indikoi näiden lisäkohteiden määrää. Lisäkohteilla meinaan esimerkiksi tasoituskohteita, over/under -kohteita jne. Miten näiden kertoimet on mahdollista saada rajapinnasta esille?

**Comment by tpokki** [comment]
Moi, vastaus löytyy täältä aikaisemmasta issuesta: https://github.com/VeikkausOy/sport-games-robot/issues/39

**Comment by samiljin** [comment]
Kiitos! Eipä tullu katseltua suljettuja issueita. Pahoittelut!
