### ISSUE TITLE
Voiko Tulosvedon kohteen pelivaihdon hakea jotenkin näppärästi?

### ISSUE THREAD

**Issue by tulosTaiUlos** [VeikkausOy/sport-games-robot#56]
Eli saako tällä JSON-rajapinnalla haettua pelikohteen kulloisenkin vaihdon samalla tyylillä kuin kertoimet ja muut pelitiedot?

**Comment by tmansner** [comment]
Hei!

Saat vaihdon mm. kutsulla

 `/api/v1/sport-games/draws/SCORE/{drawId}/popularity`

Vastauksena tulevassa JSON:ssa on avain "exchange", mkä on vaihto sentteinä sillä hetkellä. Vaihto päivittyy n. 10 minuutin välein, päivitysaika on avaimessa "suppoTimestamp" (Unix aika millisekunteina).
