### ISSUE TITLE
/race/{}/runners?

### ISSUE THREAD

**Issue by hasplund** [VeikkausOy/sport-games-robot#57]
Mitä race/{}/runners -tiedostossa runner_id tarkoittaa? Onko kyseessä hevoskohtainen tunnistenumero, vai tietyn lähdön kilpailijaan liittyvä numero. Eli, jos viime viikolla hevonen Valtion Monopoli juoksee runner_id:llä 123, juokseeko sama hevonen ensi viikon lähdössä myös runner_id:llä 123, vai tuleeko uusi id?

**Comment by TapaniJamsen** [comment]
Moi, tietääkseni runner_id ei ole hevoskohtainen tunniste.

yst terv tapani jämsen
Veikkaus Oy

Lähetetty iPhonesta

**Comment by TapaniJamsen** [comment]
Moi, varmistan vielä, että runnerid tosiaan on kertakäyttöinen tunnus hevoselle lähdössä.

yst terv tapani jämsen
Veikkaus Oy

Lähetetty iPhonesta

**Comment by TapaniJamsen** [comment]
Ja, saman kertakäyttöisen tunnuksen alle kuuluu myös ohjastaja, lähdöittäin...

yst terv tapani j.
Veikkaus Oy

Lähetetty iPhonesta

**Comment by TapaniJVeikkaus** [comment]
runnerId:n avulla pääseen hevosen/ohjastajan sen hetkisiin tilastoihin käsiksi, ks esim.

"startNumber": 5,
"startTrack": 4,
"handicapRaceRecord": "31,4ke",
"horseName": "Kikapo",
"coachNameInitials": "T",
"horseAge": 10,
"distance": 1620,
"ownerHomeTown": "Iisalmi",
"rearShoes": "UNKNOWN",
"gender": "TAMMA",
"frontShoesChanged": false,
"birthDate": "2007-01-01",
"driverName": "Keijo Hakala",
"mobileStartRecord": "29,8ake",
"ownerName": "Tytti Salonpää",
"coachName": "Tytti Salonpää",
"sire": "Totemi Rok",
"driverNameInitials": "K",
"damSire": "Romeo Lax",
"specialCart": false,
"scratched": false,
"frontShoes": "UNKNOWN",
"raceId": 5041426,
"color": {
                             "colorFiShort": "PRN",
                             "colorNumber": 13,
                             "colorFi": "punaruunikko",
                             "colorSv": "rödbrun",
                             "colorCode": 11
},
"prize": 338000,
"runnerId": 62754687,
"dam": "Ramonelli",
"rearShoesChanged": false,
"driverOutfitColor": "sin musta valk-valk",
"driverLicenseClass": "A",
"stats": {
                             "total": {
                                                          "starts": 38,
                                                          "position3": 4,
                                                          "position2": 1,
                                                          "position1": 4,
                                                          "record1": "29,8ake",
                                                          "year": "total",
                                                          "places": 0,
                                                          "record2": "31,4ke",
                                                          "winMoney": 338000
                             },
                             "previousYear": {
                                                          "starts": 9,
                                                          "position3": 1,
                                                          "position2": 0,
                                                          "position1": 0,
                                                          "record1": "29,8ake",
                                                          "year": "2016",
                                                          "places": 0,
                                                          "record2": "37,4ke",
                                                          "winMoney": 20000
                             },
                             "currentYear": {
                                                          "starts": 4,
                                                          "position3": 1,
                                                          "position2": 0,
                                                          "position1": 1,
                                                          "record1": "34,1akp",
                                                          "year": "2017",
                                                          "places": 0,
                                                          "record2": "33,6ke",
                                                          "winMoney": 148000
                             }
}
