### ISSUE TITLE
Voiko Monivedon kertoimien haussa page-tiedon antaa suoraan URL:n mukana?

### ISSUE THREAD

**Issue by tulosTaiUlos** [VeikkausOy/sport-games-robot#58]
Eli tarvitseeko lähettää JSON-tietuetta, jossa page-tieto on mukana? Menisi näppärästi URL:n mukana suoraan jos järjestelmä tukee tätä...

PS. Näyttää tulevan 500 kerroinyhdistelmää per sivu (mainitun sadan sijaan) Monivedossa.

**Comment by tmansner** [comment]
Hei!

Kerroinhakuun ei valitettavasti voi antaa tuota page-parametria URL:n mukana vaan se toimii vain json:n kautta. JSON muuten on samanlainen peräkkäisissä pyynnöissä, vain sivunumeroa pitää muuttaa koko järjestelmän kertoimien hakemiseksi.

Ja Monivedolla tosiaan on yhdellä kutsulla palautettavien yhdistelmien oletuslukumäärä 500.
