### ISSUE TITLE
How to handle Content-Encoding=[gzip] in Java / Groovy

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#6]
Could someone post an example of how to decompress the response body (assuming its not done by the server). For some reason, I could not get it to work, with Groovy / Java. Here is one failed example with Spring:
    
    HttpHeaders requestHeaders = new HttpHeaders();
    requestHeaders.set("Accept-Encoding", "GZIP")                         
    HttpEntity<?> requestEntity = new HttpEntity<Object>(requestHeaders);                         
    //Create a new RestTemplate instance
    RestTemplate restTemplate = new RestTemplate();                         
    // Add the String message converter
    restTemplate.getMessageConverters().add(new StringHttpMessageConverter());
    // Make the HTTP GET request, marshaling the response to a String
    ResponseEntity<String> response = restTemplate.exchange("https://www.veikkaus.fi/api/v1/sport-games/draws?game-names=SCORE", GET, requestEntity, String.class);

Also tried by manually decompressing the body content:

    String body = response.getBody()        
    new GZIPInputStream(new ByteArrayInputStream(body.getBytes("UTF-8"))).text

Which results in a rather nice exception "Content encoding is not gzipped". Would be happy with a working (Java) example.

**Comment by umeetiusbaar** [comment]
Hi!

Maybe you need to add a few more headers into the request:
```
X-ESA-API-Key: ROBOT
Content-Type: application/json
Accept: application/json
```
Also, I do not use "Accept-Encoding" header myself at all and it seems to work okay (Java+Spring RestTemplate). I also do not use StringhHttpMessageConverter - I have Jackson in CLASSPATH so the JSON conversion works okay for me.

**Comment by johan313** [comment]
Hello,

the issue is not header related, I have them all in the actual implementation (also you can succesfully query without the headers using curl). I will try using Jackson. I'm actually using Grails / Groovy and I'm starting to think this is a dependency problem (the support for "Accept-Encoding", "GZIP" is relatively new, might be that the 'bundled' Spring is too old). I will try with plain Java later today using Jackson.

This is driving me nuts, because it should be straightforward.

**Comment by johan313** [comment]
What version of Spring are you using? I switched to pure Java and the problem persists:

    <groupId>org.springframework</groupId>
    <artifactId>spring-web</artifactId>
    <version>4.1.4.RELEASE</version>

Very simple test case (almost same as above):

    public void getTargets() {
		HttpHeaders requestHeaders = new HttpHeaders();
		requestHeaders.set("X-ESA-API-Key", "ROBOT");
		requestHeaders.set(HttpHeaders.CONTENT_TYPE, "application/json");
		requestHeaders.set(HttpHeaders.ACCEPT, "application/json");
                //Not needed - does not change anything
		requestHeaders.set(HttpHeaders.ACCEPT_ENCODING, "GZIP");

		HttpEntity<?> requestEntity = new HttpEntity<Object>(requestHeaders);
		RestTemplate restTemplate = new RestTemplate();
		ResponseEntity<String> response = restTemplate.exchange(
				"https://www.veikkaus.fi/api/v1/sport-games/draws?game-names=SCORE", HttpMethod.GET, requestEntity,
				String.class);
		try {
			new GZIPInputStream(new ByteArrayInputStream(response.getBody().getBytes()));
		} catch (IOException e) {
			logger.debug("e: " + e);
		}
		logger.debug("Response: " + response);
	}
The use of GZIPInputStream is unnecessary, since the Spring docs states that GZIP should automatically be decompressed. Attached it as an example of the probable cause: The content does not appear to be gzipped (however, it clearly is when inspecting it).

**Comment by umeetiusbaar** [comment]
Hi,

I use Spring 4.1.3.RELEASE at the moment. I also use Apache Http Client:
```
      <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpclient</artifactId>
        <version>4.3.6</version>
      </dependency>
```
I construct RestTemplate for Apache HttpClient like this (this example does not include using credentials needed in booking wagers or checking saldo etc):
```
HttpComponentsClientHttpRequestFactory clientHttpRequestFactory = new HttpComponentsClientHttpRequestFactory(
        HttpClientBuilder.create().build());
RestTemplate restTemplate = new RestTemplate(clientHttpRequestFactory);
```

I hope this helps.

**Comment by tpokki** [comment]
Hi,

Using the `Accept-encoding: gzip` header should guarantee that the response is compressed. With headers like `Accept-encoding: application/json`, it is possible that the response is not compressed. 

Therefore if you need to handle the compression manually, the proper approach is to inspect whether the response contains `Content-encoding: gzip` header. If this header is present, then the response is compressed, and without it, it is not compressed.

I quickly tested with java HttpClient (no spring framework) library, and was able to make the request with automatic and manual decompression. 

```java
HttpClient clientWithoutCompression = HttpClientBuilder.create().disableContentCompression().build();
HttpClient clientWithCompression = HttpClientBuilder.create().build();
```
... i.e. pretty much what @umeetiusbaar has there in above. If needed, I can copy-paste the full class in here.

**Comment by johan313** [comment]
Thank you!

If the RestTemplate is initialized this way everything works properly. However, there must be an issue with Spring. According to the API my way should be OK. 

Sadly Groovys implementation of RestClient is basically the same that i tried and does not work ->  cannot use the grails / groovy implementation -> I will have to write my own which is a bit overhead because I already implemented the connection statefulness upon those templates.

But anyway, now that this is out of the way the rest will write itself.

Thanks!
