### ISSUE TITLE
Toto-voittojen laskennasta

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#60]
Viimeisimmän 16_29072017_R9_t4.xml-tiedoston mukaan:

"pool net-pool-major-only="40328,21" net-pool="40328,21" net-sales="62043,40" type="T4""
...
"probable amount="146,06" combination="15-3-6-3">55,20</probable"
...

MUTTA lopullinen tulos:
4 oikein 15-3-6-3 42,60 €

Mistä johtuu näin suuri ero (luvattu 55,2 e maksettu 42,6e) vaikka xml-tiedosto on viimeisin julkaistu ?
Virhe luvatun ja toteutuneen voiton välillä on (55,2-42,6)/42,6*100% = 30%

**Comment by tpokki** [comment]
Hei, ilmeisesti kaikki vaihto ei ole ehtinyt päivittymään xml tiedostoon. Mikäli haluat tapahtuneesta tarkemman selvityksen, suosittelen olemaan yhteydessä suoraan Veikkauksen asiakaspalveluun!
https://www.veikkaus.fi/fi/asiakaspalvelu

**Comment by Ylikerroin** [comment]
Niin varmaankin. Ikäväksi asian tekee se, että tuo xml-tiedosto on noudettu pelin jo sulkeuduttua, eli viimeisimmissä kertoimissa voi olla noin suuria virheitä.
