### ISSUE TITLE
Toto-tulosten lataaminen

### ISSUE THREAD

**Issue by vhpietil** [VeikkausOy/sport-games-robot#61]
Onnistuuko rajapinnasta vanhojen toto-tulosten lataaminen?

**Comment by tpokki** [comment]
Eivät varsinaisesti kuulu tuohon robottipelaamisen rajapintaan, mutta suosittelen tutkimaan https://www.veikkaus.fi/fi/tulokset#!/tulokset/toto sivun toiminnallisuutta sopivalla "kehitystyökalulla" (esim. firebug). Pikaisella vilkaisulla näyttää käyttävän ainakin tällaisia rajapintoja:

```
GET https://www.veikkaus.fi/api/toto-info/v1/cards/dates/?start=2017-08-14&end=2017-08-20
GET https://www.veikkaus.fi/api/toto-info/v1/card/711075/results
GET https://www.veikkaus.fi/api/toto-info/v1/race/4271454/competition-results
```
Nuo cardId (711075) ja raceId (4271454) lienee poimittu ensimmäisen pyynnön vastauksesta...
