### ISSUE TITLE
Toto: kaksoisvedonlyöntikertoimien hakeminen

### ISSUE THREAD

**Issue by JPKFin** [VeikkausOy/sport-games-robot#62]
Miten mahtaa onnistua muiden kuin 20 suosituimman kaksoisvedonlyöntiyhdistelmän haku pelirajapinnan kautta?

Esimerkiksi tämän illan Vermon ensimmäisen lähdön 20 pienintä kaksarikerrointa löytyy kutsulla
https://www.veikkaus.fi/api/toto-info/v1/pool/5227410/odds

(mutta en onnistu saamaan seuraavia kertoimia, tai tiettyjen yhdistelmien kertoimia tuota kautta)

**Comment by tpokki** [comment]
Olisiko tämä API tarkoituksiisi sopiva?
https://www.veikkaus.fi/api/toto-info/v1/pool/5227410/odds/all

**Comment by JPKFin** [comment]
Olipa hyvinkin - kiitokset!
