### ISSUE TITLE
14 kohteen vakion voitto-osuuksien lataus ei toimi

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#64]
Ladattaessa Vakio 4:n 14 kohteen voitto-osuuksia osoitteesta `https://www.veikkaus.fi/api/v1/sport-games/draws/SPORT/52737/winshares` ei lataus lopeta lainkaan. Nähdäkseni sen pitäisi ladata 4782969 tulosta, joita olisi sivukoon ollessa 100 47830 sivullista. Mutta tuolla viimeiselläkin sivulla on `"hasNext": true`. Missä mahtaa olla vika?

**Comment by tpokki** [comment]
Sivutus ei näköjään toimi tosiaan 14 kohteen vakioille. Mitä ilmeisemmin sivuilla on duplikaatteja, ja ilmeisesti melko paljon.

**Comment by umeetiusbaar** [comment]
Kyllä, duplikaatteja on runsaasti. Olisiko tähän mahdollisesti korjaus tulossa lähiaikoina?

**Comment by tpokki** [comment]
Valitettavasti en pysty ottamaan kantaa korjausaikatauluun. Alustavan analyysin mukaan järjestelmän pilkkominen pienemmiksi voisi auttaa. Esimerkiksi kertoimien kysyminen kolmelle "alajärjestelmälle" erikseen voisi toimia.

**Comment by umeetiusbaar** [comment]
Vika näyttäisi olevan siinä, että suurin sallittu sivunumero on 32767 ja sen jälkeen alkaa taas saamaan sivun 1 tietoja (vaikka sivunumero pyynnössä kasvaisikin).

**Comment by tpokki** [comment]
Joo, eli tosiaan jos järjestelmän koko on alle tuon 3276700, niin kyselyn pitäisi toimia oikein.

**Comment by JPKFin** [comment]
Lienee helppo ja nopea korjata jos vain muuttaa sivunumero-muuttujan tyypin isommakso tuosta 16bit signed integeristä ?

**Comment by tpokki** [comment]
Tämän pitäisi toimia nyt.
