### ISSUE TITLE
Muiden totopelien proposal request

### ISSUE THREAD

**Issue by JPKFin** [VeikkausOy/sport-games-robot#65]
Hei,

onko jossain dokumentoitu muiden kuin Toto4/5/jne -pelien proposal request - muuttujan rakenne.

Siis voittaja, sija, kaksari, troikka, päivän duo -pelien ?

**Comment by tpokki** [comment]
Lisätty muutama esimerkki lisää tänne: 
https://github.com/VeikkausOy/sport-games-robot/tree/master/doc 

Toivottavasti näistä on apua.

**Comment by JPKFin** [comment]
Kiitokset!
