### ISSUE TITLE
Porukkapelien teko ?

### ISSUE THREAD

**Issue by JPKFin** [VeikkausOy/sport-games-robot#66]
Hei,

voiko porukkapelejä tehdä ohjelmallisesti ?

**Comment by TapaniJVeikkaus** [comment]
Tervehdys, emme tue ohjelmallista pelaamista. Ks. pelaajaporukoiden säännöt. Yst terv tapani jämsen, Veikkaus Oy

Pelaajaporukat
Voit halutessasi pelata pelisi pelaajaporukaksi pelaamisen yhteydessä ennen koko pelin maksamista. Pelaajaporukan luonti tapahtuu valitsemalla Luo porukkapeli –valinta pelilomakkeella.

Voit jakaa porukkapelin 2 – 50 osuuten (jokaisen osuuden pitää maksaa vähintään 1 euro arvontaa kohden). Itsellesi jäävien osuuksien lukumäärä on vähintään yksi osuus. Et siis voi laittaa kaikkia pelaamasi porukkapelin osuuksia myyntiin.

Myyntiin laittamasi porukkaosuudet voidaan näyttää joko valitsemallesi pelaajaryhmälle (jonka jäsen olet) tai kaikille Veikkauksen asiakkaille. Mikäli jaat porukkapelisi valitsemallesi pelaajaryhmälle voit laittaa myymättömät osuudet näkymään myös muille kuin ryhmän jäsenille joko pelaamisen yhteydessä tai myöhemmin Omissa peleissä.

Maksat pelaamasi porukkapelin kokonaan. Saat hyvitystä pelitilillesi sitä mukaa kun toiset ostavat osuuksia tekemästäsi porukkapelistä. Peliajan päättyessä myymättömät osuudet jäävät sinulle. Voit seurata osuuksien myyntiä Omissa peleissä.
