### ISSUE TITLE
Monivetorivien jättäminen

### ISSUE THREAD

**Issue by hannikainen2** [VeikkausOy/sport-games-robot#67]
Moi,

Haluan viedä monivetorivejä yksitellen veikkauksen pelitilille. Ennen kokeilua rahan kanssa, haluan varmistua, että olen ymmärtänyt rajapinnan käyttäytymisen oikein. Tarkistuskutsu monivetorivin oikeellisuudesta palauttaa 200, kuten kuuluukin, mutta tuottaako seuraava json koodin alla olevat kolme riviä pelitilille?

`[  
    {  
        "type":"NORMAL",
        "drawId":"56418",
        "gameName":"MULTISCORE",
        "selections":[  
            {  
                "systemBetType":"NORMAL",
                "score":{  
                    "home":[2,0,2],
                    "away":[3,5,4]
                }
            },
            {  
                "systemBetType":"NORMAL",
                "score":{  
                    "home":[3,0,5],
                    "away":[3,3,6]
                }
            },
            {  
                "systemBetType":"NORMAL",
                "score":{  
                    "home":[1,4,2],
                    "away":[4,5,1]
                }
            }
        ],
        "stake":20
    }
]`

Nämä rivit pelitilille 20 sentin panoksilla:
- 2-3 3-3 1-4
- 0-5 0-3 4-5
- 2-4 5-6 2-1

Puuttuuko jsonista jotain?

**Comment by hannikainen2** [comment]
Tällä hetkellä yritys palauttaa REJECTED. 

- code: INPUT_VALIDATION_FAILED
- REPEATED_SELECTIONS
- INVALID_SYSTEM_BET_TYPE

Tukeeko rajapinta edellisessä viestissä kuvattua casea? Vai pitääkö minun tehdä niin monta lähetystä kuin haluan rivejä?

**Comment by tmansner** [comment]
Hei!

Pahoittelut ettei vastattu aiemmin! Tuossa sinulla on pieni virhe, merkintä "[0,1,2]" on tarkoitettu järjestelmälle ja silloin pitäisi olla "systemBetType":"SYSTEM" (jota voi kyllä käyttää aina). Hajariveille ei saa olla kuin yksi maaliluku koti-/vierasjoukkeelle. Eli kolmen hajarivin pelin voit pelata yhdellä POST: lla, mutta json:n pitää olla taulukko esim.:

```
[{
	"type": "NORMAL",
	"drawId": "53156",
	"gameName": "MULTISCORE",
	"selections": [{
		"systemBetType": "SYSTEM",
		"isQuickpick": false,
		"score": {
			"home": [1],
			"away": [2]
		}
	},
	{
		"systemBetType": "SYSTEM",
		"isQuickpick": false,
		"score": {
			"home": [2],
			"away": [3]
		}
	},
	{
		"systemBetType": "SYSTEM",
		"isQuickpick": false,
		"score": {
			"home": [3],
			"away": [4]
		}
	}],
	"stake": 5,
	"price": 5
},{
	"type": "NORMAL",
	"drawId": "53156",
	"gameName": "MULTISCORE",
	"selections": [{
		"systemBetType": "SYSTEM",
		"isQuickpick": false,
		"score": {
			"home": [1],
			"away": [1]
		}
	},
	{
		"systemBetType": "SYSTEM",
		"isQuickpick": false,
		"score": {
			"home": [2],
			"away": [2]
		}
	},
	{
		"systemBetType": "SYSTEM",
		"isQuickpick": false,
		"score": {
			"home": [2],
			"away": [4]
		}
	}],
	"stake": 5,
	"price": 5
}]
```

Toivottavasti pääset tällä eteenpäin.

**Comment by hannikainen2** [comment]
Kiitos! Ja noita rakenteita, joissa ensimmäinen rivi on "type": "NORMAL", voi olla 25 / post request?

**Comment by tmansner** [comment]
Juuri näin.

**Comment by hannikainen2** [comment]
Kiitos!
