### ISSUE TITLE
Vakion voitto-osuudet vanhoista tuloksista.

### ISSUE THREAD

**Issue by SneakyB** [VeikkausOy/sport-games-robot#69]
Kun hakee vanhoja vakiopelejä, ja niiden voitto-osuuksia, joistakin pyynnöistä tulee vastaukseksi
`{'fieldErrors': [], 'code': 'LIST_NOT_FOUND'}`
Tarkoittaako tämä, ettei Veikkauksella ole kyseisen vakion voitto-osuuksia? Kauanko noita voitto-osuuksia säilytetään?

**Comment by tpokki** [comment]
Kyllä tarkoittaa. Vanhat voitto-osuudet säilyvät tyypillisesti siihen asti kunnes uusi pelikohde avautuu samalla kohdenumerolla.
