### ISSUE TITLE
Character encoding of responses with Scandinavian characters

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#7]
There seem to be an issue concerning Scandinavian characters in the responses:

[tournamentId:1, categoryId:2, sportName:JÃ¤Ã¤kiekko, ...]

Not sure why this happens, but I suspect it has to do with the character encoding. Is this something that should be fixed by Veikkaus, or should I correct the encoding on my end?

**Comment by ceel** [comment]
Hello!

The API uses UTF-8 encoding (without bom), so using that should fix the problem.
