### ISSUE TITLE
Monivetorivien muodostaminen URL:n avulla

### ISSUE THREAD

**Issue by iiromutikainen** [VeikkausOy/sport-games-robot#71]
Aiemmin pystyi muodostamaan monivetorivit esim. linkin 
https://www.veikkaus.fi/fi/pelit?game=multiscore&target=1&stake=20&marks=(0-0-1.3.4)(1-0-0.1)(2-0.1-0.1.3) avulla muuttamalla targetia ja markseja, mutta ei tunnu toimivan enää. Uupuuko jotain vai mitä muutoksia sivuun on tehty? Löytyisikö täältä tähän ongelmaan ratkaisua?

**Comment by ceel** [comment]
Nyt näyttää myös tuon mallisetkin linkit taas toimivan :)

**Comment by iiromutikainen** [comment]
Mahtavaa :-)
