### ISSUE TITLE
Pitkäveto handicapit ym.

### ISSUE THREAD

**Issue by superspede** [VeikkausOy/sport-games-robot#72]
UKK:n mukaan "Veikkauksen JSON-rajapintojen kautta voi pelata kaikkia pelejä...". Löydän EBET-parametrillä pitkävedon pelikohteen 1X2 kertoimet, mutta en muita ko. kohteen kertoimia. Eli handicapit, yli/alle, ensimmäinen maali ym. vedot, jotka ovat löydettävissä kohteille Veikkauksen omilta sivuilta. Ovatko nämä kertoimet saatavissa API:n kautta?

**Comment by tpokki** [comment]
Pitkävetoa ei virallisesti tueta tämän ohjelmallisen pelaamisen puolella, mutta asiaa on tiedusteltu aikaisemminkin ja vastauksia löytyy mm. näistä linkeistä:

https://github.com/VeikkausOy/sport-games-robot/issues/22
https://github.com/VeikkausOy/sport-games-robot/issues/39
