### ISSUE TITLE
Vakion jättäminen, rivin jättämisessä tulee virhe.

### ISSUE THREAD

**Issue by Swamplander** [VeikkausOy/sport-games-robot#73]
Hei, tein VB:llä clientin.  1) kirjautuminen toimii, 2) saldon haku toimii, 3) vakiorivin tarkistus toimii, mutta varsinaisen vakiorivin jättämisen yhteydessä tulee kuitenkin errorcode 401 eli jotain autentikointiin liittyvää virhettä olisi kutsussa.  Kutsun pakolliset Header parametrit ovat kunnossa (muuten tulisi errorcode 400), seuraavana tulee cookiet mieleen, mutta kopioin cookiet aina jokaiseen kutsuun --> myös saldon haku toimii, joka puoltaa sitä, että cookieiden välitys myös toimii jatkokutsuilla.  

API ei palauta mitään tarkempaa virheilmoitusta 401 virheestä, niin mikäköhän voisi olla VB koodissani virheenä? Toki palvelin päästähän pitäisi näkyä mikä virhe tulee. Eli jos olette törmänneet samaan, niin kertokaas mikä puuttui tai piti lisätä, kun itse rivin jättäminen sisään ei toimi.

**Comment by tmansner** [comment]
Hei!

Luultavasti joku pakollinen parametri puuttuu, tuolta Excel VBA mallista ( [Robot.xlsm](https://github.com/VeikkausOy/sport-games-robot/blob/master/Excel%20VBA/Robot.xlsm) ) voit katsoa miten on tehty, lienee riittävän lähellä tavallista VB:ta.

**Comment by Swamplander** [comment]
Joo, VBAn koodi on hyvin lähellä VB:tä. Ainakin headerit on sinulla eri tavalla kuin Veikkauksen pakollisissa malliesimerkissä:
    xmlHttp.setRequestHeader "Accept", "application/json; charset=utf-8"
    xmlHttp.setRequestHeader "X-ESA-API-Key", "WWW"
    xmlHttp.setRequestHeader "Accept-Encoding", "gzip,deflate

Se tässä tosiaan ihmetyttää, kun saan kuitenkin saldon haettua ok, sekä rivi on syntaksin osalta ok, mutta virhe tulee, kun sen yrittää pelata. Jos pakollisia parametreja on enemmänkin, niin olisihan se hyvä olla ohjeessa; vielä parempi toki jos Response kertoisi syyn, että mikä tieto puuttuu.

**Comment by tmansner** [comment]
Jos kirjautuminen ja saldo toimii, niin ei liene headerissa vika. Jos voit, niin laita tänne millaisella POST:lla ja jsonilla yrität pelata.

**Comment by Swamplander** [comment]
Joo, tässäpä koodit siinä vaiheessa, kun kirjautuminen on tehty onnistuneesti sekä saldo haettu. Yritin saada yksinkertaisen vakiorivin läpi: 

       If bKirjautuminenOnnistui = True Then
            '****************
            '* TEHDÄÄN RIVI *
            '****************
            wRequest = WebRequest.Create("https://www.veikkaus.fi/api/v1/sport-games/wagers")
            'Määritellään ensin HEADERin arvot
            wRequest.Method = "POST"
            wRequest.ContentType = "application/json"
            wRequest.Accept = "application/json"
            wRequest.Headers.Add("X-ESA-API-Key", "ROBOT")

            LahtevaDATA = System.Text.Encoding.UTF8.GetBytes(jsonData)
            stream = wRequest.GetRequestStream
            stream.Write(LahtevaDATA, 0, LahtevaDATA.Length)

            'HAETAAN RESPONSE
            'Jotta kirjautumisessa saadut cookie tiedot välittyvät, niin tallennetaan ne uudelleen wRequestiin.
            wRequest.CookieContainer = tempcookies

            Try
                wResponse = wRequest.GetResponse
            Catch ex As Exception
                MessageBox.Show(ex.Message)
                ' Show the stack trace, which is a list of methods
                ' that are currently executing.
                MessageBox.Show("Stack Trace: " & vbCrLf & ex.StackTrace)
            End Try

            SR = New StreamReader(wResponse.GetResponseStream)
            Do
                rt = SR.ReadLine
                
                ' Jos streamissä on tavaraa, niin luetaan se Luettu rivi muuttujaan ja käpistellään sitä.
                If rt Is Nothing Then
                    ' rt on tyhjä, ei tehdä mitään.    
                Else
                    ' vielä on dataa, joten käpistellään.
                    LuettuRivi = rt.ToString
                End If
            Loop Until rt Is Nothing
            SR.Close()
            Console.WriteLine("Stream suljettu")
 
ja sitten stringinä oleva jsondata: [{"type":"NORMAL","drawId":"100114","gameName":"SPORT","selections":[{"systemBetType":"SYSTEM","outcomes":[{"home":{"selected": true}},{"home":{"selected": true}},{"home":{"selected": true}},{"home":{"selected": true}},{"home":{"selected": true}},{"home":{"selected": true}},{"home":{"selected": true}},{"home":{"selected": true}},{"home":{"selected": true}},{"home":{"selected": true}},{"home":{"selected": true}},{"home":{"selected": true}},{"home":{"selected": true}}]}],"stake":25,"price":1600}]

**Comment by tmansner** [comment]
Hei!

Tuossa sinulla jsonissa on sellainen vika että merkinnät ovat vain yhdelle hajariville, mutta annat hinnan ja tyypin systeemille. Jos muutat:
`"systemBetType":"NORMAL"`
`"price":25`
niin pitäisi mennä läpi.

**Comment by Swamplander** [comment]
Mielenkiintoista. Nyt kirjautuminen ja saldon haku menee edelleen läpi, mutta jokin on oltava JSONissa väärin, kun nyt ei mene rivin check edes läpi (tulee virheilmoitus 400). Jos yritän pelata rivin, niin tulee 401. Tässä JSON, huomaatko jotain poikkeavaa; ei kai tyhjillä merkeillä ole merkitystä:

[{"type": "NORMAL","drawId": "100115","gameName": "SPORT","selections": [{"systemBetType": "NORMAL","outcomes": [{"home": {"selected": true}},{"home": {"selected": true}},{"home": {"selected": true}},{"home": {"selected": true}},{"home": {"selected": true}},{"home": {"selected": true}},{"home": {"selected": true}},{"home": {"selected": true}},{"home": {"selected": true}},{"home": {"selected": true}},{"home": {"selected": true}},{"home": {"selected": true}},{"home": {"selected": true}}]}],"stake": 25,"price": 1600}]

**Comment by Swamplander** [comment]
äh, rivin check menikin heti ok läpi, kun pistin sekä stake=15 ja price 15.  Mutta kun yritän pelata saman rivin, niin jälleen tulee 401.

**Comment by Swamplander** [comment]
Eli ollaan alkuperäisen ongelman lähteillä. kirjautuminen onnistuu, saldon haku onnistuu ja rivin tsekkaus onnistuu, mutta varsinainen rivin pelaaminen palauttaa 401. En kyllä oikein tiedä mikä voisi olla vinksallaan:(

**Comment by tmansner** [comment]
Edelleen on ristiriita tuon "stake" ja "price" arvojen välillä, "stake" siis yksittäisen rivin hinta (25 senttiä siis tuolle lauantain vakiolle) ja "price" koko pelin hinta (yhdellä hajarivillä sama 25 senttiä).  Elikkä:
`"stake":25`
`"price":25`

**Comment by tpokki** [comment]
Toi 401 tulee jos ei ole kirjautunut sisään, eli pyynnöstä puuttuu ainakin osa kekseistä. 

Noiden keksien suhteen on hyvä huomioida että ne voivat päivittyä myös muiden pyyntöjen yhteydessä kuin kirjautuessa.

**Comment by Swamplander** [comment]
Joo, stake ja price muutettu jo aiemmin samaksi, jolloin rivin Check meni ok läpi (kommentissani ylhäällä). 

Ymmärrän, että 401 on autentikoinnista tuleva virhe, mutta kaikki cookiet toimitan seuraavissa kutsuissa sekä kirjautuminenkin toimii ongelmitta. 

Tässä testejä tältä päivältä: Kirjautumisesta tulee 3 cookieta ja saldon hausta 1 cookie, mutta kumpikaan kombinaatio ei toimi:
A) kirjaudun ja haen saldon ok --> yritän jättää rivin sisään (401)
B) kirjaudun ja yritän jättää rivin sisään (401) 

jos haen koodissa pelitietoja (https://www.veikkaus.fi/api/v1/sport-games/draws), niin täältä ei tullut yhtään cookieta. Muita kutsuja minulla ei ole koodissa, josta voisi tulla cookieita.

Luin aiempia keskuteluja, niin jollakin oli ollut sama ongelma (kirjautuminen toimii ja saldon haku, mutta ei rivin pelaaminen), niin ongelma oli poistunut, kun poisti cookiesta ylimääräisiä attribuutteja. En kyllä ymmärrä mitä ne voisi olla minun tapauksessa, koska kopioin cookiet suoraan responsesta.

Pitäisi nähdä serveripään loki mikä tieto puuttuu; huom! kirjautuminen toimii ok.

**Comment by tpokki** [comment]
Mikäli mahdollista, niin yritä debugata sekä saldon hakemisen HTTP header kenttiä (erityisesti `Cookie`), ja vertaa niitä tuohon pelin jättämispyyntöön. Mikäli kirjautumisen ja pelin jättämisen välillä ei ole kuin sekuntteja, niin peli-pyynnön pitäisi toimia kirjautumisen yhteydessä saaduilla kekseillä.

Mikäli robotti-ohjelma pyörii minuutteja, niin keksit voivat päivittyä minkä tahansa pyynnön yhteydessä.

Voit myös ottaa yhteyttä Veikkaus Asiakaspalveluun, jolloin voit jättää Veikkaukselle tarkemmat tiedot ongelmasta: pelitili, tarkka ajankohta ja mielellään tällaisessa tilanteessa täydet HTTP headerit sekä pyynnöstä että vastauksesta.

**Comment by Swamplander** [comment]
Yritän siis tehdä vain yhden vakiorivin, jotta näen toimiiko Veikkauksen API ylipäätään. Sovelluksen ajoon menee 1-3s alusta loppuun. Tein nyt selvityksen minimikutsuilla: 
Kirjautuminen (1 Post kutsu) ja rivin jättäminen (1 Post kutsu) 

Kirjautuminen meni ok, mutta rivin jättäminen kaatui 401:een.  Vertasin kirjautumisen cookiet (response) ja rivin jättämisen cookiet (Request) keskenään ultra-editillä ja ne ovat identtiset. Tässä välissä ei voi tulla muita pyyntöjä, koska niitä ei tehdä.

Pistän Veikkauksen asiakaspalveluun tiedot, jos sieltä löytyisi juurisyy missä vika.

**Comment by tmansner** [comment]
Hei!

Asiakaspalvelusta tuli tiedot, logeista näkyi (kuten aiemmin epäilty), että keksien käsittely ei toimi kunnolla.

Tein lyhyen esimerkin VB / .NET, jolla toimii kirjautuminen, saldon haku ja pelaaminen (pelaa yhden vakiorivin). Koodi löytyy gist:sta [vkrobot.vb](https://gist.github.com/tmansner/d33008ae609c5155882cc734c922950e). Toivottavasti tuosta on apua.

**Comment by Swamplander** [comment]
hei, kiitos avusta! Näkyikö logeista tarkempaa syytä mikä cookieissa oli väärin tai tuliko ne ylipäätään serverille asti? 

Ajoin esimerkkikoodisi ja se toimii minullakin ok. Sen verran debuggasin koodiasi ymmärtääkseni oman koodin juurisyytä, että cookien määrät ovat kuitenkin samat kuin minulla eli joko minun koodissa sinne kutsussa generoitui jotain ylimääräistä tai jotain puuttui.

**Comment by tmansner** [comment]
Logeista näkyi että session ylläpitoon tarvittavat keksit puuttuivat. Näkemättä koodiasi arvaisin että vika on siinä miten käytät sitä CookieContaineria. Sen osalta riittää siis, että luot kerran ja liität saman luodun objektin mukaan jokaiseen pyyntöön, kaikki keksien manipulointi tapahtuu .NET komponentin toimesta eli varsinaisen ohjelman ei tarvitse huolehtia muusta.

**Comment by Swamplander** [comment]
joo, aika samalta koodit näyttää cookien käsittelyn osalta, luon sen kerran ja kopioin cookiet ennen requestia. Varmaan jokin pikseli menee vinoon minun koodissa, koska sinun koodi toimii ongelmitta:)

Sinulla on cookien siirto kerran requestiin: webReq.CookieContainer = cookies. Minulla koodissa se on (kuten ylhäällä kommenteissa koodistani pala):
         'HAETAAN RESPONSE
        'Jotta kirjautumisessa saadut cookie tiedot välittyvät, niin tallennetaan ne uudelleen wRequestiin.
        wRequest.CookieContainer = tempcookies

Näin kotikoodarina toki ahdistaa, kun en löydä virhettä koodistani, mutta esimerkkisi avulla pääsin eteenpäin ja sain aiemmin koodaamani ohjelmani tekemän vakiojärjestelmän pelattua nyt myös ohjelmallisesti sisään. Nyt vain voittoja odottelemaan!! Kiitos tosi paljon avusta, tämän threadin voi varmastikin sulkea. Toivotaan, että tästä pohdiskelusta on muillekin apua:)

**Comment by tmansner** [comment]
Hyvä jos pääset eteenpäin. Yksi nippeli vielä, jos sinulla on WebRequest alirutiinissa ja annat CookieContainerin parametrina, niin rutiinin määrittelyssä pitää olla "ByRef", tällöin muutokset kekseissä pysyvät tallessa.
