### ISSUE TITLE
Sisältää Minivakion n. X euroa

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#74]
Ilmeisesti vakio-ohjelmani sisältää perustavaa laatua olevan virheen. Ohessa kuva, joka valaisee asiaa:

![image](https://user-images.githubusercontent.com/22799660/32406259-e20098fc-c17d-11e7-92be-c5472bec746b.png)

Vaihtoon tuon tekstin perusteella sisältyy Minivakio n. 220 000 e, eli 13-kohteen vakion vaihto on n. 524 000 e. Kuitenkin rivin 111 111 111 1111 voitto-osuus on 131,14 e ja sitä on pelattu  1532 kpl, joten siitä laskettuna vaihto 13-kohteen vakiolle on 1532 x 131,14 e /0,27 = 744 098 e eli melko tarkkaan tuo ilmoitettu ilman Minivakion osuuden vähentämistä. 

Onko siis kuitenkin niin, että ilmoitettu vaihto ei sisällä minivakiota ?

**Comment by Ylikerroin** [comment]
Löytyykö jostain ohjeita kuinka Minivakion voitto-osuuksia saa selville ohjelmallisesti ja kuinka Minivakiota voi yleensä pelata?

**Comment by tmansner** [comment]
Hei!

Tuo "sisältää MiniVakion" kertoo vain että MiniVakio pelattavissa tässä vakiossa ja "n. 220 000e" tarkoittaa arviota mikä on lopullinen 13 osuus jos vain yksi voittava rivi. Vaihto on vain pääpeli vakion eli siitä lasketaan nuo sääntöjen prosentit.  MiniVakion vaihtoa ei erikseen näytetä, sen saa selville (ja voitto-osuus arviot) `/api/v1/sport-games/draws/SPORT/{draw-id}/winshares` kutsulla kun annettuun jsoniin lisätään `"additionalPrizeTier":true` parametri.

Vastaavasti kun pelaa rivin, niin lisäämällä tuon `"additionalPrizeTier":true` saa rivin osallistumaan myös MiniVakioon.

Esimerkkejä käytöstä löytyy Excel robotista.
