### ISSUE TITLE
Vakio 1: "kohde 1, Rochdale - Wigan siirretty, oikea merkki arvotaan."

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#75]
Hei,

kuinka tuo mainittu tilanne ilmenee API:n kautta eli mistä sieltä näkee, että jokin kohde arvotaan?

**Comment by tpokki** [comment]
Moi,
Valitettavasti tieto että jokin kohde arvotaan ei ilmene API:n kautta.

**Comment by tpokki** [comment]
Tiedon lisääminen API:iin on kuulemma työlistalla, eli tulee varmaan jossain vaihessa. Voin yrittää muistaa ilmoitella täällä kun API päivittyy.
