### ISSUE TITLE
Onko pelien live-tulokset saatavilla?

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#76]
Esim. tulosvedossa, onko mahdollista hakea pelattavan ottelun sen hetkistä tulosta kesken ottelun?

**Comment by tpokki** [comment]
Ei kaikille kohteille. Vain jos sama urheilutapahtuma on pelattavissa live-vedossa, on kohteen live-tulos nähtävissä live-tapahtuman tiedoista. Tulosvedon kohteen tiedoista tulee ottaa ensiksi talteen urheilutapahtuman tunniste: `draws->rows->eventId`.

Live-vedon tapahtumalistassa sama tunniste löytyy kentästä `sportEventId`. Ja listan live-vedon tapahtumista saa taas seuraavalla pyynnöllä: 

    curl --compressed -H 'X-ESA-API-Key: ROBOT' https://www.veikkaus.fi/api/lwager/v2/live-games/events

Vastauksessa on ottelu-tilanne tämän tyyppisessä formaatissa:

      "matchStatus" : {
         "matchStatus" : "in_progress",
         "currentPeriod" : {
            "homeScore" : 33,
            "awayScore" : 2,
            "server" : 1
         },
         "homeScore" : 2,
         "awayScore" : 0
      },
