### ISSUE TITLE
kumppanuustunnuksesta

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#78]
Hei!

Onko kumppanuustunnus (affiliateId) jäänyt pois käytöstä vai mistä johtuu saamani virhe:
`
Error: 400:Bad Request:{"code":"INVALID_AFFILIATE_ID","fieldErrors":"[]"}
`
Jos kumppanuustunnuksia ei enää voi käyttää, niin päivittäisittekö dokumentaatiota siltä osin, kiitos.

**Comment by TapaniJVeikkaus** [comment]
Hei, ja kiitos huomiosta. Kumppanuustunnuksiin liittyvä toiminnallisuus on jäänyt pois tämän vuoden alusta, päivitämme dokumentaation. yst terv tapani jämsen, Veikkaus

**Comment by umeetiusbaar** [comment]
Avataankin vielä, kunnes tuo dokumentaatio on ajan tasalla tämän osalta :-)
