### ISSUE TITLE
myPartnerId

### ISSUE THREAD

**Issue by umeetiusbaar** [VeikkausOy/sport-games-robot#8]
Hei,

onko mahdollista sisällyttää Veikkauksen myPartnerId-parametria tämän rajapinnan pyyntöihin?

**Comment by tpokki** [comment]
Jep, kirjautumispyynnössä voi lähettää tuon id:n affiliateId kentässä: 

```javascript
{"type":"STANDARD_LOGIN","login":"example","password":"example","affiliateId":"1234567"}
```

**Comment by umeetiusbaar** [comment]
Hei!

Onko varmasti niin, että tuo affiliateId vastaa myPartnerId-parametria? Teemme nyt kirjautumispyynnön tuon esimerkin mukaisesti, mutta samalla sessiolla kirjatut vedot eivät silti näy palvelussa.
