### ISSUE TITLE
Toto-kysely GET /api/toto-wager/v1/ticket/{ticketId} palauttaa 201 eli peli pelattu, mutta peli ei oikeasti pelattu

### ISSUE THREAD

**Issue by jesverhal** [VeikkausOy/sport-games-robot#81]
`r = session.get(host + "/api/toto-wager/v1/ticket/" + str(ticketId), verify=True, headers=headers)`
Tein kaksari vedon. Yllä oleva koodi palauttaa arvon 201, mutta Veikkaustililtä ei mene rahaa eikä pelattuihin peleihin ilmesty uutta vetoa.

**Comment by tpokki** [comment]
Hei, 
Oletan että ennen tuota `GET` pyyntöä olet tehnyt tarvittavat `POST` ja `PUT` pyynnöt alla olevan linkin takana olevan ohjeen mukaisesti.
https://github.com/VeikkausOy/sport-games-robot#pelaaminen-1

Mikäli näin on, kannattaa olla yhteydessä suoraan asiakaspalveluun, niin voit jättää sinne tarkemmat tiedot kuten pelaajatunnuksen, kellonajan ja tuon tiketin tunnisteen ongelman selvittämistä varten.
https://www.veikkaus.fi/asiakaspalvelu

**Comment by jesverhal** [comment]
Tein tarvittavat `POST` ja `PUT` pyynnöt.

`POST` pyyntö: `session.post(host + "/api/toto-wager/v1/bet/" + str(poolId), verify=True, data=json.dumps(wager), headers=headers)`

`POST` pyyntö palautti: `{'proposalId': 61564979}`

`GET` pyyntö: `session.get(host + "/api/toto-wager/v1/bet/" + str(proposalId), verify=True, headers=headers)`

`GET` pyyntö palautti statuskoodin 201

`PUT` pyyntö: `session.put(host + "/api/toto-wager/v1/bet/" + str(proposalId), verify=True, headers=headers)`

`PUT` pyyntö palautti statuskoodin 202 ja `{'ticketId': 61564979}`

`GET` pyyntö: `session.get(host + "/api/toto-wager/v1/ticket/" + str(ticketId), verify=True, headers=headers)`

`GET` pyyntö palautti statuskoodin 201

Olisiko mahdollista että jossain noista pyynnöistä oli virhe, mutta serveri silti palautti oikeita arvoja.

 Keskustelin asiakaspalvelun chatissa asiasta, mutta asiakaspalvelija ei osannut auttaa.

**Comment by jesverhal** [comment]
Löysin vian. 
Olin olettanut että kun `GET`proposalId:llä palautti statuksen 201, niin se tarkoittaisi hyväksyttyä peliehdotusta, mutta se tarkoittaakin vain, että serveri on tarkastanut peliehdotuksen ja se voi olla myös hylätty. 
Minulla GET palautti: `{'discarded': [{'betType': 'KAK', 'selections': [[10, 15]], 'stake': 100, 'error': {'descriptionArguments': {'expectedLegs': 2, 'actualLegs': 1}, 'description': 'Not enough legs in selection: actual ${actualLegs}, expected ${expectedLegs}', 'code': 122001}, 'cost': 100}], 'valid': False, 'proposals': []}` eli siellä on virhe. Oletin myös että edellä olevan GET pyynnön jälkeen tehdyt PUT ja GET pyynnöt palauttaisivat jonkin virheen jos peliehdotusta ei oltu hyväksytty.
