### ISSUE TITLE
Historiadata: Tulosvedon lopulliset kertoimet

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#82]
Hei, 

onko mahdollista hakea tulosvedon lopullisia kertoimia aikaisemmista otteluista, esim vuodelta 2017?  Voittokerroin löytyyy, mutta kiinostaisi koko jakuama.

**Comment by tmansner** [comment]
Hei!

Valitettavasti tuollaista palvelua ei ole tällä hetkellä olemassa, vain oikean tuloksen kertoimet voi hakea.

**Comment by johan313** [comment]
Mikäli rajapintoja edelleen kehitetään, niin esitetän toivomuksen, että historiadatan haku huomioitaisiin jatkossa.

**Comment by tpokki** [comment]
Toive välitetty eteenpäin :)
