### ISSUE TITLE
SSL autentikointi lakkasi toimimasta 18.5. alkaen

### ISSUE THREAD

**Issue by jep66** [VeikkausOy/sport-games-robot#84]
Näyttäisi siltä, että 18.5. SSL autentikointi lakkasi toimimasta (16.5. ohjelma toimi vielä). Kun yritän lukea esim. kerrointiedostoja veikkauksen palvelimelta WebClientilla (VB.NET) yhteyden muodostaminen katkeaa virheeseen "Taustalla oleva yhteys suljettiin". Miten yhteyden saisi taas pelittämään. Käytän webclient:ia seuraavasti:

Dim instance As WebClient 
Dim address As Uri 
Dim fileName As String
instance.DownloadFile(address, fileName)

**Comment by tmansner** [comment]
Hei!

Viime viikolla poistettiin tuki vanhoilta TLS protokolleilta ja luultavasti se aiheuttaa ongelman. WebClient käyttää varmaankin IE:n asetuksia, tarkista ohjauspaneelin Internet ominaisuuksien Lisäasetukset osiosta että TLS 1.2 on valittuna.

**Comment by JPKFin** [comment]
Tuollaisista muutoksista joilla voi olla vaikutuksia rajapintojen käyttöön olisi jatkossa mukava kuulla etukäteen..
Itsekin jouduin päivittämään curl:in openSSL -paketin uudempaan juuri tästä samaisesta syystä huomattuani että sovellus lakkasi toimimasta.

**Comment by jep66** [comment]
Kävin katsomassa IE:n lisäasetuksista TLS-täpät ja mulla oli täpät kohdissa TLS 1.0, TLS 1.1 sekä TLS 1.2. Niillä ei ollut vaikutusta WebClientin toimintaan. Kiitos kuitenkin ehdotuksesta, jotenkin tämä ongelma on varmaankin kiinni TLS-protokollien tuen poistumisesta. Olisiko muuta ehdotusta miten voisin ohittaa ongelman?

**Comment by jep66** [comment]
Minulla on käytössä Visual Studio 2008 ja  .NET 3.5 ja sain selvitettyä nyt ettei .NET 3.5:ssä ole suoraa tukea TLS 1.2 protokollan käytölle. Sain netistä selville, että VB:stä kuitenkin löytyy koodipätkä, joka saa .NET Frameworkin (2.0, 3.5 jne.) käyttämään TLS 1.2 protokollaa. Lisäämällä seuraavan koodirivin VB projektiini, sain yhteyden taas pelaamaan:
System.Net.ServicePointManager.SecurityProtocol = DirectCast(3072, System.Net.SecurityProtocolType)

Toivottavasti tästä on apua muillekin, jotka ovat ongelmaan törmänneet.

**Comment by JPKFin** [comment]
Sellainen irtohuomio vielä tähän TLS-asiaan liittyen, että olisko tälle sivulle
/api/toto-info/v1/xml/cards.xml
tehtävissä jotain - oheinen tuolta sivulta löytyvä virhe aiheuttaa nyt harmaita hiuksia:
--
This XML file does not appear to have any style information associated with it. The document tree is shown below.
--

**Comment by tpokki** [comment]
Moi @JPKFin 
Käsittääkseni tuo "virhe" tulee joillakin selaimilla tarkasteltaessa XML dokumenttia, johon ei ole liitetty tyylitietoja (XSLT). Tuo kyseinen XML on tarkoitettu luettavan ohjelmallisesti, eikä sen siis ole tarkoituskaan sisältään noita tyylitietoja. 

XML:n pitäisi latautua oikein esimerkiksi tuolla `curl`:lla.

**Comment by JPKFin** [comment]
@tpokki - tämä cards.xml ei nimenomaan syystä tai toisesta lataudu curlilla oikein - http return code on 500 ja virheilmoitusrakenteesta löytyy:
--
stdClass Object ( [code] => 0 [description] => Unknown error occurred: ${errorMessage} [descriptionArguments] => stdClass Object ( [errorMessage] => system error ) )
--

**Comment by tpokki** [comment]
Moi @JPKFin 
Ilmeisesti käytät pyynnössäsi `Accept` headeriä joka ei vastaa XML tietotyyppiä (esim. `application/json`). Eli jätä `Accept` kokonaan pois, tai laita arvoksi `text/xml`. 

Valitettavasti virheviesti ei ole kovin kuvaava (parannetaan jossain vaiheessa). Mutta toimii tosiaan esimerkiksi tällä komennolla: 

```
$ curl -H 'Accept: text/xml' -H 'X-ESA-API-Key: ROBOT' https://www.veikkaus.fi/api/toto-info/v1/xml/cards.xml
```

**Comment by JPKFin** [comment]
Joo. Käytän itse asiassa curlia PHP:n kautta mac (OSX) -ympäristössä..
Suoraan OSX-komentoriviltä tuo curl-kutsu toimiikin hyvin jos jätän vielä Accept html/text -option pois.

PHP taitaa sitten taas uudelleen sotkea headereitä koska sitä kautta en ole vielä saanut rakennetta siististi luettua - pitänee tutkia tuota ehtiessään lisää. 
Kun päivitin PHP:nkin uusimpaan versioon (jotta SSL tuli sielläkin ajan tasalle) niin XMLReader -palikan kautta tuo taas sitten lukeutuu aivan nätisti. Go figure..
