### ISSUE TITLE
eventID puuttuu (Tulosveto)

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#87]
Hei, aika ajoin otteluista puuttuu EventID minkä seurauksen ei voi hakea kohteen lisätietoja:

Ohessa yksi esimerkki koripallosta:

[resultsAvailableTime:1532120399000, brandName:14, gameName:SCORE, drawTime:1532120399000, closeTime:1532091480000, id:105045, openTime:1532067600000, gameRuleSet:[minStake:30, quickPickAvailable:true, maxPrice:1000000, oddsType:VARIABLE, maxSelections:10, maxStake:10000], rows:[[score:[min:50, max:100], id:0, outcome:[away:[name:Suomi U20], home:[name:Venäjä]]]], status:OPEN]

Onko tämä tilanne mitä pitää hallita omassa päässä (nythän pakostakin nämä jäävät pelaamatta), vai onko tämä virhetilanne Veikkauken puolella?

**Comment by TapaniJVeikkaus** [comment]
Hei, EventID:n puuttuminen on valitettavasti mahdollista silloin tällöin aina urheiludatan toimittajalta lähtien, joten sinun kannattaa varautua hallitsemaan tällainen poikkeustilanne sovelluksessasi. Hyvää kesän jatkoa.
