### ISSUE TITLE
Aiempien ravien lähtölistat

### ISSUE THREAD

**Issue by LabradorinNoutaja** [VeikkausOy/sport-games-robot#88]
Muutaman viikon vanhojen ravien lähtölistoista ovat kadonneet hevosen tilastotiedot kuluvalta ja edelliseltä vuodelta ja uran ajalta sekä edelliset startit (esimerkkinä Vermo 4.7.2018, lähtö 9, raceid 4416445). Aiemmin ko. tiedot löytyivät raveista monen vuoden takaa. Lieneekö tässä takana vakaa harkinta vai onko kysymys vahingosta.

Lähtölistat saisivat pysyä samanlaisina kuin ne ovat olleet ennen lähtöä. Todennäköisyyslaskennan parametreja on vaikea testata, jos lähtötiedot eivät ole käytettävissä samanlaisina kuin ennen kilpailua.

**Comment by stefanodep** [comment]
Tämä on välitettävästi normaali toiminnallisuus. Kaksi viikkoa vanhemmilta lähtölistoilta poistetaan hevosten tilastotiedot sekä edelliset startit, aivan kuten on poistettu aina ennenkin.
