### ISSUE TITLE
cURL ja minivakion winShares - value

### ISSUE THREAD

**Issue by mackepee** [VeikkausOy/sport-games-robot#89]
Perusvakion voittoennuste riville löytyy iisisti, ['winShares']['0']['value'], mutta mihin on piilotettu minivakion voittoennuste?

**Comment by tmansner** [comment]
Hei!

Minivakiolle saa voitto-osuudet kun parametrina annettavaan jsoniin lisää "additionalPrizeTier: true" ja merkintöjä vain minivakion otteluille. 

Esim. 
```
{
	"page": 0,
        "additionalPrizeTier": true,
	"selections": [{
	"systemBetType": "SYSTEM",
	"outcomes": [{
			"away": {
				"selected": true
			}
         },
         ...
}
```

Vastaus vastaavasti sisältää vain minivakiolle voitto-osuudet.

**Comment by mackepee** [comment]
Täydellistä! Kiitoksia!
