### ISSUE TITLE
vakion peliprosentit

### ISSUE THREAD

**Issue by mikkome** [VeikkausOy/sport-games-robot#90]
yritän php:lla saada haettua vakion peliprosentit. tein ohjeen mukaan, mutta saan ilmoituksen, että list not found. mistä löydän oikein id:een että saan imuroitua tuon jakauman. vakiokohteiden haku kyllä onnistuu. kiitos :)

**Comment by mikkome** [comment]
No niin nyt toimii. Eli tuo id:een tsekkaus pitää tehdä aina uuden viikon koettaessa, eli se muuttuu joka viikko. Eipä se ole ongelma toki. Kiitos

**Comment by tpokki** [comment]
`awdPercentage` on mini-vakion peliprosentti.
