### ISSUE TITLE
15.9.2018 n. klo 11 alkanut ongelma rivien pelaamisessa

### ISSUE THREAD

**Issue by 10Andy10** [VeikkausOy/sport-games-robot#91]
Lauantain järjestelmäpäivityksenne jälkeen rivejä ei ole pystynyt pelaamaan kunnolla. Yksittäisen rivin/kupongin lähetys joskus onnistuu, joskus menee muutamakin peräkkäin, mutta hyvin satunnaisesti. Käytössä PHP, cURL, Centos 7.5. Kun pelaaminen katkeaa, niin virheilmoitus on:

{"code":"NOT_AUTHENTICATED","fieldErrors":[]}

Osaisitteko kertoa onko teillä tiedossa oleva vika, tai jokin uusi ominaisuus joka tämän pelaamisen katkeamisen voi aiheuttaa?

**Comment by 10Andy10** [comment]
Ongelma koskee kolminumeroista pelaajamäärää ja erityisesti Monivetoa ja Vakiota.

**Comment by 10Andy10** [comment]
OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.veikkaus.fi:443

**Comment by tpokki** [comment]
Moi, asiaa selvitetään.

**Comment by 10Andy10** [comment]
Tällä hetkellä näyttäisi toimivan normaalisti.

**Comment by 10Andy10** [comment]
Nyt on toiminut hyvin. Kiitos korjauksesta.
