### ISSUE TITLE
Useita virheitä Tulsovedon "check" endpointissa

### ISSUE THREAD

**Issue by johan313** [VeikkausOy/sport-games-robot#92]
Hei

viime päivien aikana lokille on ilmestynyt paljon virheitä tulsovedon check-endpointista: https://www.veikkaus.fi/api/v1/sport-games/wagers/check

**Virhe on:**
I/O error on POST request for "https://www.veikkaus.fi/api/v1/sport-games/wagers/check": Connection reset; nested exception is java.net.SocketException: Connection reset

JAVA:n dokumentaation mukaan:

> Thrown to indicate that there is an error in the underlying protocol such as a TCP error

Onko rajapinnassa muuttunut jotain viimeaikoina mitä pitäisi huomioida? Jos ei, niin syy on luultavasti veikkausken puolella sillä jos tässä olisi yleinen tietoliikennevirhe, niin tämä näkyisi myös muissa kutsuissa mutta tämä virhe ilmenee vain tässä _/check_ endpointissa.

Tämä koskettaa sekä jalkapalloa, jääkiekkoa että sählyä.

**Comment by tpokki** [comment]
Todennäköisesti sama ongelma kuin #91:ssa.
