### ISSUE TITLE
API:ssa häiriötä?

### ISSUE THREAD

**Issue by kurjenmiekka** [VeikkausOy/sport-games-robot#93]
Hei!

Onko jotakin häikkää API:ssa? Ei ole toiminut kunnolla ainakaan tänään (17.9.).
Esim. robot.py esimerkkitoteutuskin heittää välillä erroria vaikkapa saldokyselyssä:

requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))`

Vakion rivien voitto-osuuksia ei käytännössä pysty em. vuoksi hakemaan.

**Comment by tpokki** [comment]
Sama ongelma kuin #91:ssa.
