### ISSUE TITLE
Kokoonpanojen hakeminen pitkävedosta

### ISSUE THREAD

**Issue by npelkone** [VeikkausOy/sport-games-robot#94]
Moi. Pystyykö pitkävedosta löytyviä Liigan pelien kokoonpanoja hakemaan? Responsen html ei näyttäisi palauttavan tuota kokoonpanojen osuutta ollenkaan. Login palauttaa kyllä 200? Kiitos! :)

**Comment by TapaniJVeikkaus** [comment]
Moi, meillä ei ole kokoonpanojen hakumahdollisuutta ohjelmallisen pelaamisen rajapinnan kautta. Ks. https://www.veikkaus.fi/fi/liiga esim. tänään Jukurit-Lukko-kokoonpanot julkaistaan iltapäivän aikana

yst terv tapani jämsen, Veikkaus
