### ISSUE TITLE
Oman pelihistorian hakeminen, voitot eivät näy listalla

### ISSUE THREAD

**Issue by jarmo99** [VeikkausOy/sport-games-robot#95]
Oman pelihistorian hakeminen palauttaa vain tehdyt ostot (BUY), voitot eivät tule näkyviin listalle (WIN).
Kyseessä totopelit joihin tehty ostoja, ja joskus on tullut jopa muutama voittokin, mutta ne eivät näy listalla.

Haku esim. kutsulla: /api/v1/players/self/account/transactions?size=50&sort-by=RESULT_DATE

**Comment by tpokki** [comment]
Moi, kokeile jos saat voitot näkyviin jos käytät järjestämiseen `TXDATE` arvoa:
```
/api/v1/players/self/account/transactions?size=50&sort-by=TXDATE
```

**Comment by jarmo99** [comment]
Jep, näyttää toimivan tuolla TXDATE arvolla. Kiitos.
