### ISSUE TITLE
Kaksari- kertoimista

### ISSUE THREAD

**Issue by Ylikerroin** [VeikkausOy/sport-games-robot#96]
Osa tiedoista on kätevämpi noutaa json-avulla, mutta kertoimien kohdalla on pakko käyttää xml, jos haluaa kaikki kertoimet.

Miksi JSON:lla

1)
http://www.veikkaus.fi/api/toto-info/v1/pool/ + poolId + /odds
saa vain 20 pienikertoimisinta kerrointa eikä kaikkia pelattuja ?

2) 
xml
www.veikkaus.fi/api/toto-info/v1/xml/8_17112018_R3_kak.xml
palauttaa kaikki, mutta  sitä varten olisi tiedettävä ratakoodi (esimerkissä 8), mutta miksi niitä kaikkia ei ole annettu ohjeissa "Kotimaiset raviradat ja käytetyt lyhenteet (käytetty kirjainlyhenne annettu)"? 

https://www.veikkaus.fi/fi/toto?sort=TXDATE&track=Ku&date=2018-11-18&pool=VOI&race=1#!/ohjeet/pelaamisen_tyokalut/pelitiedosto

Löytyykö ratakoodit (numerot jostain)?

**Comment by Ylikerroin** [comment]
Jotain hämärää näissä track-code:ssa on  (6.1.1019)

"YLIVIESKA"  track-code="16"  =>  file="16_06012019_R1_voi.xml %
"ROMME" track-code="55" ==> file="46_06012019_R1_voi.xml ????
"UMÅKER" track-code="54" ==> file="67_06012019_R1_voi.xml ?????
"FORUS" track-code="53" ==> file="60_06012019_R1_voi.xml ????
"CAGNES-SUR-MER" track-code="84" ==> file="84_06012019_R1_voi.xml %
"VINCENNES" track-code="60" ==> file="56_06012019_R1_voi.xm ????

Ainoastaan Ylivieskan ja CAGNES-SUR-MER:n kerrointiedostot alkavat oikein ?

**Comment by tpokki** [comment]
Ratanumerot eivät tosiaan aina täsmää. Ilmeisesti ongelma koskee pääasiassa ulkomaisia- ja kesäratoja. Valitettavasti ei ole tietoa tarkemmasta korjausaikataulusta.
